-- =====================================================================
-- WineCatalog — O CATÁLOGO DE VINHOS (schema `winecatalog`)
--
-- FONTE DE VERDADE. Este ficheiro é a única definição do catálogo que
-- existe em lado nenhum. Esteve até setembro de 2026 num schema à parte
-- (`catalogo`) e num terceiro repo (Garrafeira), e mudou-se para aqui —
-- ver `db/migracao-catalogo-para-winecatalog.sql` para o porquê e para o
-- como.
--
-- O QUE ISTO É: a memória do que já se sabe sobre um vinho — o que a IA
-- já procurou (nas apps todas), e o que alguém já confirmou por ter a
-- garrafa em casa. Existe por uma razão só: cada chamada à IA custa
-- dinheiro, e a ficha de um vinho não muda de semana para semana. Se
-- alguém já procurou "Quinta do Crasto Reserva 2019" na WineSelection,
-- a Garrafeira não tem de a procurar outra vez — e vice-versa.
--
-- O QUE ISTO NÃO É: não guarda uma linha do que é de alguém. Aqui entra
-- só o que é FACTO SOBRE O VINHO (a referência: castas, região, nota do
-- Vivino, preço médio de mercado) — nunca o que é da GARRAFA ou da
-- PESSOA: quanto se pagou, onde está arrumada, as notas escritas à mão, a
-- fotografia tirada em casa. É a mesma linha que a Garrafeira já traça
-- entre "vinho" e "garrafa", e é ela que torna este catálogo partilhável
-- sem partilhar garrafeira nenhuma.
--
-- QUEM LHE TOCA, e por onde:
--   · a WineCatalog (esta app) — pelas funções de leitura e de decisão
--     lá em baixo, com o JWT de uma pessoa;
--   · a `vinho-info` (Garrafeira) e a `sugerir-vinho`/`verificar-vinhos`
--     (WineSelection) — por RPC com a service role, e só pelas três:
--     `juntar`, `procurar`, `procurar_lote`;
--   · o trigger `garrafeira.vinhos_catalogo` — esse vive no repo
--     Garrafeira (pendura-se em `garrafeira.vinhos`, que é dela) e chama
--     `winecatalog.juntar`.
--
-- Correr DEPOIS de `db/schema.sql` (precisa da `winecatalog.allowed_users`
-- para saber quem pode ler). É IDEMPOTENTE.
--
-- Quase todos os comentários abaixo vêm do ficheiro original e ficam
-- como estavam: foram pagos com erros, e um erro que já se cometeu é a
-- coisa mais barata que este ficheiro tem.
-- =====================================================================

-- A service_role não tem acesso a schemas fora de `public` só por ser
-- service_role — BYPASSRLS é sobre policies, não sobre GRANTs. Sem isto,
-- as três Edge Functions falham com 42501 e sem uma palavra do lado de
-- quem chama. (Mesma nota que já está no `wineselection/db/schema.sql`.)






-- ---------------------------------------------------------------------
-- A tabela
--
-- A ficha é um `jsonb` e não vinte colunas de propósito: quem a lê e quem
-- a escreve são Edge Functions que já trabalham em JSON, e a JUNÇÃO (ver
-- `winecatalog.juntar`) percorre os campos um a um — com colunas, essa função
-- eram vinte atribuições escritas à mão que alguém se esquecia de
-- acrescentar no dia em que aparecesse um campo novo.
--
-- `origens` é a proveniência CAMPO A CAMPO: {campo: {o:origem, f:força,
-- em:quando}}. É o que permite juntar duas leituras sem uma apagar a
-- outra às cegas — uma pesquisa a sério não deve ser substituída por uma
-- extração mais fraca, e nada deve substituir o que alguém confirmou por
-- ter a garrafa na mão.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.vinhos (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  -- DUAS identidades por linha, e é preciso que sejam duas: ver
  -- `winecatalog.achar()`. `chave` é o nome MAIS o produtor; `chave_nome` é só
  -- o nome, como vem escrito numa carta de restaurante.
  chave         text NOT NULL,          -- nome+produtor+ano ("crasto-reserva|2019")
  chave_base    text NOT NULL,          -- o mesmo sem o ano
  chave_nome    text,                   -- só o nome+ano; NULL quando o nome
                                        -- sozinho não distingue nada
  base_nome     text,                   -- o mesmo sem o ano
  nome          text NOT NULL DEFAULT '',
  produtor      text NOT NULL DEFAULT '',
  ano           integer,
  ficha         jsonb NOT NULL DEFAULT '{}'::jsonb,   -- os factos do vinho
  origens       jsonb NOT NULL DEFAULT '{}'::jsonb,   -- proveniência campo a campo
  fontes        jsonb NOT NULL DEFAULT '[]'::jsonb,   -- [{titulo,url}], no máximo 8
  vezes         integer NOT NULL DEFAULT 0,           -- quantas vezes foi escrito (diagnóstico)
  visto_em      timestamptz NOT NULL DEFAULT now(),   -- última vez que serviu uma pergunta
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vinhos_pkey PRIMARY KEY (id),
  CONSTRAINT vinhos_chave_uniq UNIQUE (chave)
);

CREATE INDEX IF NOT EXISTS vinhos_chave_base_idx ON winecatalog.vinhos (chave_base);
CREATE INDEX IF NOT EXISTS vinhos_chave_nome_idx ON winecatalog.vinhos (chave_nome);
CREATE INDEX IF NOT EXISTS vinhos_base_nome_idx  ON winecatalog.vinhos (base_nome);
CREATE INDEX IF NOT EXISTS vinhos_visto_idx      ON winecatalog.vinhos (visto_em DESC);

-- RLS ligada e SEM UMA ÚNICA POLICY, de propósito: isto tranca a tabela a
-- toda a gente menos à service_role (que passa por cima da RLS). Não há
-- GRANT nenhum a `anon`/`authenticated` — nem de leitura. Quem alimenta o
-- catálogo do lado do browser é o trigger da Garrafeira, e esse é
-- SECURITY DEFINER: escreve sem que a pessoa tenha de poder escrever aqui.
--
-- Porquê tão fechado, se o que está cá dentro não é de ninguém: a LISTA de
-- vinhos que passaram por aqui diz alguma coisa sobre o que as pessoas têm
-- em casa, mesmo que cada linha à parte não diga. Uma leitura por nome
-- (que é tudo o que as apps precisam) não é a mesma coisa que poder ler a
-- lista toda, e é só a primeira que se abre — pela Edge Function.
ALTER TABLE winecatalog.vinhos ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- AS DUAS TABELAS DA DECISÃO HUMANA
--
-- Nascem aqui em cima, e não lá para o fim ao pé das funções que as usam,
-- por uma razão de mecânica: a `winecatalog.achar()` passou a resolver
-- aliases, e uma função `LANGUAGE sql` é validada quando se CRIA. A pôr
-- estas tabelas depois dela, o ficheiro não corre.
--
-- `alias`: "estas duas linhas são o mesmo vinho". A linha perdedora NÃO
-- se apaga e NÃO se lhe tocam as chaves — fica como está, e é a `achar`
-- que passa a responder com a linha-alvo quando esbarra nela. Desfazer é
-- literalmente apagar uma linha desta tabela.
--
-- `distintos`: "estas duas NÃO são o mesmo". Sem isto, a lista de
-- candidatos volta a propor o mesmo par todas as semanas — e uma lista
-- que insiste em erros deixa de se ler, que é o caminho para alguém
-- carregar em "são o mesmo" sem olhar e juntar um Vallado a um Esporão.
-- O par guarda-se sempre ordenado (a < b) para que marcar (A,B) e marcar
-- (B,A) sejam a mesma linha.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.alias (
  chave_de       text NOT NULL,          -- a chave da linha que deixou de responder
  chave_para     text NOT NULL,
  id_de          bigint NOT NULL,
  id_para        bigint NOT NULL,
  nome_de        text,
  ano_de         integer,
  -- {campo: {antes, antes_origem, depois_origem}} — o estado ANTERIOR de
  -- cada campo que a fusão mexeu, para desfazer ser exato e não um palpite
  campos_movidos jsonb NOT NULL DEFAULT '{}'::jsonb,
  quem           text,
  quando         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alias_pkey PRIMARY KEY (chave_de)
);
CREATE INDEX IF NOT EXISTS alias_para_idx ON winecatalog.alias (id_para);
CREATE INDEX IF NOT EXISTS alias_de_idx   ON winecatalog.alias (id_de);

CREATE TABLE IF NOT EXISTS winecatalog.distintos (
  chave_a text NOT NULL,
  chave_b text NOT NULL,
  quem    text,
  quando  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT distintos_pkey PRIMARY KEY (chave_a, chave_b),
  CONSTRAINT distintos_ordem_chk CHECK (chave_a < chave_b)
);

-- ---------------------------------------------------------------------
-- QUEM MANDA no catálogo
--
-- Numa LINHA e não fixo em código, mesmo desenho do `garrafeira.config`:
-- passar a app a outra pessoa tem de ser um clique e não um deploy. O
-- COALESCE é a rede de segurança — se alguém apagar a linha, o catálogo
-- não fica sem admin nenhum (o que o trancaria para sempre: não haveria
-- ninguém com direito a repor a linha).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.config (
  chave text NOT NULL,
  valor text NOT NULL,
  CONSTRAINT config_pkey PRIMARY KEY (chave)
);
INSERT INTO winecatalog.config (chave, valor)
VALUES ('admin_email', 'diogo.andre.f.silva@gmail.com')
ON CONFLICT (chave) DO NOTHING;

ALTER TABLE winecatalog.alias     ENABLE ROW LEVEL SECURITY;
ALTER TABLE winecatalog.distintos ENABLE ROW LEVEL SECURITY;
ALTER TABLE winecatalog.config    ENABLE ROW LEVEL SECURITY;



-- ---------------------------------------------------------------------
-- A CHAVE: como é que dois vinhos são o mesmo vinho
--
-- ISTO VIVE AQUI E SÓ AQUI, de propósito. As Edge Functions das duas apps
-- nunca calculam uma chave: mandam nome, produtor e ano, e é o SQL que
-- decide o que é o mesmo vinho (`winecatalog.procurar`, `winecatalog.juntar`).
-- A primeira versão tinha o algoritmo repetido em TypeScript nos três
-- lados, com um aviso grande a dizer para os manter iguais — e um aviso
-- desses é uma dívida à espera: no dia em que um deles divergisse, o
-- catálogo PARTIA-SE EM DOIS em silêncio (as mesmas garrafas em linhas
-- diferentes, ninguém a acertar com a do outro) e a única coisa que se
-- notava era a conta da IA a não descer. Uma cópia só não pode divergir.
--
-- As regras, e porquê:
--   · sem acentos e em minúsculas — "Rosé" e "rose" são o mesmo vinho;
--   · o ANO sai do nome (fica no seu campo) — a carta escreve "Papa Figos
--     2020" e a garrafeira escreve nome + ano em campos separados;
--   · abreviaturas de carta expandidas (qta. -> quinta);
--   · as palavras VAZIAS ("de", "do", "vinho") saem — não distinguem nada;
--   · as palavras de CASA saem também (quinta, herdade, adega, monte…):
--     é o que faz "Crasto" (lido numa carta) encontrar "Quinta do Crasto"
--     (escrito numa garrafeira). São o ruído dos nomes portugueses;
--   · mas as palavras que QUALIFICAM o vinho ficam (reserva, grande,
--     velhas, garrafeira, superior, colheita): "Quinta do Crasto" e
--     "Quinta do Crasto Reserva" são vinhos diferentes, com preços
--     diferentes, e juntá-los era responder a uma pergunta com o outro;
--   · os tokens são ORDENADOS e sem repetições, e o produtor entra no
--     mesmo saco do nome: "Crasto Reserva" (só nome, vindo da carta) e
--     nome="Reserva" + produtor="Quinta do Crasto" (vindo da garrafeira)
--     têm de cair na mesma chave, e caem.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.tokens(p_texto text)
  RETURNS text[] LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  -- Duas voltas, e a ORDEM importa: primeiro expandem-se as abreviaturas,
  -- só DEPOIS se deitam fora as palavras que não distinguem nada. Ao
  -- contrário, "Qta. do Vallado" dava tokens {quinta,vallado} (o "qta" não
  -- está na lista das que saem, e já ia expandido quando ninguém olhava) e
  -- "Quinta do Vallado" dava {vallado} — a MESMA garrafa com duas chaves,
  -- que é exatamente a avaria que este catálogo não pode ter.
  SELECT COALESCE(array_agg(DISTINCT t ORDER BY t), ARRAY[]::text[])
  FROM (
    SELECT CASE w
             WHEN 'qta'  THEN 'quinta' WHEN 'qtas' THEN 'quintas'
             WHEN 'hrd'  THEN 'herdade'
             WHEN 'sto'  THEN 'santo'  WHEN 'sta'  THEN 'santa'
             ELSE w
           END AS t
    FROM regexp_split_to_table(
           regexp_replace(
             regexp_replace(
               -- NFD parte "é" em "e" + acento, e o intervalo apaga o acento.
               lower(regexp_replace(normalize(COALESCE(p_texto, ''), NFD),
                                    U&'[\0300-\036F]', '', 'g')),
               '\m(19|20)[0-9]{2}\M', ' ', 'g'    -- a colheita não entra no nome
             ),
             '[^a-z0-9]+', ' ', 'g'
           ), '\s+') AS w
    WHERE w <> ''
  ) x
  WHERE t <> ''
    -- vazias: não distinguem vinho nenhum
    AND t NOT IN ('de','do','da','dos','das','e','o','a','os','as','um','uma',
                  'vinho','vinhos','wine')
    -- de casa: é o ruído dos nomes portugueses, e é o que impede
    -- "Crasto" de encontrar "Quinta do Crasto"
    AND t NOT IN ('quinta','quintas','herdade','casa','adega','monte','vinha',
                  'vinhas','conde','dom','santo','santa','sociedade','agricola',
                  'soc','lda');
$$;

-- Nota sobre a COR: "tinto", "branco" e "rose" NÃO saem da chave, ao
-- contrário do que a primeira versão fazia. O Papa Figos branco não é o
-- Papa Figos tinto — castas diferentes, nota diferente, preço diferente —
-- e juntá-los era responder a uma pergunta com a outra. O preço disto é
-- que um vinho gravado na Garrafeira como nome="Papa Figos" + tipo=Branco
-- (a cor numa COLUNA, fora do nome) não encontra o "Papa Figos Branco"
-- lido numa carta: são chaves diferentes. É uma chamada à IA que se perde,
-- e perder uma chamada é sempre melhor do que devolver o vinho errado.

-- O PARÊNTESIS DO PRODUTOR NÃO ENTRA NA CHAVE. Quem escreve "Herdade dos
-- Grous (Monte do Trevo)" ou "Quinta do Vesúvio (Symington Family Estates)"
-- está a deixar uma NOTA a si próprio — a sociedade que o detém, a marca
-- do grupo — e não a dizer outro produtor. Deixá-la entrar dava
-- "grous-harvested-moon-trevo" a quem escreveu a nota e
-- "grous-harvested-moon" a quem não escreveu: o MESMO vinho em duas
-- linhas, cada uma a pagar a sua ida à IA. Tira-se só do PRODUTOR, nunca
-- do NOME: um "(Branco)" no nome é a cor, e a cor não sai da chave (ver a
-- nota acima).
CREATE OR REPLACE FUNCTION winecatalog.chave_base(p_nome text, p_produtor text)
  RETURNS text LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT array_to_string(
    winecatalog.tokens(
      COALESCE(p_nome,'') || ' ' ||
      regexp_replace(COALESCE(p_produtor,''), '\s*\([^)]*\)', ' ', 'g')
    ), '-');
$$;

CREATE OR REPLACE FUNCTION winecatalog.chave(p_nome text, p_produtor text, p_ano integer)
  RETURNS text LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT winecatalog.chave_base(p_nome, p_produtor) || '|' || COALESCE(p_ano::text, '');
$$;

-- ---------------------------------------------------------------------
-- ACHAR: as DUAS identidades de cada vinho, e porque é que são duas
--
-- O mesmo vinho chega aqui escrito de duas maneiras, e nenhuma está
-- errada:
--   · numa GARRAFEIRA está partido em campos — nome "Barca Velha",
--     produtor "Casa Ferreirinha";
--   · numa CARTA de restaurante está escrito de corrida — "Barca Velha",
--     e o produtor não aparece em lado nenhum.
-- Juntar o produtor ao nome para fazer a chave (que é o que é preciso
-- fazer, senão um vinho chamado "Reserva" casava com todos os outros
-- "Reserva" do mundo) dá "barca-ferreirinha-velha" de um lado e
-- "barca-velha" do outro: chaves diferentes, e o catálogo a nunca
-- responder a uma carta — que era metade da razão de ele existir.
--
-- Daí cada linha guardar as duas: `chave` (nome+produtor) e `chave_nome`
-- (só o nome). Uma pergunta calcula também as suas duas, e casa se
-- QUALQUER uma bater com QUALQUER uma das da linha. Não é contenção de
-- tokens (a `verificarCoerencia` da WineSelection faz isso, e ali está
-- certo): contenção juntava "Quinta do Crasto" com "Quinta do Crasto
-- Reserva", que são vinhos diferentes com preços diferentes — e num
-- catálogo isso não é um aviso a mais, é a nota errada dada como certa.
--
-- A trave de segurança: um nome que sozinho não distinga nada NÃO ganha
-- `chave_nome` (fica NULL). "Reserva", "Tinto", "Grande Reserva" — se
-- depois de tirar as palavras de casa só sobram qualificadores, o nome
-- por si não é identidade nenhuma, e deixá-lo casar dava o "Reserva" de
-- um produtor a responder pelo "Reserva" de outro.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.base_nome(p_nome text)
  RETURNS text LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE
    WHEN EXISTS (
      SELECT 1 FROM unnest(winecatalog.tokens(p_nome)) t
       WHERE t NOT IN ('reserva','grande','garrafeira','colheita','selecionada',
                       'seleccionada','velhas','superior','especial','premium',
                       'tinto','branco','rose','doce','seco','bruto','meio',
                       'unoaked','barrica','madeira','antiga','velho','novo')
    )
    THEN array_to_string(winecatalog.tokens(p_nome), '-')
    ELSE NULL      -- só qualificadores: não é identidade nenhuma
  END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.chave_nome(p_nome text, p_ano integer)
  RETURNS text LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT winecatalog.base_nome(p_nome) || '|' || COALESCE(p_ano::text, '');
$$;

-- Devolve o id da linha deste vinho, ou NULL. `p_exigir_ano`:
--   true  -> só a colheita pedida (é o que `juntar` precisa: escrever no
--            ano errado era estragar duas linhas de uma vez);
--   false -> qualquer colheita do mesmo vinho, a mais preenchida primeiro
--            (é o que `procurar` precisa quando o ano pedido não existe).
-- `p_excluir` deixa de fora uma linha: é como o `procurar` vai buscar a
-- colheita IRMÃ sem voltar a apanhar a que já tem na mão.
DROP FUNCTION IF EXISTS winecatalog.achar(text, text, integer, boolean);
CREATE OR REPLACE FUNCTION winecatalog.achar(
  p_nome text, p_produtor text, p_ano integer, p_exigir_ano boolean DEFAULT true,
  p_excluir bigint DEFAULT NULL
) RETURNS bigint
  LANGUAGE sql STABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  -- O LEFT JOIN à `alias` é o que faz uma fusão valer para sempre.
  --
  -- Quando alguém decide na WineCatalog que duas linhas são o mesmo
  -- vinho, a perdedora fica onde está, com as chaves que tinha — o que
  -- muda é ESTA função: se a pergunta esbarrar nela, responde-se com a
  -- linha-alvo. É o desenho que o documento de arranque pedia ("o `achar`
  -- resolve por ele"), e não uma preferência de estilo.
  --
  -- A primeira versão não podia mexer aqui (o ficheiro era de outro repo)
  -- e resolvia-o a estacionar as chaves da perdedora com um prefixo. Isso
  -- tirava-a do caminho, sim — mas tirava-a DEMAIS: a grafia antiga
  -- deixava de casar com fosse o que fosse, e a próxima carta que
  -- escrevesse "Grous Moon Harvest" outra vez não achava a perdedora (com
  -- a chave mexida) nem a alvo (que tem outra), e nascia uma TERCEIRA
  -- linha. Ou seja: o duplicado voltava, e voltava por causa da própria
  -- ferramenta que servia para o resolver.
  --
  -- `p_excluir` continua a ser sobre a linha CRUA (é a colheita irmã do
  -- `procurar`, que precisa de saltar a linha que já tem na mão), por isso
  -- compara-se com `v.id` e não com o id já resolvido.
  --
  -- AS CHAVES DA PERGUNTA CALCULAM-SE UMA VEZ, na CTE `q`, e não dentro do
  -- WHERE. Lá dentro, com parâmetros em vez de constantes, o Postgres
  -- chamava a `tokens()` (NFD + três regex) para CADA linha do catálogo,
  -- várias vezes por linha: ~1 s por vinho com 180 linhas. Uma carta de
  -- 11 vinhos pelo `procurar_lote` dava 10 s, o `statement_timeout` de 8 s
  -- do PostgREST cortava-a com 500, e a WineSelection dizia "não conheço
  -- nenhum" de uma carta cujos vinhos tinham acabado de ser pesquisados e
  -- pagos (24/09/2026). O que a chave QUER DIZER não mudou — só quantas
  -- vezes se calcula.
  WITH q AS MATERIALIZED (
    SELECT winecatalog.chave(p_nome, p_produtor, p_ano)  AS k,
           winecatalog.chave_nome(p_nome, p_ano)         AS kn,
           winecatalog.chave_base(p_nome, p_produtor)    AS b,
           winecatalog.base_nome(p_nome)                 AS bn
  )
  SELECT COALESCE(a.id_para, v.id)
    FROM q, winecatalog.vinhos v
    LEFT JOIN winecatalog.alias a ON a.id_de = v.id
   WHERE (p_excluir IS NULL OR v.id <> p_excluir)
     AND CASE WHEN p_exigir_ano THEN
           -- as quatro combinações das duas chaves de cada lado
           v.chave = q.k
           OR (q.kn IS NOT NULL AND v.chave = q.kn)
           OR (v.chave_nome IS NOT NULL AND v.chave_nome IN (q.k, q.kn))
         ELSE
           v.chave_base = q.b
           OR (q.bn IS NOT NULL AND v.chave_base = q.bn)
           OR (v.base_nome IS NOT NULL AND v.base_nome IN (q.b, q.bn))
         END
   -- Uma linha que já foi fundida noutra vai para o fim: se a alvo também
   -- casou, é ela que responde por si, e não pelo desvio.
   ORDER BY (a.id_para IS NOT NULL),
            (SELECT count(*) FROM jsonb_object_keys(v.ficha)) DESC,
            v.ano DESC NULLS LAST
   LIMIT 1;
$$;

-- ---------------------------------------------------------------------
-- Campos VOLÁTEIS: os que envelhecem
--
-- As castas de um vinho não mudam; a nota do Vivino e o preço de mercado
-- mudam. Quem lê o catálogo trata um campo volátil com mais de N dias como
-- se não estivesse lá (e vai à IA buscá-lo); os outros não expiram nunca —
-- pagar outra vez para saber que o Barca Velha é do Douro é dinheiro
-- deitado fora.
--
-- São também os campos que NÃO se aproveitam de outra colheita: ver
-- `winecatalog.procurar`.
--
-- Repara no que NÃO está aqui nem em lado nenhum do catálogo: o
-- "barato/justo/caro" da WineSelection. Esse não é volátil — é de OUTRA
-- COISA: é um juízo sobre o preço de UMA CARTA, não sobre o vinho. O mesmo
-- Papa Figos é barato a 22 € e caro a 45 €, e nem o vinho mudou nem
-- envelheceu nada. O que é do vinho, e entra, é o `preco_medio` (o preço
-- de mercado); a comparação com a carta que está à frente refaz-se sempre,
-- em código, na `verificar-vinhos`.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.volatil(p_campo text)
  RETURNS boolean LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT COALESCE(p_campo, '') IN (
    'vivino_nota', 'vivino_avaliacoes', 'vivino_url',
    'preco_medio', 'imagem_url'
  );
$$;

-- ---------------------------------------------------------------------
-- A REGIÃO, normalizada — "DOURO" e "Douro" não podem responder por
-- facetas diferentes no Catálogo, e "Península de Setúbal" é a mesma
-- região que "Setúbal", só escrita como uma carta a escreveria.
--
-- Duas regras, e só duas:
--   1. "Setúbal" ganha a qualquer grafia da Península — é a mesma região,
--      o nome mais curto é o que fica;
--   2. um valor todo em CAPS LOCK ou todo em minúsculas passa a Title
--      Case. Não se toca em mais nada: "Beira Interior" e
--      "Trás-os-Montes" já estão certos, e um `initcap()` ingénuo
--      estragava o hífen e as preposições.
--
-- Chamada em CADA sítio por onde uma região pode entrar no catálogo —
-- `juntar` (garrafeira/pesquisa) e `editar`/`criar` (admin, em
-- curadoria.sql) — para a mesma inconsistência não voltar a entrar por
-- outra porta.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.normalizar_regiao(p_regiao text)
  RETURNS text LANGUAGE plpgsql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v      text := btrim(regexp_replace(COALESCE(p_regiao, ''), '\s+', ' ', 'g'));
  v_low  text;
  small  text[] := ARRAY['de','da','do','das','dos','e'];
  words  text[];
  out_arr text[] := '{}';
  i      integer;
BEGIN
  IF v = '' THEN RETURN NULL; END IF;
  v_low := lower(v);

  IF v_low IN ('setúbal', 'setubal', 'península de setúbal',
               'peninsula de setubal', 'peninsula de setúbal',
               'península de setubal') THEN
    RETURN 'Setúbal';
  END IF;

  -- Só se mexe quando o valor é TUDO maiúsculas ou TUDO minúsculas — um
  -- valor já com mistura das duas ("Beira Interior", "Trás-os-Montes")
  -- está certo, e um `initcap()` ingénuo é que lhe estragava o hífen e as
  -- preposições.
  IF v <> upper(v) AND v <> lower(v) THEN
    RETURN v;
  END IF;

  words := regexp_split_to_array(v_low, ' ');
  FOR i IN 1..array_length(words, 1) LOOP
    IF i > 1 AND words[i] = ANY(small) THEN
      out_arr := out_arr || words[i];
    ELSE
      out_arr := out_arr || (upper(substring(words[i] FROM 1 FOR 1)) || substring(words[i] FROM 2));
    END IF;
  END LOOP;

  RETURN array_to_string(out_arr, ' ');
END;
$$;

-- ---------------------------------------------------------------------
-- A FORÇA de cada origem: quem é que ganha quando duas leituras discordam
--
-- Não é uma opinião sobre quem é mais inteligente — é sobre o que cada uma
-- teve à frente quando respondeu:
--   3  alguém tem a garrafa em casa e confirmou a ficha campo a campo
--      (a Garrafeira nunca grava uma leitura da IA sem um clique);
--   4  o ADMIN DO CATÁLOGO a corrigir um campo à mão, no ecrã desta app.
--      É o único 4 que existe, e existe para o botão "Editar" não ser uma
--      mentira: a 3 empatava com a garrafeira, e como a `juntar` escreve
--      com `>=`, a escrita seguinte de qualquer garrafeira desfazia a
--      correção em silêncio. Quem corrige um campo aqui está a corrigir
--      um erro que as três apps estão a ver;
--   3  a `verificar-vinhos` — pesquisa Google a sério, pedida à mão para
--      um vinho escolhido, que é o mais caro que aqui se paga;
--   3  a `catalogo-info` — a mesma coisa pedida do ecrã do catálogo:
--      pesquisa Google com grounding, um vinho de cada vez, a pedido. É o
--      mesmo trabalho e o mesmo custo, por isso é a mesma força;
--   2  as pesquisas normais das duas apps (grounding search, ou pesquisa
--      externa + extração);
--   1  um vinho escrito à mão numa garrafeira que ninguém preencheu — vale
--      para encher um campo vazio, nunca para tapar uma pesquisa;
--   0  tudo o resto — E É AQUI QUE ESTÁ O PONTO: a `pontuacaoAprox` da
--      WineSelection (a estimativa de memória do modelo, sem pesquisa
--      nenhuma) tem de dar 0 e NUNCA pode entrar no catálogo. Toda a
--      WineSelection está construída à volta de não disfarçar uma
--      estimativa de verificação; deixá-la entrar aqui era pior do que
--      isso — era espalhá-la pelas duas apps com ar de facto pesquisado,
--      e depois já ninguém sabia de onde tinha vindo.
-- ---------------------------------------------------------------------
-- A FORÇA É DA ORIGEM **E DO CAMPO**, e a segunda metade não é um
-- pormenor: é o que impede o catálogo de tomar por facto tudo o que
-- alguém escreveu à mão.
--
-- Quem tem a garrafa em casa sabe melhor do que qualquer pesquisa o que
-- está no RÓTULO: as castas, a cor, o teor, a região, a menção. Isso vale
-- 3, e é a razão de a Garrafeira estar lá em cima.
--
-- Mas ninguém sabe a nota do Vivino nem o preço de mercado por ter a
-- garrafa na mão — esses lêem-se num site, e quem os escreve na sua
-- garrafeira está a copiar (ou a lembrar-se, ou a enganar-se). A dar-lhes
-- a mesma força de uma pesquisa a sério, um número escrito à pressa
-- tapava a `verificar-vinhos` para toda a gente e para sempre; e como
-- estes campos entram no catálogo por uma app onde CADA UM ESCREVE O QUE
-- QUISER na sua garrafeira, isto não é uma hipótese remota, é o caminho
-- normal. Por isso um campo volátil vindo de uma garrafeira vale 2: chega
-- para encher um campo vazio e para se manter enquanto ninguém pesquisou,
-- e perde para a pesquisa a sério no dia em que ela existir.
--
-- Repara que a distinção é a MESMA de `winecatalog.volatil`, e é a mesma
-- ideia por dois lados: o que envelhece é também o que não se sabe por
-- ter a garrafa à frente.
--
-- E VALE PARA O ADMIN TAMBÉM, pela mesma razão e não por simetria bonita:
-- ser dono do catálogo não faz ninguém saber a nota do Vivino nem o preço
-- de mercado — esses também os foi ler a algum lado. Por isso a correção
-- do admin vale 4 no que está no RÓTULO (aí é a última palavra e ninguém
-- lhe passa por cima) e 3 na nota, no preço e na imagem: uma pesquisa a
-- sério fresca ainda os pode actualizar, e uma cópia de garrafeira nunca.
-- A alternativa — 4 em tudo — congelava para sempre um preço que por
-- definição envelhece, e punha as três apps a pagar pesquisas cujo
-- resultado era deitado fora à chegada.
DROP FUNCTION IF EXISTS winecatalog.forca(text);
CREATE OR REPLACE FUNCTION winecatalog.forca(p_origem text, p_campo text DEFAULT NULL)
  RETURNS integer LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE
    -- Ver o comentário grande acima: a força é da ORIGEM **e do CAMPO**, e
    -- as duas excepções aqui são a mesma ideia aplicada a duas pessoas
    -- diferentes.
    WHEN COALESCE(p_origem,'') = 'garrafeira'     AND winecatalog.volatil(p_campo) THEN 2
    WHEN COALESCE(p_origem,'') = 'catalogo-admin' AND winecatalog.volatil(p_campo) THEN 3
    ELSE CASE COALESCE(p_origem, '')
      WHEN 'catalogo-admin'      THEN 4
      WHEN 'garrafeira'          THEN 3
      WHEN 'ws-verificacao'      THEN 3
      WHEN 'catalogo-pesquisa'   THEN 3
      WHEN 'vinho-info-premium'  THEN 2
      WHEN 'vinho-info-gratis'   THEN 2
      WHEN 'ws-sugestao'         THEN 2
      WHEN 'garrafeira-bruto'    THEN 1
      ELSE 0
    END
  END;
$$;

-- ---------------------------------------------------------------------
-- JUNTAR: escrever no catálogo sem apagar o que já lá estava
--
-- Campo a campo: entra se o campo estava vazio, ou se quem escreve agora
-- vem de uma origem tão forte ou mais forte do que a que lá pôs o valor.
-- O que vem vazio ('', null, [], {}) nunca entra — "não sei" não é uma
-- resposta que valha a pena guardar, e a apagar uma que valia era o pior
-- que esta função podia fazer.
--
-- SECURITY DEFINER porque quem a chama do lado do browser é o trigger da
-- Garrafeira, em nome de uma pessoa que não tem (nem deve ter) direito de
-- escrita nesta tabela.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.juntar(
  p_nome text, p_produtor text, p_ano integer,
  p_ficha jsonb, p_origem text, p_fontes jsonb DEFAULT '[]'::jsonb
) RETURNS bigint
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  -- A da ORIGEM, só para a guarda de entrada: a que decide campo a
  -- campo calcula-se DENTRO do ciclo, que a força é da origem E do campo.
  v_forca   integer := winecatalog.forca(p_origem);
  v_fcampo  integer;
  v_chave   text    := winecatalog.chave(p_nome, p_produtor, p_ano);
  v_base    text    := winecatalog.chave_base(p_nome, p_produtor);
  v_cnome   text    := winecatalog.chave_nome(p_nome, p_ano);
  v_bnome   text    := winecatalog.base_nome(p_nome);
  v_id      bigint;
  v_ficha   jsonb;
  v_origens jsonb;
  v_fontes  jsonb;
  v_mexeu   boolean := false;
  k         text;
  v         jsonb;
  v_ant     integer;
BEGIN
  -- Sem força não entra (ver `winecatalog.forca`), e sem tokens não há
  -- identidade nenhuma: um nome que se reduza a "quinta" não é um vinho,
  -- é uma palavra, e casaria com tudo.
  IF v_forca <= 0 OR v_base = '' OR p_ficha IS NULL OR jsonb_typeof(p_ficha) <> 'object' THEN
    RETURN NULL;
  END IF;

  -- A linha deste vinho pode já existir escrita da OUTRA maneira (com ou
  -- sem produtor) — ver `winecatalog.achar`. Sem isto, cada app criava a sua
  -- linha do mesmo vinho e nenhuma via a da outra: um catálogo partilhado
  -- que não partilhava nada.
  v_id := winecatalog.achar(p_nome, COALESCE(p_produtor,''), p_ano, true);

  IF v_id IS NULL THEN
    INSERT INTO winecatalog.vinhos (chave, chave_base, chave_nome, base_nome, nome, produtor, ano)
    VALUES (v_chave, v_base, v_cnome, v_bnome,
            COALESCE(p_nome,''), COALESCE(p_produtor,''), p_ano)
    ON CONFLICT (chave) DO NOTHING;
    -- Duas escritas ao mesmo tempo: quem perdeu o INSERT vai buscar a
    -- linha de quem ganhou em vez de desistir.
    SELECT v.id INTO v_id FROM winecatalog.vinhos v WHERE v.chave = v_chave;
  END IF;
  IF v_id IS NULL THEN RETURN NULL; END IF;

  SELECT v.ficha, v.origens, v.fontes
    INTO v_ficha, v_origens, v_fontes
    FROM winecatalog.vinhos v WHERE v.id = v_id FOR UPDATE;

  FOR k, v IN SELECT key, value FROM jsonb_each(p_ficha) LOOP
    CONTINUE WHEN v IS NULL
                  OR jsonb_typeof(v) = 'null'
                  OR v = '""'::jsonb OR v = '[]'::jsonb OR v = '{}'::jsonb;
    -- "DOURO" e "Península de Setúbal" não podem responder por facetas
    -- diferentes de "Douro"/"Setúbal" — ver `winecatalog.normalizar_regiao`.
    IF k = 'regiao' AND jsonb_typeof(v) = 'string' THEN
      v := to_jsonb(winecatalog.normalizar_regiao(v #>> '{}'));
      CONTINUE WHEN v IS NULL;
    END IF;
    v_fcampo := winecatalog.forca(p_origem, k);
    v_ant    := COALESCE((v_origens -> k ->> 'f')::integer, 0);
    IF v_fcampo >= v_ant THEN
      v_ficha   := v_ficha   || jsonb_build_object(k, v);
      v_origens := v_origens || jsonb_build_object(
        k, jsonb_build_object('o', p_origem, 'f', v_fcampo, 'em', now())
      );
      v_mexeu := true;
    END IF;
  END LOOP;

  -- As fontes acumulam-se, sem repetir o mesmo URL, e ficam pelas 8 —
  -- são para se poder ir ver de onde veio isto, não um arquivo.
  IF p_fontes IS NOT NULL AND jsonb_typeof(p_fontes) = 'array' THEN
    SELECT COALESCE(jsonb_agg(f), '[]'::jsonb) INTO v_fontes FROM (
      SELECT DISTINCT ON (f ->> 'url') f
        FROM jsonb_array_elements(v_fontes || p_fontes) f
       WHERE COALESCE(f ->> 'url', '') <> ''
       ORDER BY (f ->> 'url')
       LIMIT 8
    ) x;
  END IF;

  UPDATE winecatalog.vinhos SET
    ficha    = v_ficha,
    origens  = v_origens,
    fontes   = v_fontes,
    -- O nome mais COMPRIDO fica: entre "Crasto" (lido de uma carta ao
    -- lume de vela) e "Quinta do Crasto Reserva", quem abrir o catálogo
    -- para perceber uma linha quer ver o segundo.
    nome     = CASE WHEN length(COALESCE(p_nome,'')) > length(nome) THEN p_nome ELSE nome END,
    produtor = CASE WHEN produtor = '' THEN COALESCE(p_produtor,'') ELSE produtor END,
    ano      = COALESCE(ano, p_ano),
    -- Uma linha nascida de uma carta não tem produtor, e uma nascida de uma
    -- garrafeira não tem a chave curta. Cada escrita acrescenta a que
    -- faltar — é o que faz as duas apps convergirem na mesma linha em vez
    -- de se encontrarem por acaso.
    chave_nome = COALESCE(chave_nome, v_cnome),
    base_nome  = COALESCE(base_nome,  v_bnome),
    vezes    = vezes + 1,
    atualizado_em = CASE WHEN v_mexeu THEN now() ELSE atualizado_em END
  WHERE id = v_id;

  RETURN v_id;
END;
$$;

-- ---------------------------------------------------------------------
-- PROCURAR: o que é que já se sabe deste vinho
--
-- Devolve um objeto (ou NULL). Primeiro a colheita exata; se não houver,
-- outra colheita do mesmo vinho.
--
-- E é aqui que estão as DUAS perguntas diferentes que parecem uma só:
--
--   · "quero o Papa Figos de 2019" e o catálogo só tem o de 2021 — então
--     os factos estáveis servem (as castas de um Papa Figos são as mesmas
--     nos dois anos) mas a NOTA e o PREÇO não: esses são da colheita, e
--     dar a nota de 2021 a quem perguntou por 2019 era inventar uma;
--
--   · "quero o Papa Figos" e mais nada — que é como as cartas de
--     restaurante vêm, e a WineSelection lê cartas. Aqui não há colheita
--     errada nenhuma: quem pergunta não tem ano, e a nota de uma colheita
--     recente é a melhor resposta que existe (é também a única que a
--     alternativa — a estimativa de memória do modelo — daria, e essa nem
--     sequer olha para nada). Fica tudo, e devolve-se o `ano` para quem
--     mostra poder dizer de que colheita é a nota.
--
-- A primeira versão tratava as duas da mesma maneira e cortava a nota nas
-- duas: o resultado era um catálogo que nunca respondia a uma carta.
--
-- `p_idade_dias` corta os campos voláteis velhos (ver `winecatalog.volatil`):
-- vêm de fora como se não estivessem lá, e quem perguntou vai à IA só por
-- esses.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.procurar(
  p_nome text, p_produtor text, p_ano integer, p_idade_dias integer DEFAULT 30
) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_id    bigint;
  r       winecatalog.vinhos%ROWTYPE;
  r2      winecatalog.vinhos%ROWTYPE;   -- a colheita irmã, quando é precisa
  v_irmao bigint;
  v_exato boolean := true;
  v_outra boolean;            -- pediram uma colheita E esta não é essa
  v_corte timestamptz := now() - make_interval(days => GREATEST(COALESCE(p_idade_dias, 30), 0));
  v_ficha jsonb;
  v_orig  jsonb;
  v_empr  jsonb := '[]'::jsonb;      -- campos vindos de outra colheita
  k       text;
BEGIN
  IF winecatalog.chave_base(p_nome, p_produtor) = '' THEN RETURN NULL; END IF;

  v_id := winecatalog.achar(p_nome, COALESCE(p_produtor,''), p_ano, true);
  IF v_id IS NULL THEN
    -- Sem a colheita pedida, serve outra do mesmo vinho — a mais
    -- preenchida, e em empate a mais recente. O que ela pode ou não pode
    -- responder decide-se a seguir, no `v_outra`.
    v_exato := false;
    v_id := winecatalog.achar(p_nome, COALESCE(p_produtor,''), p_ano, false);
  END IF;
  IF v_id IS NULL THEN RETURN NULL; END IF;

  SELECT * INTO r FROM winecatalog.vinhos v WHERE v.id = v_id;
  IF r.id IS NULL THEN RETURN NULL; END IF;

  v_outra := p_ano IS NOT NULL AND r.ano IS DISTINCT FROM p_ano;

  v_ficha := r.ficha;
  v_orig  := r.origens;
  FOR k IN SELECT key FROM jsonb_each(r.ficha) LOOP
    IF winecatalog.volatil(k)
       AND (v_outra
            OR COALESCE((r.origens -> k ->> 'em')::timestamptz, r.criado_em) < v_corte) THEN
      v_ficha := v_ficha - k;
    END IF;
  END LOOP;

  -- A COLHEITA CERTA NÃO PODE TAPAR O QUE A IRMÃ SABE.
  --
  -- Achar a linha do ano pedido e ficar por aí parece o mais óbvio, e é o
  -- que estava — mas uma linha do ano certo pode ser um espelho vazio (o
  -- vinho que alguém acabou de escrever na sua garrafeira, sem mais nada)
  -- enquanto a de 2022 tem dezassete campos. O que se via era o catálogo
  -- a responder "não sei" com a resposta ao lado, e a IA a ser paga na
  -- mesma. Foi o que aconteceu ao Grous Moon Harvested.
  --
  -- Por isso: o que a linha CERTA sabe manda sempre, e só o que lhe FALTA
  -- se vai pedir emprestado à irmã — e apenas os campos ESTÁVEIS. As
  -- castas de um Papa Figos são as mesmas em 2019 e em 2021; a nota do
  -- Vivino e o preço não são, e esses nunca atravessam colheitas (é a
  -- mesma regra do `v_outra` aqui em cima, e não pode ter duas versões).
  IF v_exato THEN
    v_irmao := winecatalog.achar(p_nome, COALESCE(p_produtor,''), p_ano, false, r.id);
    IF v_irmao IS NOT NULL THEN
      SELECT * INTO r2 FROM winecatalog.vinhos v WHERE v.id = v_irmao;
      FOR k IN SELECT key FROM jsonb_each(r2.ficha) LOOP
        IF NOT winecatalog.volatil(k) AND NOT (v_ficha ? k) THEN
          v_ficha := v_ficha || jsonb_build_object(k, r2.ficha -> k);
          v_orig  := v_orig  || jsonb_build_object(k, COALESCE(r2.origens -> k, '{}'::jsonb));
          v_empr  := v_empr  || to_jsonb(k);
        END IF;
      END LOOP;
    END IF;
  END IF;

  UPDATE winecatalog.vinhos v SET visto_em = now() WHERE v.id = r.id;

  RETURN jsonb_build_object(
    'chave',    r.chave,
    'nome',     r.nome,
    'produtor', r.produtor,
    'ano',      r.ano,
    'ficha',    v_ficha,
    'origens',  v_orig,
    'fontes',   r.fontes,
    'exato',    v_exato,
    -- os campos estáveis que vieram de outra colheita (só para diagnóstico)
    'emprestados', v_empr,
    -- true: é a colheita pedida · false: é OUTRA · null: não se pediu ano
    'mesmoAno', CASE WHEN p_ano IS NULL THEN NULL ELSE NOT v_outra END,
    'atualizadoEm', r.atualizado_em
  );
END;
$$;

-- Em lote, na MESMA ordem do pedido e com `null` onde não se sabe nada.
-- A WineSelection pergunta por uma carta inteira de uma vez (quarenta
-- vinhos): quarenta idas ao PostgREST por causa disso era trocar uma
-- chamada cara ao Gemini por quarenta baratas, e essa troca faz-se uma vez
-- só. `p_pedidos` é [{nome, produtor, ano}].
CREATE OR REPLACE FUNCTION winecatalog.procurar_lote(
  p_pedidos jsonb, p_idade_dias integer DEFAULT 30
) RETURNS jsonb
  LANGUAGE sql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT COALESCE(jsonb_agg(
           winecatalog.procurar(
             p ->> 'nome', COALESCE(p ->> 'produtor', ''),
             CASE WHEN jsonb_typeof(p -> 'ano') = 'number' THEN (p ->> 'ano')::integer END,
             p_idade_dias
           ) ORDER BY i
         ), '[]'::jsonb)
    FROM jsonb_array_elements(
           CASE WHEN jsonb_typeof(p_pedidos) = 'array' THEN p_pedidos ELSE '[]'::jsonb END
         ) WITH ORDINALITY AS t(p, i);
$$;


-- =====================================================================
-- QUEM MANDA, E QUEM PODE LER
--
-- O catálogo não herda o admin da Garrafeira nem o da WineSelection. Era
-- esse o problema de governo que a app nova veio resolver: pôr este painel
-- dentro da Garrafeira significava que quem a herdasse (o admin dela passa
-- com `definir_admin()`) herdava poder sobre uma tabela que também serve a
-- WineSelection.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.admin_email()
  RETURNS text LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT COALESCE(
    (SELECT lower(valor) FROM winecatalog.config WHERE chave = 'admin_email'),
    'diogo.andre.f.silva@gmail.com'
  );
$$;

CREATE OR REPLACE FUNCTION winecatalog.sou_admin()
  RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT lower(COALESCE(auth.email(), '')) = winecatalog.admin_email();
$$;

-- Quem pode LER o catálogo: o admin, e quem estiver aprovado na app.
-- Numa função só, para que mudar de ideias sobre quem lê seja mudar uma
-- linha e não catorze.
CREATE OR REPLACE FUNCTION winecatalog.pode_ler()
  RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT winecatalog.sou_admin() OR EXISTS (
    SELECT 1 FROM winecatalog.allowed_users
     WHERE lower(email) = lower(COALESCE(auth.email(), ''))
  );
$$;

-- Passar o catálogo a outra pessoa. Só o admin, e só para um email que já
-- tenha acesso à app — passá-lo a quem não está em `allowed_users` é ficar
-- sem admin nenhum e sem forma de voltar atrás pela UI.
CREATE OR REPLACE FUNCTION winecatalog.definir_admin(p_email text)
  RETURNS text LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_novo text := lower(trim(COALESCE(p_email, '')));
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin pode passar o catálogo a outra pessoa.';
  END IF;
  IF v_novo = '' OR v_novo NOT LIKE '%@%' THEN
    RAISE EXCEPTION 'Email inválido.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM winecatalog.allowed_users WHERE lower(email) = v_novo) THEN
    RAISE EXCEPTION 'Esse email ainda não tem acesso à app — aprova-o primeiro em Utilizadores.';
  END IF;
  INSERT INTO winecatalog.config (chave, valor) VALUES ('admin_email', v_novo)
  ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor;
  RETURN 'ok';
END;
$$;
-- =====================================================================
-- 2. UM CAMINHO DE LEITURA PARA A UI
--
-- Até aqui `winecatalog.vinhos` tinha RLS com ZERO policies: nem o
-- `authenticated` lia uma linha, e não havia um único ecrã em lado nenhum
-- que mostrasse o que lá está. Só as Edge Functions (service_role) lhe
-- chegavam.
--
-- Duas saídas, e a escolhida é a segunda:
--   · policies de SELECT — mais simples, mas abre a tabela a QUALQUER
--     pessoa com login em QUALQUER app do projeto que aponte para o
--     schema `winecatalog`, e o schema está EXPOSTO na API. A lista de
--     vinhos que passaram por aqui diz alguma coisa sobre o que as
--     pessoas têm em casa, mesmo que cada linha à parte não diga;
--   · funções SECURITY DEFINER com `REVOKE` e `GRANT` só a quem deve —
--     a mesma razão que levou ao REVOKE da `juntar`/`procurar`/
--     `procurar_lote`, e a mesma disciplina.
--
-- Cada função nova nasce com EXECUTE para PUBLIC. Os REVOKEs estão todos
-- juntos no FIM deste ficheiro, e confirmam-se com a consulta que está lá.
-- =====================================================================

-- ---------------------------------------------------------------------
-- O preço como número, ou NULL. A ficha é jsonb e um dia tem lá "34,90"
-- escrito à mão: um cast directo rebentava a lista inteira por causa de
-- uma linha.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.preco_num(f jsonb)
  RETURNS numeric LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE WHEN jsonb_typeof(f -> 'preco_medio') = 'number'
              THEN (f ->> 'preco_medio')::numeric END;
$$;

-- As faixas de preço vivem AQUI e não no browser: são o que a `listar`
-- conta e o que ela filtra, e duas listas destas divergem no dia em que
-- alguém mexe numa só.
CREATE OR REPLACE FUNCTION winecatalog.faixa_preco(p numeric)
  RETURNS text LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE
           WHEN p IS NULL THEN NULL
           WHEN p <  15 THEN '<15'
           WHEN p <  30 THEN '15-30'
           WHEN p <  60 THEN '30-60'
           ELSE '60+'
         END;
$$;

-- Uma linha do catálogo como a UI a quer numa LISTA: sem a ficha inteira
-- (são ~19 campos por linha e a lista tem centenas), mas com o que
-- responde à pergunta "vale a pena abrir esta?".
CREATE OR REPLACE FUNCTION winecatalog.resumo_linha(r winecatalog.vinhos)
  RETURNS jsonb LANGUAGE sql STABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT jsonb_build_object(
    'id',       r.id,
    'chave',    r.chave,
    'nome',     r.nome,
    'produtor', r.produtor,
    'ano',      r.ano,
    'tipo',     r.ficha ->> 'tipo',
    'regiao',   COALESCE(r.ficha ->> 'regiao', r.ficha ->> 'pais'),
    'castas',   r.ficha -> 'castas',
    'nota',     r.ficha -> 'vivino_nota',
    'preco',    r.ficha -> 'preco_medio',
    -- A fotografia do vinho (a do RÓTULO, que é do vinho — nunca a
    -- `imagem_path` tirada em casa, que apanha a prateleira à volta e é
    -- de quem a tem). A lista desenha a garrafa quando isto vem vazio,
    -- por isso é seguro estar em falta — o que não pode é obrigar o ecrã
    -- a abrir a ficha inteira só para saber se existe.
    'imagem',   r.ficha ->> 'imagem_url',
    'campos',   (SELECT count(*) FROM jsonb_object_keys(r.ficha)),
    -- A força MÁXIMA que esta linha tem em cima: é o que distingue um
    -- vinho que alguém pesquisou a sério de um que foi escrito à pressa
    -- numa garrafeira e nunca mais ninguém tocou.
    'forca',    (SELECT COALESCE(max((o.value ->> 'f')::integer), 0)
                   FROM jsonb_each(r.origens) o),
    'fontes',   jsonb_array_length(COALESCE(r.fontes, '[]'::jsonb)),
    'vezes',    r.vezes,
    'vistoEm',      r.visto_em,
    'atualizadoEm', r.atualizado_em
  );
$$;

-- A LISTA, com procura e FILTROS. `p_procura` vazio e sem filtro nenhum
-- devolve tudo (por ordem da última vez que serviu uma pergunta — que é a
-- ordem por que alguém quer ver isto, não a alfabética).
--
-- A procura bate em quatro sítios porque é por esses quatro que se procura
-- um vinho: o nome, o produtor, a região e a casta. Os dois primeiros
-- passam também pela CHAVE (`winecatalog.tokens`), e é isso que faz "qta do
-- crasto" encontrar a linha escrita "Quinta do Crasto" e "crasto"
-- encontrar as duas — a mesma normalização que o catálogo já usa para
-- decidir o que é o mesmo vinho, sem uma segunda ideia sobre acentos.
--
-- Os quatro filtros (tipo, região, castas, faixa de preço) são do SQL e
-- não do browser porque a lista é PAGINADA (50 de cada vez): filtrar do
-- lado do cliente filtrava só a página que por acaso já tinha vindo —
-- "3 tintos do Douro" quando havia trinta.
--
-- E as CONTAGENS por opção (`facetas`) voltam no mesmo pedido, contadas
-- com os OUTROS grupos aplicados mas não o próprio: é o que faz
-- "Branco 7" continuar visível depois de se escolher Tinto. Um grupo que
-- só conta o que já está filtrado por ele mesmo mostra sempre o total
-- escolhido, e não serve para nada.
--
-- As CASTAS, e só elas, aceitam as duas leituras: escolher Touriga
-- Nacional e Syrah pode ser "qualquer uma das duas" (`p_castas_todas`
-- false, o costume) ou "os lotes que levam as duas" (true). Um vinho tem
-- UM tipo e UMA região — ali a pergunta não se põe, e é por isso que o
-- visto no ecrã só aparece nas castas.
--
-- A assinatura mudou (quatro parâmetros novos, e depois o quinto), por
-- isso as antigas têm de sair — senão ficavam todas e o PostgREST
-- escolhia a que lhe desse jeito.
DROP FUNCTION IF EXISTS winecatalog.listar(text, integer, integer);
DROP FUNCTION IF EXISTS winecatalog.listar(text, integer, integer,
                                           text[], text[], text[], text[]);

CREATE OR REPLACE FUNCTION winecatalog.listar(
  p_procura text    DEFAULT NULL,
  p_limite  integer DEFAULT 50,
  p_saltar  integer DEFAULT 0,
  p_tipos   text[]  DEFAULT NULL,
  p_regioes text[]  DEFAULT NULL,
  p_castas  text[]  DEFAULT NULL,
  p_precos  text[]  DEFAULT NULL,  -- ids das faixas: '<15','15-30','30-60','60+'
  p_castas_todas boolean DEFAULT false
) RETURNS jsonb
  LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_q    text    := lower(trim(COALESCE(p_procura, '')));
  v_toks text[]  := CASE WHEN v_q = '' THEN ARRAY[]::text[] ELSE winecatalog.tokens(v_q) END;
  v_lim  integer := LEAST(GREATEST(COALESCE(p_limite, 50), 1), 200);
  v_off  integer := GREATEST(COALESCE(p_saltar, 0), 0);
  v_e    boolean := COALESCE(p_castas_todas, false);
  v_res  jsonb;
BEGIN
  IF NOT winecatalog.pode_ler() THEN
    RAISE EXCEPTION 'Sem acesso ao catálogo.';
  END IF;

  -- Uma CTE e não uma tabela temporária: uma função STABLE não pode
  -- escrever, nem sequer num `CREATE TEMP TABLE`, e o Postgres só o diz
  -- quando a função CORRE. É a mesma pedra em que já se tropeçou do outro
  -- lado (um `UPDATE` do `visto_em` dentro de algo marcado STABLE) e que
  -- está escrita no CLAUDE.md — aqui não se repete.
  --
  -- E a linha inteira viaja numa COLUNA (`linha winecatalog.vinhos`), não
  -- como `v.*` espalhado pelas CTEs. A razão é o `resumo_linha`, que
  -- recebe uma `winecatalog.vinhos`: assim que uma CTE acrescenta uma
  -- coluna sua (aqui os quatro `ok_*`), o `p.*` dessa CTE passa a ser um
  -- `record` com colunas a mais e o Postgres recusa-o com
  -- «cannot cast type record to vinhos» — em tempo de EXECUÇÃO, com a
  -- lista inteira a morrer por causa disso. Uma coluna de tipo composto
  -- não tem esse problema: é sempre uma `vinhos`, leve o resto da CTE o
  -- que levar.
  WITH achados AS (
    -- As castas normalizadas uma vez só (`[]` quando a ficha não tem lista
    -- nenhuma): a seguir são precisas três vezes — no filtro, na contagem
    -- e na contagem cruzada do modo "todas".
    SELECT v.id, v.visto_em, v.ficha, v AS linha,
           CASE WHEN jsonb_typeof(v.ficha -> 'castas') = 'array'
                THEN v.ficha -> 'castas' ELSE '[]'::jsonb END AS cas
      FROM winecatalog.vinhos v
     WHERE
       -- Uma linha já fundida noutra não entra na lista: deixou de
       -- responder por si (a `achar` desvia-a) e passou a ser o rasto de
       -- uma decisão. Quem a quer ver abre a ficha da alvo, onde ela
       -- aparece, e é lá que se desfaz.
       NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = v.id)
       AND (
         v_q = ''
         OR v.nome     ILIKE '%' || v_q || '%'
         OR v.produtor ILIKE '%' || v_q || '%'
         OR COALESCE(v.ficha ->> 'regiao', '')     ILIKE '%' || v_q || '%'
         OR COALESCE(v.ficha ->> 'sub_regiao', '') ILIKE '%' || v_q || '%'
         OR EXISTS (
              SELECT 1 FROM jsonb_array_elements_text(
                             CASE WHEN jsonb_typeof(v.ficha -> 'castas') = 'array'
                                  THEN v.ficha -> 'castas' ELSE '[]'::jsonb END) c
               WHERE c ILIKE '%' || v_q || '%')
         -- e pela CHAVE: todos os tokens escritos têm de estar na linha
         OR (cardinality(v_toks) > 0
             AND string_to_array(v.chave_base, '-') @> v_toks)
       )
  ),
  -- Cada linha sabe quais dos quatro filtros passa. É isto que permite
  -- contar um grupo "como se ele não estivesse escolhido" sem repetir a
  -- procura quatro vezes.
  marcados AS (
    SELECT a.*,
      (p_tipos IS NULL OR cardinality(p_tipos) = 0
        OR (a.ficha ->> 'tipo') = ANY(p_tipos))                                   AS ok_tipo,
      (p_regioes IS NULL OR cardinality(p_regioes) = 0
        OR COALESCE(a.ficha ->> 'regiao', a.ficha ->> 'pais') = ANY(p_regioes))   AS ok_regiao,
      -- `?|` = tem alguma; `?&` = tem todas. Em jsonb os dois operadores
      -- olham para os ELEMENTOS de um array de texto, que é exatamente o
      -- que a `ficha -> 'castas'` é.
      (p_castas IS NULL OR cardinality(p_castas) = 0
        OR (CASE WHEN v_e THEN a.cas ?& p_castas ELSE a.cas ?| p_castas END))     AS ok_casta,
      (p_precos IS NULL OR cardinality(p_precos) = 0
        OR winecatalog.faixa_preco(winecatalog.preco_num(a.ficha)) = ANY(p_precos)) AS ok_preco
      FROM achados a
  ),
  filtrados AS (
    SELECT * FROM marcados WHERE ok_tipo AND ok_regiao AND ok_casta AND ok_preco
  ),
  pagina AS (
    SELECT f.linha, f.visto_em, f.id FROM filtrados f
     ORDER BY f.visto_em DESC, f.id DESC
     OFFSET v_off LIMIT v_lim
  ),
  f_tipo AS (
    SELECT m.ficha ->> 'tipo' AS v, count(*) AS n
      FROM marcados m
     WHERE m.ok_regiao AND m.ok_casta AND m.ok_preco AND m.ficha ->> 'tipo' IS NOT NULL
     GROUP BY 1
  ),
  f_regiao AS (
    SELECT COALESCE(m.ficha ->> 'regiao', m.ficha ->> 'pais') AS v, count(*) AS n
      FROM marcados m
     WHERE m.ok_tipo AND m.ok_casta AND m.ok_preco
       AND COALESCE(m.ficha ->> 'regiao', m.ficha ->> 'pais') IS NOT NULL
     GROUP BY 1
  ),
  f_casta AS (
    SELECT c AS v, count(*) AS n
      FROM marcados m,
           LATERAL jsonb_array_elements_text(m.cas) c
     WHERE m.ok_tipo AND m.ok_regiao AND m.ok_preco
       -- Em "qualquer uma" a regra do costume basta: o grupo não se conta
       -- a si próprio, e por isso "Syrah 28" continua lá depois de se
       -- escolher Touriga Nacional.
       --
       -- Em "todas em simultâneo" ignorar o grupo inteiro dava um número
       -- que não é o de lado nenhum: "Syrah 28" com a lista a mostrar
       -- três vinhos. Aqui a mesma ideia aplica-se à OPÇÃO e não ao
       -- grupo — conta-se com as OUTRAS castas escolhidas por cima, mas
       -- nunca com a própria. Uma que já esteja escolhida mostra o total
       -- do cruzamento (e continua visível, que é o que permite
       -- desmarcá-la); uma que não esteja mostra em quantos se ficaria se
       -- fosse acrescentada — e desaparece quando esse número é zero,
       -- que é a resposta certa para um caminho sem saída.
       AND (NOT v_e OR p_castas IS NULL OR cardinality(p_castas) = 0
            OR m.cas ?& (SELECT COALESCE(array_agg(s), ARRAY[]::text[])
                           FROM unnest(p_castas) s WHERE s <> c))
     GROUP BY 1
  ),
  f_preco AS (
    SELECT winecatalog.faixa_preco(winecatalog.preco_num(m.ficha)) AS v, count(*) AS n
      FROM marcados m
     WHERE m.ok_tipo AND m.ok_regiao AND m.ok_casta
       AND winecatalog.faixa_preco(winecatalog.preco_num(m.ficha)) IS NOT NULL
     GROUP BY 1
  )
  SELECT jsonb_build_object(
           'total',  (SELECT count(*) FROM filtrados),
           'linhas', COALESCE((SELECT jsonb_agg(winecatalog.resumo_linha(p.linha)
                                        ORDER BY p.visto_em DESC, p.id DESC)
                                 FROM pagina p), '[]'::jsonb),
           'facetas', jsonb_build_object(
             -- Região e castas são listas abertas: mostram-se as mais
             -- cheias, e o ecrã acrescenta as que já estão escolhidas
             -- (senão não havia como as desmarcar).
             'tipos',   COALESCE((SELECT jsonb_agg(x) FROM (
                          SELECT jsonb_build_object('v', v, 'n', n) AS x
                            FROM f_tipo ORDER BY n DESC, v) s), '[]'::jsonb),
             'regioes', COALESCE((SELECT jsonb_agg(x) FROM (
                          SELECT jsonb_build_object('v', v, 'n', n) AS x
                            FROM f_regiao ORDER BY n DESC, v LIMIT 12) s), '[]'::jsonb),
             'castas',  COALESCE((SELECT jsonb_agg(x) FROM (
                          SELECT jsonb_build_object('v', v, 'n', n) AS x
                            FROM f_casta ORDER BY n DESC, v LIMIT 12) s), '[]'::jsonb),
             'precos',  COALESCE((SELECT jsonb_agg(x) FROM (
                          SELECT jsonb_build_object('v', v, 'n', n) AS x
                            FROM f_preco ORDER BY v) s), '[]'::jsonb)
           )
         )
    INTO v_res;

  RETURN v_res;
END;
$$;

-- UMA linha, inteira, com a proveniência CAMPO A CAMPO.
--
-- É o ponto do ecrã do §4.2 e a razão de a app existir: `origens` guarda
-- {campo: {o:origem, f:força, em:quando}} desde o primeiro dia e nunca
-- ninguém o viu. Sem isto não há como responder à pergunta que decide se
-- se confia num número — "de onde é que isto veio?".
--
-- Devolve também as linhas que foram FUNDIDAS nesta (`aliases`): quem abre
-- uma ficha tem direito a saber que ela é o resultado de uma decisão de
-- alguém, e a desfazê-la.
CREATE OR REPLACE FUNCTION winecatalog.ver(p_id bigint)
  RETURNS jsonb
  LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  r winecatalog.vinhos%ROWTYPE;
BEGIN
  IF NOT winecatalog.pode_ler() THEN
    RAISE EXCEPTION 'Sem acesso ao catálogo.';
  END IF;
  SELECT * INTO r FROM winecatalog.vinhos v WHERE v.id = p_id;
  IF r.id IS NULL THEN RETURN NULL; END IF;

  RETURN winecatalog.resumo_linha(r) || jsonb_build_object(
    'chaveBase', r.chave_base,
    'chaveNome', r.chave_nome,
    'baseNome',  r.base_nome,
    'ficha',     r.ficha,
    'origens',   r.origens,
    'fontes',    COALESCE(r.fontes, '[]'::jsonb),
    'criadoEm',  r.criado_em,
    'aliases',   COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
                 'chaveDe', a.chave_de, 'nome', a.nome_de, 'ano', a.ano_de,
                 'quem', a.quem, 'quando', a.quando,
                 'campos', (SELECT count(*) FROM jsonb_object_keys(a.campos_movidos))
               ) ORDER BY a.quando DESC)
          FROM winecatalog.alias a WHERE a.id_para = r.id), '[]'::jsonb)
  );
END;
$$;




-- =====================================================================
-- DUPLICADOS: a fusão MANUAL
-- =====================================================================
-- ---------------------------------------------------------------------
-- GENÉRICO: as palavras que NÃO identificam um vinho
--
-- Serve só à lista de candidatos, e é o que a fez passar de 28 pares para
-- 7 na base real. Sem ela, a varredura propunha coisas destas:
--
--   HERDADE DO SOBROSO Grande Reserva  ×  Bafarela Grande Reserva
--   Esporão Touriga Nacional           ×  Quinta do Noval Touriga Nacional
--   Leo d'Honor                        ×  Ermelinda Freitas Syrah
--
-- Três ruídos diferentes, e vale a pena saber distingui-los:
--   · QUALIFICADORES ("grande", "reserva", "garrafeira", "velhas") — dizem
--     a gama, não o vinho. Dois vinhos que só partilham isto não têm nada
--     a ver um com o outro;
--   · CASTAS ("touriga", "nacional", "syrah") — é a uva, e metade do Douro
--     engarrafa a mesma. Era este o falso positivo perigoso que o
--     documento de arranque já tinha apanhado (`nacional-touriga-vallado`
--     com `esporao-nacional-touriga`);
--   · o PRODUTOR — este não se resolve com uma lista, resolve-se abaixo:
--     a chave junta nome E produtor (de propósito, ver `winecatalog.achar`),
--     por isso dois vinhos diferentes da MESMA casa partilham sempre os
--     tokens dela. O "Leo d'Honor" e o "Ermelinda Freitas Syrah" são os
--     dois da Ermelinda Freitas e não têm mais nada em comum.
--
-- ESTA LISTA NÃO É A DO `base_nome`, e não tem de ser. Aquela decide
-- IDENTIDADE — mexer nela mexe na chave e, por aí, nas três apps. Esta só
-- decide se vale a pena PROPOR um par a uma pessoa, e por isso pode (e
-- deve) ser mais larga: aqui um falso negativo custa um duplicado que fica
-- mais um mês à espera, e um falso positivo custa a confiança na lista
-- toda — que é o que faz alguém carregar em "são o mesmo" sem olhar.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.generico(p_token text)
  RETURNS boolean LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT COALESCE(p_token, '') IN (
    -- gama, cor, estilo
    'reserva','grande','garrafeira','colheita','selecionada','seleccionada',
    'velhas','velha','superior','especial','premium','escolha','tinto','branco',
    'rose','doce','seco','bruto','meio','unoaked','barrica','madeira','antiga',
    'velho','novo','private','selection','edicao','limitada','safra','vindima',
    -- castas
    'touriga','nacional','franca','roriz','tinta','aragonez','trincadeira',
    'castelao','baga','jaen','alfrocheiro','alicante','bouschet','syrah','shiraz',
    'cabernet','sauvignon','merlot','pinot','noir','chardonnay','alvarinho',
    'loureiro','arinto','encruzado','fernao','pires','antao','vaz','verdelho',
    'viosinho','rabigato','gouveio','malvasia','moscatel','sercial','bual',
    'sousao','barroca','bastardo','ramisco','avesso','azal','trajadura','esgana',
    'cao','marufo','carignan','grenache','tempranillo','viognier','riesling',
    'semillon','petit','verdot','malbec','blend'
  );
$$;

-- ---------------------------------------------------------------------
-- CANDIDATOS: a lista que SUGERE, e que nunca decide
--
-- A trave está nas palavras que os dois lados partilham NO NOME e que
-- IDENTIFICAM mesmo um vinho (`fortes`). Tem de haver pelo menos uma —
-- senão o par não é proposto, por muito parecidas que as chaves sejam.
--
-- Repara que a contagem é sobre os tokens do NOME e não sobre os da
-- chave. É isso que apanha o terceiro ruído: a chave traz o produtor lá
-- dentro, e por isso dois vinhos diferentes da mesma casa parecem
-- parecidíssimos por tokens. Pelo nome, não: "Leo d'Honor" e "Ermelinda
-- Freitas Syrah" não têm uma palavra em comum.
--
-- Os cortes de antes ficam como estavam (>=2 tokens comuns, >=60% de
-- sobreposição): servem para medir QUÃO parecidas são duas chaves, e isso
-- continua a ser bom sinal. O que mudou é que já não chegam sozinhos.
--
-- A sobreposição mede-se contra o MENOR dos dois conjuntos: "Crasto" (1
-- token) contra "Crasto Reserva" (2) dá 100% e aparece na lista — que é o
-- que se quer. Contra o maior dava 50% e desaparecia.
--
-- Fora ficam: pares já marcados como distintos, linhas já fundidas
-- noutras, e colheitas diferentes (que nunca se fundem).
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.candidatos(p_limite integer DEFAULT 40)
  RETURNS jsonb
  LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_lim integer := LEAST(GREATEST(COALESCE(p_limite, 40), 1), 200);
  v_res jsonb;
BEGIN
  IF NOT winecatalog.pode_ler() THEN
    RAISE EXCEPTION 'Sem acesso ao catálogo.';
  END IF;

  WITH linhas AS (
    SELECT v.*,
           string_to_array(v.chave_base, '-') AS toks,
           winecatalog.tokens(v.nome)         AS toks_nome
      FROM winecatalog.vinhos v
     WHERE NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = v.id)
  ), pares AS (
    SELECT a.id AS id_a, b.id AS id_b,
           a.chave AS chave_a, b.chave AS chave_b,
           cardinality(ARRAY(SELECT unnest(a.toks) INTERSECT SELECT unnest(b.toks))) AS comuns,
           LEAST(cardinality(a.toks), cardinality(b.toks)) AS menor,
           -- as palavras do NOME que os dois partilham e que identificam
           -- mesmo um vinho: nem gama, nem casta, nem só o produtor
           ARRAY(SELECT t FROM (
                   SELECT unnest(a.toks_nome) INTERSECT SELECT unnest(b.toks_nome)
                 ) x(t)
                  WHERE NOT winecatalog.generico(t)) AS fortes
      FROM linhas a
      JOIN linhas b
        ON b.id > a.id
       -- mesma colheita: duas colheitas nunca se fundem, por isso nem
       -- sequer se propõem
       AND b.ano IS NOT DISTINCT FROM a.ano
  ), filtrados AS (
    SELECT p.*, round(p.comuns::numeric / NULLIF(p.menor, 0), 2) AS sobreposicao
      FROM pares p
     WHERE cardinality(p.fortes) >= 1
       AND p.comuns >= 2
       AND p.menor > 0
       AND p.comuns::numeric / p.menor >= 0.6
       AND NOT EXISTS (
             SELECT 1 FROM winecatalog.distintos d
              WHERE d.chave_a = LEAST(p.chave_a, p.chave_b)
                AND d.chave_b = GREATEST(p.chave_a, p.chave_b))
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'comuns',       f.comuns,
           'sobreposicao', f.sobreposicao,
           -- vai para o ecrã: ver QUE palavra é que os aproximou é o que
           -- torna a decisão de um segundo em vez de um estudo
           'fortes',       to_jsonb(f.fortes),
           'a', winecatalog.resumo_linha(va.*),
           'b', winecatalog.resumo_linha(vb.*)
         ) ORDER BY f.sobreposicao DESC, f.comuns DESC), '[]'::jsonb)
    INTO v_res
    FROM (SELECT * FROM filtrados ORDER BY sobreposicao DESC, comuns DESC LIMIT v_lim) f
    JOIN winecatalog.vinhos va ON va.id = f.id_a
    JOIN winecatalog.vinhos vb ON vb.id = f.id_b;

  RETURN v_res;
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.marcar_distintos(p_id_a bigint, p_id_b bigint)
  RETURNS text LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_a text; v_b text;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode decidir isto.';
  END IF;
  SELECT chave INTO v_a FROM winecatalog.vinhos WHERE id = p_id_a;
  SELECT chave INTO v_b FROM winecatalog.vinhos WHERE id = p_id_b;
  IF v_a IS NULL OR v_b IS NULL OR v_a = v_b THEN
    RAISE EXCEPTION 'Par inválido.';
  END IF;
  INSERT INTO winecatalog.distintos (chave_a, chave_b, quem)
  VALUES (LEAST(v_a, v_b), GREATEST(v_a, v_b), auth.email())
  ON CONFLICT (chave_a, chave_b) DO NOTHING;
  RETURN 'ok';
END;
$$;

-- E desfazer o "não são", que também é uma decisão e também se erra.
CREATE OR REPLACE FUNCTION winecatalog.desmarcar_distintos(p_chave_a text, p_chave_b text)
  RETURNS text LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode decidir isto.';
  END IF;
  DELETE FROM winecatalog.distintos
   WHERE chave_a = LEAST(p_chave_a, p_chave_b)
     AND chave_b = GREATEST(p_chave_a, p_chave_b);
  RETURN 'ok';
END;
$$;

-- A lista dos "não são" já gravados, para se poder voltar atrás sem ir ao
-- SQL Editor.
CREATE OR REPLACE FUNCTION winecatalog.listar_distintos()
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_res jsonb;
BEGIN
  IF NOT winecatalog.pode_ler() THEN
    RAISE EXCEPTION 'Sem acesso ao catálogo.';
  END IF;
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'chaveA', d.chave_a, 'chaveB', d.chave_b,
           'nomeA', va.nome, 'nomeB', vb.nome,
           'quem', d.quem, 'quando', d.quando
         ) ORDER BY d.quando DESC), '[]'::jsonb)
    INTO v_res
    FROM winecatalog.distintos d
    LEFT JOIN winecatalog.vinhos va ON va.chave = d.chave_a
    LEFT JOIN winecatalog.vinhos vb ON vb.chave = d.chave_b;
  RETURN v_res;
END;
$$;




-- ---------------------------------------------------------------------
-- FUNDIR: "são o mesmo vinho"
--
-- `p_id_de` é a linha que deixa de responder por si; `p_id_para` é a que
-- fica. A UI propõe como alvo a mais preenchida, mas quem decide é quem
-- está a olhar.
--
-- Duas coisas acontecem, e a ordem importa:
--   1. os campos passam da perdedora para a alvo UM A UM, e só quando a
--      força de quem os tem é >= à de quem lá está. É a mesma regra da
--      `juntar`, e pela mesma razão: uma fusão não pode ser a porta dos
--      fundos por onde um número copiado à pressa tapa uma
--      `ws-verificacao` que se pagou. A força não se recalcula (não se
--      sabe aqui de que CAMPO ela veio do outro lado, e inventá-la era
--      pior): usa-se a que já está gravada em `origens`;
--   2. grava-se a linha em `winecatalog.alias`, e é ISSO que tira a
--      perdedora do caminho — a `achar()` passa a responder com a alvo
--      quando esbarra nela. **Não se lhe toca nas chaves nem na ficha.**
--
-- O que fica em `campos_movidos` é o estado ANTERIOR de cada campo
-- mexido, para o `separar` ser exato e não um palpite.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.fundir(p_id_de bigint, p_id_para bigint)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  de    winecatalog.vinhos%ROWTYPE;
  para  winecatalog.vinhos%ROWTYPE;
  v_ficha   jsonb;
  v_origens jsonb;
  v_fontes  jsonb;
  v_mov     jsonb := '{}'::jsonb;
  k     text;
  v     jsonb;
  f_de  integer;
  f_para integer;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode fundir linhas.';
  END IF;
  IF p_id_de IS NULL OR p_id_para IS NULL OR p_id_de = p_id_para THEN
    RAISE EXCEPTION 'Par inválido.';
  END IF;

  SELECT * INTO de   FROM winecatalog.vinhos WHERE id = p_id_de   FOR UPDATE;
  SELECT * INTO para FROM winecatalog.vinhos WHERE id = p_id_para FOR UPDATE;
  IF de.id IS NULL OR para.id IS NULL THEN
    RAISE EXCEPTION 'Linha não encontrada.';
  END IF;
  IF EXISTS (SELECT 1 FROM winecatalog.alias WHERE id_de = de.id) THEN
    RAISE EXCEPTION 'Essa linha já foi fundida noutra.';
  END IF;
  -- Fundir A em B quando B já foi fundida em C deixava uma cadeia que a
  -- `achar` não segue (resolve UM salto, de propósito — uma cadeia é um
  -- ciclo à espera de acontecer).
  IF EXISTS (SELECT 1 FROM winecatalog.alias WHERE id_de = para.id) THEN
    RAISE EXCEPTION 'A linha escolhida para ficar já foi fundida noutra — desfaz essa primeiro.';
  END IF;

  -- A trave que segura a nota e o preço. Não é um aviso: é um erro.
  IF de.ano IS DISTINCT FROM para.ano
     AND de.ano IS NOT NULL AND para.ano IS NOT NULL THEN
    RAISE EXCEPTION 'São colheitas diferentes (% e %) — essas nunca se fundem.',
      de.ano, para.ano;
  END IF;

  v_ficha   := para.ficha;
  v_origens := para.origens;
  v_fontes  := COALESCE(para.fontes, '[]'::jsonb);

  FOR k, v IN SELECT key, value FROM jsonb_each(de.ficha) LOOP
    CONTINUE WHEN v IS NULL OR jsonb_typeof(v) = 'null'
                  OR v = '""'::jsonb OR v = '[]'::jsonb OR v = '{}'::jsonb;
    f_de   := COALESCE((de.origens -> k ->> 'f')::integer, 0);
    f_para := COALESCE((v_origens  -> k ->> 'f')::integer, 0);
    IF NOT (v_ficha ? k) OR f_de >= f_para THEN
      v_mov := v_mov || jsonb_build_object(k, jsonb_build_object(
        'antes',         CASE WHEN v_ficha ? k THEN v_ficha -> k END,
        'antes_origem',  v_origens -> k,
        'depois_origem', COALESCE(de.origens -> k, '{}'::jsonb)
      ));
      v_ficha   := v_ficha   || jsonb_build_object(k, v);
      v_origens := v_origens || jsonb_build_object(k, COALESCE(de.origens -> k, '{}'::jsonb));
    END IF;
  END LOOP;

  -- As fontes juntam-se sem repetir e ficam pelas 8, como na `juntar`:
  -- são para se poder ir ver de onde veio isto, não um arquivo.
  SELECT COALESCE(jsonb_agg(f), '[]'::jsonb) INTO v_fontes FROM (
    SELECT DISTINCT ON (f ->> 'url') f
      FROM jsonb_array_elements(v_fontes || COALESCE(de.fontes, '[]'::jsonb)) f
     WHERE COALESCE(f ->> 'url', '') <> ''
     ORDER BY (f ->> 'url')
     LIMIT 8
  ) x;

  UPDATE winecatalog.vinhos SET
    ficha    = v_ficha,
    origens  = v_origens,
    fontes   = v_fontes,
    -- o nome mais COMPRIDO fica, como na `juntar`
    nome     = CASE WHEN length(COALESCE(de.nome,'')) > length(nome) THEN de.nome ELSE nome END,
    produtor = CASE WHEN produtor = '' THEN COALESCE(de.produtor,'') ELSE produtor END,
    ano      = COALESCE(ano, de.ano),
    atualizado_em = now()
  WHERE id = para.id;

  INSERT INTO winecatalog.alias (chave_de, chave_para, id_de, id_para,
                                 nome_de, ano_de, campos_movidos, quem)
  VALUES (de.chave, para.chave, de.id, para.id, de.nome, de.ano, v_mov, auth.email())
  ON CONFLICT (chave_de) DO UPDATE
    SET chave_para = EXCLUDED.chave_para, id_para = EXCLUDED.id_para,
        campos_movidos = EXCLUDED.campos_movidos, quem = EXCLUDED.quem,
        quando = now();

  -- Um par fundido deixa de ser um par por decidir.
  DELETE FROM winecatalog.distintos
   WHERE chave_a = LEAST(de.chave, para.chave)
     AND chave_b = GREATEST(de.chave, para.chave);

  RETURN jsonb_build_object(
    'ok', true, 'id', para.id,
    'campos', (SELECT count(*) FROM jsonb_object_keys(v_mov))
  );
END;
$$;


-- ---------------------------------------------------------------------
-- SEPARAR: desfazer uma fusão — literalmente apagar uma linha
--
-- A perdedora volta a responder por si assim que o alias desaparece (é a
-- `achar` que deixa de a desviar), e cada campo volta ao que era ANTES da
-- fusão — mas SÓ os campos que ninguém reescreveu entretanto. A
-- comparação é com a entrada de `origens` que a fusão lá pôs: se ela
-- ainda está exatamente igual, ninguém tocou; se mudou, foi outra escrita
-- e essa manda.
--
-- Desfazer uma fusão de setembro não pode deitar fora uma verificação de
-- outubro — é por isso que isto não é um "restaurar a cópia de segurança"
-- em bloco.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.separar(p_chave_de text)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  a     winecatalog.alias%ROWTYPE;
  para  winecatalog.vinhos%ROWTYPE;
  v_ficha   jsonb;
  v_origens jsonb;
  k     text;
  v     jsonb;
  n_rep integer := 0;
  n_mant integer := 0;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode desfazer uma fusão.';
  END IF;

  SELECT * INTO a FROM winecatalog.alias WHERE chave_de = p_chave_de;
  IF a.chave_de IS NULL THEN RAISE EXCEPTION 'Essa fusão não existe.'; END IF;

  SELECT * INTO para FROM winecatalog.vinhos WHERE id = a.id_para FOR UPDATE;
  IF para.id IS NOT NULL THEN
    v_ficha   := para.ficha;
    v_origens := para.origens;
    FOR k, v IN SELECT key, value FROM jsonb_each(a.campos_movidos) LOOP
      IF (v_origens -> k) IS NOT DISTINCT FROM (v -> 'depois_origem') THEN
        IF (v -> 'antes') IS NULL OR jsonb_typeof(v -> 'antes') = 'null' THEN
          v_ficha   := v_ficha   - k;      -- não estava lá: volta a não estar
          v_origens := v_origens - k;
        ELSE
          v_ficha   := v_ficha   || jsonb_build_object(k, v -> 'antes');
          v_origens := v_origens || jsonb_build_object(k, COALESCE(v -> 'antes_origem', '{}'::jsonb));
        END IF;
        n_rep := n_rep + 1;
      ELSE
        n_mant := n_mant + 1;              -- alguém escreveu depois: fica
      END IF;
    END LOOP;
    UPDATE winecatalog.vinhos
       SET ficha = v_ficha, origens = v_origens, atualizado_em = now()
     WHERE id = para.id;
  END IF;

  DELETE FROM winecatalog.alias WHERE chave_de = a.chave_de;

  RETURN jsonb_build_object('ok', true, 'repostos', n_rep, 'mantidos', n_mant);
END;
$$;
-- =====================================================================
-- 4. O TAMANHO DO CATÁLOGO, E DE ONDE VEIO CADA CAMPO
--
-- A segunda metade do ecrã de Resumo. "Quantos campos vieram de cada
-- origem" é a pergunta que apanhou a avaria que esteve semanas de pé: os
-- 3106 campos do catálogo estavam TODOS a força 3, nenhum tinha entrado
-- por uma pesquisa, e nenhum podia, porque 3 tapa 2. Um número destes no
-- ecrã tê-la-ia apanhado no primeiro dia.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.resumo()
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_res jsonb;
BEGIN
  IF NOT winecatalog.pode_ler() THEN
    RAISE EXCEPTION 'Sem acesso ao catálogo.';
  END IF;

  WITH vivas AS (
    SELECT v.* FROM winecatalog.vinhos v WHERE NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = v.id)
  ), campos AS (
    SELECT o.key AS campo,
           COALESCE(o.value ->> 'o', '(sem origem)') AS origem,
           COALESCE((o.value ->> 'f')::integer, 0)   AS forca
      FROM vivas v, jsonb_each(v.origens) o
  )
  SELECT jsonb_build_object(
    'linhas',        (SELECT count(*) FROM vivas),
    'distintos',     (SELECT count(DISTINCT chave_base) FROM vivas),
    'semAno',        (SELECT count(*) FROM vivas WHERE ano IS NULL),
    'campos',        (SELECT count(*) FROM campos),
    'mediaCampos',   (SELECT round(AVG(n), 1) FROM (
                        SELECT (SELECT count(*) FROM jsonb_object_keys(v.ficha)) AS n
                          FROM vivas v) t),
    'fundidas',      (SELECT count(*) FROM winecatalog.alias),
    'distintosMarcados', (SELECT count(*) FROM winecatalog.distintos),
    -- quantos campos por ORIGEM, e a que força entraram
    'origens', COALESCE((
        SELECT jsonb_agg(jsonb_build_object('origem', c.origem, 'forca', c.forca, 'campos', c.n)
                         ORDER BY c.n DESC)
          FROM (SELECT origem, forca, count(*) AS n FROM campos GROUP BY origem, forca) c
      ), '[]'::jsonb),
    -- e quantos campos VOLÁTEIS estão velhos (>30 dias): é o que as apps
    -- vão pedir outra vez à IA na próxima pergunta
    'volateisVelhos', (
        SELECT count(*) FROM vivas v, jsonb_each(v.origens) o
         WHERE winecatalog.volatil(o.key)
           AND COALESCE((o.value ->> 'em')::timestamptz, v.criado_em) < now() - interval '30 days')
  ) INTO v_res;

  RETURN v_res;
END;
$$;


-- ---------------------------------------------------------------------
-- SYNC_LOG — o que a Edge Function desta app gastou
--
-- As outras duas apps têm a sua (`garrafeira.sync_log`,
-- `wineselection.sync_log`) e a vista `winecatalog.consumo` já as lê. A
-- partir do momento em que ESTA app também manda pesquisar, também gasta
-- — e um gasto que não aparece no ecrã do "está a poupar quanto?" faz o
-- número mentir por omissão. Mesma forma das outras duas, de propósito:
-- é o que deixa a vista juntá-las sem casos especiais.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.sync_log (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  origem    text NOT NULL DEFAULT 'function',   -- 'function' | 'app'
  acao      text NOT NULL,
  estado    text NOT NULL,                      -- 'pedido' | 'ok' | 'erro'
  quem      text,
  detalhe   jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sync_log_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS sync_log_criado_idx ON winecatalog.sync_log (criado_em DESC);
ALTER TABLE winecatalog.sync_log ENABLE ROW LEVEL SECURITY;


-- =====================================================================
-- 5. O CONSUMO DAS OUTRAS DUAS APPS — `winecatalog.consumo`
--
-- A pergunta que deu origem ao catálogo ("está a poupar quanto?") tem a
-- resposta em `garrafeira.sync_log` e `wineselection.sync_log` — duas
-- tabelas em dois schemas que a WineCatalog não tem (nem deve ter) que
-- conhecer. A vista põe as duas na mesma forma, e a app fala só com o
-- `winecatalog`, sem espreitar para dentro das outras duas.
--
-- AS UNIDADES NÃO SÃO A MESMA COISA, e somá-las era inventar um número:
--   · a `vinho-info` conta CAMPOS   (castas, região, teor…);
--   · a `sugerir-vinho` conta NOTAS (uma por vinho da carta);
--   · a `verificar-vinhos` conta VINHOS.
-- Por isso cada linha diz em que UNIDADE está, e quem soma só soma dentro
-- da mesma. O que atravessa as três e se pode somar é o PEDIDO: um pedido
-- que não foi à IA nenhuma vez (`so_catalogo`) é uma ida poupada, e essa
-- conta-se igual nas três.
--
-- O CUSTO: `custo_estimado_eur` vem dos próprios logs, e onde não vem é
-- porque não houve chamada nenhuma (a `vinho-info` servida pelo catálogo
-- nem sequer escreve o campo) — daí o zero. É uma ESTIMATIVA GROSSEIRA,
-- não um preço publicado, e a pesquisa Google é faturada à parte por
-- pedido. Os TOKENS é que são facto: vêm da API do Gemini. O ecrã tem de
-- dizer as duas coisas.
--
-- SEGURANÇA: uma vista não é `security_invoker`, corre como o DONO, e o
-- dono aqui passa por cima da RLS das duas `sync_log`. Ou seja: esta vista
-- vê tudo, INCLUINDO o `quem` de cada pedido. Por isso não se dá SELECT
-- dela a ninguém (ver os REVOKEs no fim) e quem lhe chega é só a
-- `ia_uso.poupanca_catalogo()` da AI-API-Control (ver abaixo), que agrega
-- e NUNCA devolve o `quem` — quanto é que o catálogo poupou não precisa de
-- dizer quem é que andou a usar o quê.
-- =====================================================================

-- Ler um número de um jsonb sem rebentar se lá estiver um texto. Um
-- `(detalhe->>'x')::numeric` seco morre com a linha inteira no dia em que
-- alguém gravar "n/d" — e o ecrã ficava em branco sem se perceber porquê.
CREATE OR REPLACE FUNCTION winecatalog.num(p jsonb, k text)
  RETURNS numeric LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE WHEN jsonb_typeof(p -> k) = 'number' THEN (p ->> k)::numeric ELSE 0 END;
$$;

CREATE OR REPLACE VIEW winecatalog.consumo AS
  -- Garrafeira / vinho-info — conta CAMPOS.
  -- Só `origem='function'`: as linhas com origem 'app' são outro tipo de
  -- registo (a app a anotar-se a si própria) e não são pedidos à IA.
  SELECT 'garrafeira'::text AS app,
         l.acao,
         l.estado,
         l.criado_em,
         COALESCE(l.detalhe ->> 'modo', '')                  AS modo,
         (COALESCE(l.detalhe ->> 'modo', '') = 'catalogo')    AS so_catalogo,
         'campos'::text                                      AS unidade,
         CASE WHEN COALESCE(l.detalhe ->> 'modo', '') = 'catalogo'
              THEN winecatalog.num(l.detalhe, 'campos')
              ELSE winecatalog.num(l.detalhe, 'catalogo_campos') END AS itens_catalogo,
         winecatalog.num(l.detalhe, 'ia_campos')                 AS itens_ia,
         winecatalog.num(l.detalhe, 'custo_estimado_eur')        AS custo_eur,
         winecatalog.num(l.detalhe -> 'usageMetadata', 'totalTokenCount') AS tokens
    FROM garrafeira.sync_log l
   WHERE l.origem = 'function'

  UNION ALL

  -- WineSelection / sugerir-vinho — conta NOTAS da carta.
  -- `so_catalogo` é sempre falso e não é um esquecimento: esta chamada lê
  -- uma FOTOGRAFIA, e isso não há catálogo que o responda. O que o
  -- catálogo aqui poupa é a SEGUNDA chamada (a das notas), e isso
  -- aparece em `itens_catalogo`.
  SELECT 'wineselection'::text,
         l.acao,
         l.estado,
         l.criado_em,
         COALESCE(l.detalhe ->> 'modelo', ''),
         false,
         'notas'::text,
         winecatalog.num(l.detalhe, 'pontuacoes_catalogo'),
         GREATEST(winecatalog.num(l.detalhe, 'pontuacoes_aprox')
                  - winecatalog.num(l.detalhe, 'pontuacoes_catalogo'), 0),
         winecatalog.num(l.detalhe, 'custo_estimado_eur'),
         winecatalog.num(l.detalhe -> 'usageMetadata', 'totalTokenCount')
    FROM wineselection.sync_log l
   WHERE l.acao = 'sugerir_vinho'

  UNION ALL

  -- WineSelection / verificar-vinhos — conta VINHOS. É a mais cara das
  -- três (pesquisa Google a sério), e a única da WineSelection que o
  -- catálogo pode servir inteira.
  SELECT 'wineselection'::text,
         l.acao,
         l.estado,
         l.criado_em,
         COALESCE(l.detalhe ->> 'modelo', ''),
         (COALESCE(l.detalhe ->> 'modelo', '') = 'catalogo'),
         'vinhos'::text,
         winecatalog.num(l.detalhe, 'catalogo'),
         winecatalog.num(l.detalhe, 'gemini'),
         winecatalog.num(l.detalhe, 'custo_estimado_eur'),
         winecatalog.num(l.detalhe -> 'usageMetadata', 'totalTokenCount')
    FROM wineselection.sync_log l
   WHERE l.acao = 'verificar_vinhos'

  UNION ALL

  -- WineCatalog / catalogo-info — conta CAMPOS, como a `vinho-info`, e é
  -- a mesma pergunta feita do outro lado: aqui não há garrafeira nenhuma,
  -- há o admin a mandar pesquisar uma linha do catálogo.
  --
  -- `so_catalogo` é SEMPRE falso, e desta vez não é um pormenor: esta
  -- chamada existe precisamente para ir buscar o que o catálogo NÃO tem.
  -- Servi-la pelo catálogo seria devolver a pergunta a quem a fez. Por
  -- isso esta app só aparece no ecrã do lado do GASTO — e é bom que
  -- apareça: a partir do momento em que o catálogo também paga, um número
  -- de poupança que a ignorasse estava a mentir por omissão.
  SELECT 'winecatalog'::text,
         l.acao,
         l.estado,
         l.criado_em,
         COALESCE(l.detalhe ->> 'modelo', ''),
         false,
         'campos'::text,
         0::numeric,
         winecatalog.num(l.detalhe, 'campos'),
         winecatalog.num(l.detalhe, 'custo_estimado_eur'),
         winecatalog.num(l.detalhe -> 'usageMetadata', 'totalTokenCount')
    FROM winecatalog.sync_log l
   WHERE l.origem = 'function';


-- O Resumo (§4.1) — `winecatalog.consumo_resumo` — JÁ NÃO VIVE AQUI.
--
-- "Quanto é que o catálogo está a poupar" é uma pergunta de CUSTO, e desde
-- 23/09/2026 quem responde a perguntas de custo é a app AI-API-Control:
-- a `ia_uso.poupanca_catalogo()` (fonte de verdade:
-- `AI-API-Control/db/poupanca.sql`) agrega ESTA vista. Duas apps a dizer
-- quanto se gastou, com números diferentes, era o erro de sempre.
--
-- A VISTA FICA AQUI, e é por isso que mexer-lhe mexe com outro repo: é a
-- tradução de cada `sync_log` e é de quem conhece os `sync_log` das apps de
-- vinhos. Mudar o nome ou tirar uma coluna parte o cartão "Catálogo de
-- vinhos" no Resumo da AI-API-Control, e só se nota quando ele corre.
DROP FUNCTION IF EXISTS winecatalog.consumo_resumo(integer);




-- =====================================================================
-- QUEM PODE CHAMAR O QUÊ
--
-- O schema `winecatalog` está EXPOSTO na API (é assim que a app e as três
-- Edge Functions lhe falam) e uma função SECURITY DEFINER nasce com
-- EXECUTE para PUBLIC. As duas coisas juntas são um caminho direto para
-- dentro se alguém se esquecer de um REVOKE.
--
-- LEIA-SE ISTO COM ATENÇÃO, que é o ponto onde a mudança de casa podia
-- ter aberto um buraco: enquanto o catálogo viveu num schema só dele, a
-- `vinhos` estava protegida por DUAS coisas — RLS sem policy nenhuma E
-- nenhum GRANT a `anon`/`authenticated`. Ao vir para o schema da APP, um
-- `GRANT ALL ON ALL TABLES IN SCHEMA winecatalog TO anon, authenticated`
-- (que é o que as apps irmãs fazem no schema delas, e que este repo
-- chegou a ter) apanhava-a de caminho e deixava-a só com a RLS. Continuava
-- fechada — mas por uma trave em vez de duas, e sem ninguém dar por isso.
--
-- Por isso o `db/schema.sql` NÃO dá grants em bloco neste schema: dá-os
-- tabela a tabela, e as do catálogo não estão lá. Se um dia acrescentares
-- uma tabela aqui, a pergunta a fazer é a mesma: isto é da APP (e leva
-- GRANT + policies) ou é do CATÁLOGO (e não leva nada)?
-- =====================================================================

-- As três tabelas do catálogo e a config: nenhum GRANT a quem tem login.
-- Só a service role (Edge Functions) e as funções SECURITY DEFINER.
REVOKE ALL ON winecatalog.vinhos    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON winecatalog.alias     FROM PUBLIC, anon, authenticated;
REVOKE ALL ON winecatalog.distintos FROM PUBLIC, anon, authenticated;
REVOKE ALL ON winecatalog.config    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON winecatalog.consumo   FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.vinhos    TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.alias     TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.distintos TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.config    TO service_role;
REVOKE ALL ON winecatalog.sync_log FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.sync_log TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA winecatalog    TO service_role;

-- As TRÊS das Edge Functions: service role e mais ninguém. Sem isto,
-- qualquer pessoa com login podia chamar `juntar` do browser e carimbar o
-- que lhe apetecesse com a força de quem tem a garrafa na mão — e
-- envenenar as três apps de uma vez.
REVOKE ALL ON FUNCTION winecatalog.juntar(text, text, integer, jsonb, text, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.procurar(text, text, integer, integer)          FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.procurar_lote(jsonb, integer)                   FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.juntar(text, text, integer, jsonb, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.procurar(text, text, integer, integer)          TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.procurar_lote(jsonb, integer)                   TO service_role;

-- As da app: chamadas por uma PESSOA, com o seu JWT, do browser. Por isso
-- `authenticated` tem de poder chamá-las, e é DENTRO de cada uma que se
-- confirma quem é (`pode_ler()` para ler, `sou_admin()` para decidir).
-- O `anon` nunca: não há modo convidado.
REVOKE ALL ON FUNCTION winecatalog.listar(text, integer, integer, text[], text[], text[], text[], boolean)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.ver(bigint)                      FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.candidatos(integer)              FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.listar_distintos()               FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.resumo()                         FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.fundir(bigint, bigint)           FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.separar(text)                    FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.marcar_distintos(bigint, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.desmarcar_distintos(text, text)  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.definir_admin(text)              FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION winecatalog.listar(text, integer, integer, text[], text[], text[], text[], boolean)
  TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.ver(bigint)                      TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.candidatos(integer)              TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.listar_distintos()               TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.resumo()                         TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.fundir(bigint, bigint)           TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.separar(text)                    TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.marcar_distintos(bigint, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.desmarcar_distintos(text, text)  TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.definir_admin(text)              TO authenticated;

-- As de apoio: só as duas de identidade é que a UI precisa de chamar
-- (para saber que botões mostrar). As outras são chamadas de DENTRO das
-- de cima, onde o SECURITY DEFINER já as alcança.
REVOKE ALL ON FUNCTION winecatalog.admin_email()                      FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.generico(text)                     FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.resumo_linha(winecatalog.vinhos)   FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.preco_num(jsonb)                   FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.faixa_preco(numeric)               FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.sou_admin()                        FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.pode_ler()                         FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.sou_admin()   TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.pode_ler()    TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.admin_email() TO service_role;

-- ---------------------------------------------------------------------
-- CONFIRMA SEMPRE, depois de correr isto. Um REVOKE esquecido não dá erro
-- nenhum — dá uma porta aberta calada.
--
-- A linha que interessa: `juntar`, `procurar`, `procurar_lote`,
-- `admin_email` e `resumo_linha` têm de estar a `false` para
-- `authenticated`. As da app, a `true` para `authenticated` e `false`
-- para `anon`.
--
-- As de cálculo da chave (`tokens`, `chave`, `achar`, `forca`, `volatil`,
-- `num`…) aparecem a `true` nos dois, e não é um esquecimento: são puras
-- sobre os argumentos, e a única que lê a tabela (`achar`) corre como quem
-- chama e esbarra na RLS na mesma.
--
--   SELECT p.proname,
--          has_function_privilege('authenticated', p.oid, 'EXECUTE') AS auth,
--          has_function_privilege('anon',          p.oid, 'EXECUTE') AS anon
--     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--    WHERE n.nspname = 'winecatalog'
--    ORDER BY 1;
--
-- E que a `vinhos` continua fechada às duas travas — RLS sem policy E sem
-- grant nenhum a quem tem login:
--
--   SELECT count(*) FROM pg_policies
--    WHERE schemaname='winecatalog' AND tablename='vinhos';            -- 0
--   SELECT has_table_privilege('authenticated','winecatalog.vinhos','SELECT');  -- false
-- ---------------------------------------------------------------------
