-- =====================================================================
-- COMENTÁRIOS E SUGESTÕES — o que as garrafeiras têm a dizer (28/09/2026,
-- pedido do dono das apps).
--
-- Corre DEPOIS de `cor-na-chave.sql` (usa a `achar` com a cor) e de
-- `curadoria.sql`. Na Garrafeira, a seguir: `db/migracao-comentarios.sql`
-- (migração 26), que é a porta por onde as pessoas escrevem.
--
-- O `reportar` (curadoria.sql) já existia e continua: é o "o errado é o
-- catálogo" de UM campo, com os dois valores guardados, e só aparece quando
-- a comparação encontra uma diferença. Faltavam duas coisas que não cabem
-- nele:
--
--   · um COMENTÁRIO SOBRE UM VINHO — "estes atributos não estão bem",
--     "atualizem-no a partir deste site", ou outro problema qualquer — mesmo
--     quando a comparação não encontrou diferença nenhuma (o catálogo e a
--     garrafeira podem estar os dois errados, e é o caso mais comum: a
--     garrafeira trouxe o erro do catálogo);
--   · uma SUGESTÃO sobre a app, que não é de vinho nenhum.
--
-- Uma tabela para as duas, porque são a mesma conversa (alguém escreve, o
-- admin lê, responde e fecha) e aparecem no mesmo sítio: dois cartões em
-- Alertas, na app, e dois separadores no painel do PC.
--
-- É do catálogo e não da Garrafeira pela mesma razão dos `reportes`: quem as
-- lê é o admin do catálogo, na app do catálogo e no painel; a `app` diz de
-- onde veio cada uma, e a WineSelection pode escrever aqui no dia em que
-- tiver a sua porta.
--
-- A INVARIANTE 2 fica onde estava: isto não abre garrafeira nenhuma. Guarda
-- o que a pessoa escreveu, o vinho como ELA o tem (nome, produtor, ano, cor)
-- e os valores dos campos de que se queixa — a mesma coisa que um reporte já
-- guarda, e com o mesmo `quem`. Nunca as notas pessoais, o preço de compra,
-- o lugar ou a fotografia: nem sequer chegam a esta função.
-- =====================================================================

CREATE TABLE IF NOT EXISTS winecatalog.comentarios (
  id               bigint GENERATED BY DEFAULT AS IDENTITY,
  tipo             text NOT NULL,                 -- vinho | sugestao
  motivo           text NOT NULL,                 -- ver o CHECK
  texto            text,
  link             text,                          -- o site de onde atualizar
  campos           text[] NOT NULL DEFAULT '{}',  -- os atributos de que se queixa
  valores_deles    jsonb,                         -- esses campos na garrafeira de quem escreveu, então
  valores_catalogo jsonb,                         -- esses campos no catálogo, então
  vinho_id         bigint,                        -- a linha do catálogo, se a achou
  chave            text,
  nome             text,
  produtor         text NOT NULL DEFAULT '',
  ano              integer,
  cor              text,
  app              text NOT NULL DEFAULT 'garrafeira',
  quem             text NOT NULL,
  quando           timestamptz NOT NULL DEFAULT now(),
  estado           text NOT NULL DEFAULT 'aberto', -- aberto | duvida | resolvido | rejeitado
  resposta         text,                          -- o que o admin respondeu ao fechar (quem escreveu vê-a)
  fechado_em       timestamptz,
  fechado_por      text,
  por_ler_autor    boolean NOT NULL DEFAULT false, -- o admin disse alguma coisa que quem escreveu ainda não viu
  CONSTRAINT comentarios_pkey PRIMARY KEY (id),
  CONSTRAINT comentarios_tipo_chk CHECK (tipo IN ('vinho', 'sugestao')),
  -- vinho: atributos errados · atualizar a partir de um site · outro problema
  -- sugestão: uma ideia/melhoria · algo que não funciona
  CONSTRAINT comentarios_motivo_chk CHECK (
       (tipo = 'vinho'    AND motivo IN ('atributos', 'atualizar', 'outro'))
    OR (tipo = 'sugestao' AND motivo IN ('melhoria', 'problema'))),
  CONSTRAINT comentarios_estado_chk CHECK (estado IN ('aberto', 'duvida', 'resolvido', 'rejeitado')),
  CONSTRAINT comentarios_vinho_chk CHECK (tipo <> 'vinho' OR COALESCE(nome, '') <> '')
);
CREATE INDEX IF NOT EXISTS comentarios_abertos_idx ON winecatalog.comentarios (tipo, quando DESC)
  WHERE estado = 'aberto';
CREATE INDEX IF NOT EXISTS comentarios_quem_idx ON winecatalog.comentarios (quem, quando DESC);

ALTER TABLE winecatalog.comentarios ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- A CONVERSA (28/09/2026, o dono: "um estado de devolver uma dúvida").
--
-- Fechar com uma resposta era a única coisa que o admin podia dizer — e um
-- "qual é o site?" obrigava a dar o comentário por tratado sem o estar. O
-- estado `duvida` é a vez de QUEM ESCREVEU: o admin pergunta, a pessoa
-- responde, e o comentário volta a `aberto` (a vez do admin). Cada fala é
-- uma linha em `comentarios_msgs`, com o estado em que o comentário ficou
-- — é isso que faz o fecho ("tratado") aparecer na conversa, com ou sem
-- texto, e é nesta tabela que o push (migração 27 da Garrafeira) se
-- pendura: uma fala nova é sempre alguém a quem avisar.
--
-- `por_ler_autor` é o aviso do outro lado: o admin perguntou ou fechou, e
-- quem escreveu ainda não abriu a lista. Desliga-se quando ela a abre
-- (`comentarios_marcar_lidos`) ou quando ela própria responde.
-- ---------------------------------------------------------------------
ALTER TABLE winecatalog.comentarios ADD COLUMN IF NOT EXISTS por_ler_autor boolean NOT NULL DEFAULT false;
ALTER TABLE winecatalog.comentarios DROP CONSTRAINT IF EXISTS comentarios_estado_chk;
ALTER TABLE winecatalog.comentarios ADD CONSTRAINT comentarios_estado_chk
  CHECK (estado IN ('aberto', 'duvida', 'resolvido', 'rejeitado'));
CREATE INDEX IF NOT EXISTS comentarios_por_ler_idx ON winecatalog.comentarios (quem) WHERE por_ler_autor;

CREATE TABLE IF NOT EXISTS winecatalog.comentarios_msgs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  comentario_id bigint NOT NULL,
  de            text NOT NULL,             -- autor | admin
  estado        text,                      -- o estado em que o comentário ficou
  texto         text,
  quem          text NOT NULL,
  quando        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT comentarios_msgs_pkey PRIMARY KEY (id),
  CONSTRAINT comentarios_msgs_com_fkey FOREIGN KEY (comentario_id)
    REFERENCES winecatalog.comentarios (id) ON DELETE CASCADE,
  CONSTRAINT comentarios_msgs_de_chk CHECK (de IN ('autor', 'admin')),
  CONSTRAINT comentarios_msgs_estado_chk CHECK (estado IS NULL OR estado IN ('aberto', 'duvida', 'resolvido', 'rejeitado'))
);
CREATE INDEX IF NOT EXISTS comentarios_msgs_idx ON winecatalog.comentarios_msgs (comentario_id, quando);
ALTER TABLE winecatalog.comentarios_msgs ENABLE ROW LEVEL SECURITY;

-- As falas de um comentário, pela ordem. `com_quem` só para o admin: quem
-- escreveu vê "o admin", não o email de quem lhe respondeu.
CREATE OR REPLACE FUNCTION winecatalog.comentario_msgs(p_id bigint, p_com_quem boolean DEFAULT false)
  RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'de', m.de, 'estado', m.estado, 'texto', m.texto, 'quando', m.quando)
           || CASE WHEN p_com_quem THEN jsonb_build_object('quem', m.quem) ELSE '{}'::jsonb END
         ORDER BY m.quando, m.id), '[]'::jsonb)
    FROM winecatalog.comentarios_msgs m WHERE m.comentario_id = p_id;
$$;


-- ---------------------------------------------------------------------
-- COMENTAR — escrever um. Só a `service_role` a chama de fora; quem chega
-- aqui são as portas das apps (na Garrafeira, `garrafeira.comentar_vinho`
-- e `garrafeira.sugerir`, SECURITY DEFINER), que conferem antes quem pode
-- falar de que vinho (`pode_ver`) e tiram os valores da BD — os
-- `p_valores_deles` nunca são texto escrito numa caixa.
--
-- O `quem` sai do JWT (`auth.email()`), que atravessa a porta intacto.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.comentar(
  p_tipo text, p_motivo text, p_texto text,
  p_nome text DEFAULT NULL, p_produtor text DEFAULT NULL, p_ano integer DEFAULT NULL,
  p_cor text DEFAULT NULL, p_campos text[] DEFAULT NULL,
  p_valores_deles jsonb DEFAULT NULL, p_link text DEFAULT NULL,
  p_app text DEFAULT 'garrafeira'
) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_quem   text := lower(COALESCE(auth.email(), ''));
  v_tipo   text := btrim(COALESCE(p_tipo, ''));
  v_motivo text := btrim(COALESCE(p_motivo, ''));
  v_texto  text := NULLIF(left(btrim(COALESCE(p_texto, '')), 2000), '');
  v_link   text := NULLIF(left(btrim(COALESCE(p_link, '')), 500), '');
  v_nome   text := NULLIF(btrim(COALESCE(p_nome, '')), '');
  v_prod   text := btrim(COALESCE(p_produtor, ''));
  v_campos text[];
  v_vid    bigint;
  r        winecatalog.vinhos%ROWTYPE;
  v_cat    jsonb;
  v_id     bigint;
BEGIN
  IF v_quem = '' THEN RAISE EXCEPTION 'Precisa de sessão iniciada.'; END IF;
  IF v_tipo NOT IN ('vinho', 'sugestao') THEN RAISE EXCEPTION 'Tipo inválido.'; END IF;
  IF (v_tipo = 'vinho'    AND v_motivo NOT IN ('atributos', 'atualizar', 'outro'))
  OR (v_tipo = 'sugestao' AND v_motivo NOT IN ('melhoria', 'problema')) THEN
    RAISE EXCEPTION 'Motivo inválido.';
  END IF;
  IF v_tipo = 'vinho' AND v_nome IS NULL THEN RAISE EXCEPTION 'Falta o vinho.'; END IF;
  -- Um link é um endereço, e só http(s): o admin vai abri-lo (e o
  -- "Procurar informação" do catálogo pode lê-lo).
  IF v_link IS NOT NULL AND v_link !~* '^https?://[^\s<>"'']+$' THEN
    RAISE EXCEPTION 'O link tem de ser um endereço completo, começado por https://';
  END IF;
  IF v_motivo = 'atualizar' AND v_link IS NULL THEN
    RAISE EXCEPTION 'Diz de que site é para atualizar (o link da página do vinho).';
  END IF;
  -- Atualizar a partir de um site diz-se pelo link; o resto precisa de
  -- palavras — "está mal" sem dizer o quê não se consegue tratar.
  IF v_motivo <> 'atualizar' AND COALESCE(length(v_texto), 0) < 3 THEN
    RAISE EXCEPTION 'Escreve o que se passa.';
  END IF;

  -- Os campos: só nomes de coluna (os da ficha, mais nome/produtor/ano).
  SELECT COALESCE(array_agg(DISTINCT c ORDER BY c), '{}') INTO v_campos
    FROM unnest(COALESCE(p_campos, '{}'::text[])) c
   WHERE c ~ '^[a-z_]{2,30}$';
  v_campos := v_campos[1:30];

  -- A mesma trava dos reportes: chega para qualquer pessoa, e não chega
  -- para entupir o ecrã do admin.
  IF (SELECT count(*) FROM winecatalog.comentarios
       WHERE quem = v_quem AND estado = 'aberto') >= 30 THEN
    RAISE EXCEPTION 'Já tens 30 comentários por tratar — espera que o admin os veja.';
  END IF;

  -- Dois toques no botão não são dois comentários: o mesmo, ainda aberto
  -- e escrito há menos de 10 minutos, devolve-se em vez de se repetir.
  SELECT id INTO v_id FROM winecatalog.comentarios
   WHERE quem = v_quem AND estado = 'aberto' AND tipo = v_tipo AND motivo = v_motivo
     AND COALESCE(nome, '') = COALESCE(v_nome, '') AND ano IS NOT DISTINCT FROM p_ano
     AND COALESCE(texto, '') = COALESCE(v_texto, '') AND COALESCE(link, '') = COALESCE(v_link, '')
     AND quando > now() - interval '10 minutes'
   ORDER BY quando DESC LIMIT 1;
  IF v_id IS NOT NULL THEN
    RETURN jsonb_build_object('ok', true, 'id', v_id, 'repetido', true);
  END IF;

  -- O vinho do catálogo: a mesma colheita primeiro, senão outra do mesmo
  -- vinho (a de uma carta, a de uma irmã) — o admin vê qual é.
  IF v_tipo = 'vinho' THEN
    v_vid := COALESCE(winecatalog.achar(v_nome, v_prod, p_ano, true,  NULL, p_cor),
                      winecatalog.achar(v_nome, v_prod, p_ano, false, NULL, p_cor));
    IF v_vid IS NOT NULL THEN
      SELECT * INTO r FROM winecatalog.vinhos WHERE id = v_vid;
      IF cardinality(v_campos) > 0 THEN
        SELECT jsonb_object_agg(c, CASE c WHEN 'nome' THEN to_jsonb(r.nome)
                                          WHEN 'produtor' THEN to_jsonb(r.produtor)
                                          WHEN 'ano' THEN to_jsonb(r.ano)
                                          ELSE r.ficha -> c END)
          INTO v_cat FROM unnest(v_campos) c;
      END IF;
    END IF;
  END IF;

  INSERT INTO winecatalog.comentarios
    (tipo, motivo, texto, link, campos, valores_deles, valores_catalogo,
     vinho_id, chave, nome, produtor, ano, cor, app, quem)
  VALUES
    (v_tipo, v_motivo, v_texto, v_link, v_campos,
     CASE WHEN v_tipo = 'vinho' THEN p_valores_deles END, v_cat,
     r.id, r.chave, CASE WHEN v_tipo = 'vinho' THEN v_nome END,
     CASE WHEN v_tipo = 'vinho' THEN v_prod ELSE '' END,
     CASE WHEN v_tipo = 'vinho' THEN p_ano END,
     CASE WHEN v_tipo = 'vinho' THEN NULLIF(btrim(COALESCE(p_cor, '')), '') END,
     left(COALESCE(NULLIF(btrim(COALESCE(p_app, '')), ''), 'garrafeira'), 20), v_quem)
  RETURNING id INTO v_id;

  RETURN jsonb_build_object('ok', true, 'id', v_id, 'noCatalogo', r.id IS NOT NULL);
END;
$$;


-- ---------------------------------------------------------------------
-- O LADO DO ADMIN — na app (Alertas, com o JWT dele) e no painel do PC
-- (service_role, sem email). O portão está dentro de cada uma.
-- ---------------------------------------------------------------------

-- A lista. O vinho do catálogo é o de AGORA: um id fundido responde pelo
-- que ficou (uma fusão não pode deixar um comentário órfão), e um vinho que
-- ainda não estava no catálogo quando se escreveu procura-se outra vez —
-- pode ter entrado entretanto. Os valores desses campos AGORA vão ao lado
-- dos de então: vê-se logo se já foi corrigido por outra via.
CREATE OR REPLACE FUNCTION winecatalog.listar_comentarios(
  p_tipo text DEFAULT NULL, p_estado text DEFAULT 'aberto')
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_e   text := COALESCE(NULLIF(btrim(COALESCE(p_estado, '')), ''), 'aberto');
  v_t   text := NULLIF(btrim(COALESCE(p_tipo, '')), '');
  v_res jsonb;
BEGIN
  IF NOT (winecatalog.sou_admin() OR COALESCE(auth.role(), '') = 'service_role') THEN
    RAISE EXCEPTION 'Só o admin do catálogo vê os comentários.';
  END IF;
  -- "Por tratar" são também os que esperam pela resposta de quem escreveu
  -- (`duvida`): não são a vez do admin — e por isso não contam no número —,
  -- mas estão por fechar, e escondê-los era perdê-los de vista.
  WITH t AS MATERIALIZED (
    SELECT * FROM winecatalog.comentarios
     WHERE (v_e = 'todos' OR estado = v_e OR (v_e = 'aberto' AND estado = 'duvida'))
       AND (v_t IS NULL OR tipo = v_t)
     ORDER BY quando DESC LIMIT 200
  ), x AS MATERIALIZED (
    SELECT t.*,
           CASE WHEN t.tipo <> 'vinho' THEN NULL
                WHEN t.vinho_id IS NOT NULL
                  THEN COALESCE((SELECT a.id_para FROM winecatalog.alias a WHERE a.id_de = t.vinho_id), t.vinho_id)
                ELSE COALESCE(winecatalog.achar(t.nome, t.produtor, t.ano, true,  NULL, t.cor),
                              winecatalog.achar(t.nome, t.produtor, t.ano, false, NULL, t.cor))
           END AS vid
      FROM t
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'id', x.id, 'tipo', x.tipo, 'motivo', x.motivo, 'texto', x.texto, 'link', x.link,
           'campos', to_jsonb(x.campos),
           'valoresDeles', x.valores_deles, 'valoresCatalogo', x.valores_catalogo,
           'valoresAgora', CASE WHEN v.id IS NULL OR cardinality(x.campos) = 0 THEN NULL ELSE
             (SELECT jsonb_object_agg(c, CASE c WHEN 'nome' THEN to_jsonb(v.nome)
                                                WHEN 'produtor' THEN to_jsonb(v.produtor)
                                                WHEN 'ano' THEN to_jsonb(v.ano)
                                                ELSE v.ficha -> c END)
                FROM unnest(x.campos) c) END,
           'vinhoId', v.id, 'nomeCatalogo', v.nome, 'produtorCatalogo', v.produtor,
           'anoCatalogo', v.ano,
           'mesmaColheita', CASE WHEN v.id IS NULL THEN NULL ELSE v.ano IS NOT DISTINCT FROM x.ano END,
           'nome', x.nome, 'produtor', x.produtor, 'ano', x.ano, 'cor', x.cor,
           'app', x.app, 'quem', x.quem, 'quando', x.quando,
           'estado', x.estado, 'resposta', x.resposta,
           'fechadoEm', x.fechado_em, 'fechadoPor', x.fechado_por,
           'mensagens', winecatalog.comentario_msgs(x.id, true)
         ) ORDER BY (x.estado = 'aberto') DESC, x.quando DESC), '[]'::jsonb) INTO v_res
    FROM x LEFT JOIN winecatalog.vinhos v ON v.id = x.vid;
  RETURN v_res;
END;
$$;

-- Os números dos dois cartões (e do separador Alertas). A quem não é o
-- admin, zeros — nem erro, que a app pergunta no arranque.
CREATE OR REPLACE FUNCTION winecatalog.contar_comentarios()
  RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE WHEN winecatalog.sou_admin() OR COALESCE(auth.role(), '') = 'service_role'
    THEN jsonb_build_object(
      'vinho',    (SELECT count(*) FROM winecatalog.comentarios WHERE estado = 'aberto' AND tipo = 'vinho'),
      'sugestao', (SELECT count(*) FROM winecatalog.comentarios WHERE estado = 'aberto' AND tipo = 'sugestao'))
    ELSE jsonb_build_object('vinho', 0, 'sugestao', 0) END;
$$;

-- O admin fala: fechar (resolvido/rejeitado), perguntar (`duvida` — a vez
-- passa a quem escreveu; a pergunta é obrigatória) ou reabrir. A resposta ao
-- fechar é o que quem escreveu lê na app dele — por isso se pede. Reabrir
-- não é uma fala (é o admin a arrumar a lista): não avisa ninguém e apaga a
-- resposta, que já não responde a nada. Perguntar ou fechar deixa o aviso
-- por ler do lado de quem escreveu e fica como uma fala na conversa — é
-- dessa linha que sai o push.
CREATE OR REPLACE FUNCTION winecatalog.responder_comentario(
  p_id bigint, p_estado text DEFAULT 'resolvido', p_resposta text DEFAULT NULL,
  p_quem text DEFAULT NULL)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_e     text := COALESCE(NULLIF(btrim(COALESCE(p_estado, '')), ''), 'resolvido');
  v_texto text := NULLIF(left(btrim(COALESCE(p_resposta, '')), 1000), '');
  v_quem  text;
BEGIN
  IF NOT (winecatalog.sou_admin() OR COALESCE(auth.role(), '') = 'service_role') THEN
    RAISE EXCEPTION 'Só o admin do catálogo trata dos comentários.';
  END IF;
  IF v_e NOT IN ('aberto', 'duvida', 'resolvido', 'rejeitado') THEN
    RAISE EXCEPTION 'Estado inválido.';
  END IF;
  IF v_e = 'duvida' AND v_texto IS NULL THEN
    RAISE EXCEPTION 'Escreve a pergunta para quem fez o comentário.';
  END IF;
  v_quem := COALESCE(NULLIF(lower(COALESCE(auth.email(), '')), ''),
                     NULLIF(btrim(COALESCE(p_quem, '')), ''), 'painel do PC (admin)');
  UPDATE winecatalog.comentarios
     SET estado        = v_e,
         resposta      = CASE WHEN v_e IN ('resolvido', 'rejeitado') THEN v_texto END,
         fechado_em    = CASE WHEN v_e IN ('resolvido', 'rejeitado') THEN now() END,
         fechado_por   = CASE WHEN v_e IN ('resolvido', 'rejeitado') THEN left(v_quem, 200) END,
         por_ler_autor = CASE WHEN v_e = 'aberto' THEN por_ler_autor ELSE true END
   WHERE id = p_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Comentário não encontrado.'; END IF;
  IF v_e <> 'aberto' THEN
    INSERT INTO winecatalog.comentarios_msgs (comentario_id, de, estado, texto, quem)
    VALUES (p_id, 'admin', v_e, v_texto, left(v_quem, 200));
  END IF;
  RETURN jsonb_build_object('ok', true, 'estado', v_e);
END;
$$;


-- ---------------------------------------------------------------------
-- O LADO DE QUEM ESCREVEU — os meus, com o estado e a resposta. Só os da
-- própria pessoa (o `quem` sai do JWT); sem sessão, lista vazia. Não diz
-- QUEM do lado do admin tratou (`fechado_por`): é o admin, e basta.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.meus_comentarios(p_limite integer DEFAULT 50)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_quem text := lower(COALESCE(auth.email(), ''));
  v_res  jsonb;
BEGIN
  IF v_quem = '' THEN RETURN '[]'::jsonb; END IF;
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'id', t.id, 'tipo', t.tipo, 'motivo', t.motivo, 'texto', t.texto, 'link', t.link,
           'campos', to_jsonb(t.campos), 'nome', t.nome, 'produtor', t.produtor, 'ano', t.ano,
           'app', t.app, 'quando', t.quando, 'estado', t.estado, 'resposta', t.resposta,
           'fechadoEm', t.fechado_em, 'porLer', t.por_ler_autor,
           'mensagens', winecatalog.comentario_msgs(t.id, false)
         ) ORDER BY (t.estado = 'duvida') DESC, t.quando DESC), '[]'::jsonb) INTO v_res
    FROM (SELECT * FROM winecatalog.comentarios
           WHERE quem = v_quem
           ORDER BY quando DESC
           LIMIT LEAST(GREATEST(COALESCE(p_limite, 50), 1), 200)) t;
  RETURN v_res;
END;
$$;

-- Quem escreveu responde (a uma dúvida do admin, ou para acrescentar
-- alguma coisa). A vez volta ao admin: o comentário passa a `aberto`,
-- mesmo que já estivesse fechado — "continua mal" depois de "tratado" é
-- exatamente o que tem de voltar à lista. Só a própria pessoa (o `quem` do
-- JWT), e com uma trava contra conversas sem fim.
CREATE OR REPLACE FUNCTION winecatalog.comentario_do_autor(p_id bigint, p_texto text)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_quem  text := lower(COALESCE(auth.email(), ''));
  v_texto text := NULLIF(left(btrim(COALESCE(p_texto, '')), 2000), '');
BEGIN
  IF v_quem = '' THEN RAISE EXCEPTION 'Precisa de sessão iniciada.'; END IF;
  IF COALESCE(length(v_texto), 0) < 2 THEN RAISE EXCEPTION 'Escreve a resposta.'; END IF;
  PERFORM 1 FROM winecatalog.comentarios WHERE id = p_id AND quem = v_quem FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Comentário não encontrado.'; END IF;
  IF (SELECT count(*) FROM winecatalog.comentarios_msgs
       WHERE comentario_id = p_id AND de = 'autor' AND quando > now() - interval '1 day') >= 10 THEN
    RAISE EXCEPTION 'Já escreveste muito neste comentário hoje — espera pela resposta do admin.';
  END IF;
  UPDATE winecatalog.comentarios
     SET estado = 'aberto', resposta = NULL, fechado_em = NULL, fechado_por = NULL,
         por_ler_autor = false
   WHERE id = p_id;
  INSERT INTO winecatalog.comentarios_msgs (comentario_id, de, estado, texto, quem)
  VALUES (p_id, 'autor', 'aberto', v_texto, v_quem);
  RETURN jsonb_build_object('ok', true, 'estado', 'aberto');
END;
$$;

-- A pessoa abriu a lista: o que o admin disse deixa de estar por ler.
CREATE OR REPLACE FUNCTION winecatalog.comentarios_marcar_lidos()
  RETURNS integer LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_n integer;
BEGIN
  UPDATE winecatalog.comentarios SET por_ler_autor = false
   WHERE quem = lower(COALESCE(auth.email(), '')) AND por_ler_autor;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;

-- Os avisos de quem está com a app aberta, numa ida: o que o admin lhe
-- disse e ainda não leu, as dúvidas à espera da resposta dele e — só se for
-- o admin do catálogo — os comentários e sugestões por tratar. É o que a
-- Garrafeira mostra à entrada (e no ⚙️), e é a rede por baixo do push: um
-- push que não chegue não perde nada.
CREATE OR REPLACE FUNCTION winecatalog.meus_avisos()
  RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT jsonb_build_object(
    'porLer',  (SELECT count(*) FROM winecatalog.comentarios
                 WHERE quem = lower(COALESCE(auth.email(), '')) AND por_ler_autor),
    'duvidas', (SELECT count(*) FROM winecatalog.comentarios
                 WHERE quem = lower(COALESCE(auth.email(), '')) AND estado = 'duvida'),
    -- os dois de cima juntos, sem contar duas vezes o mesmo comentário (uma
    -- dúvida por ler é as duas coisas): é o número do ⚙️
    'atencao', (SELECT count(*) FROM winecatalog.comentarios
                 WHERE quem = lower(COALESCE(auth.email(), ''))
                   AND (por_ler_autor OR estado = 'duvida')),
    'admin',   CASE WHEN winecatalog.sou_admin() THEN winecatalog.contar_comentarios() END);
$$;


-- =====================================================================
-- GRANTS — a postura do resto do catálogo. A tabela não tem grant nenhum a
-- quem tem login; chega-se lá pelas funções.
-- =====================================================================
REVOKE ALL ON winecatalog.comentarios FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.comentarios TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA winecatalog TO service_role;

-- Escrever: só pelas portas das apps (SECURITY DEFINER, que a alcançam como
-- donas) e pela service_role. Aberta a quem tem login, qualquer pessoa
-- escrevia `p_valores_deles` à mão.
REVOKE ALL ON FUNCTION winecatalog.comentar(text, text, text, text, text, integer, text, text[], jsonb, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.comentar(text, text, text, text, text, integer, text, text[], jsonb, text, text)
  TO service_role;

-- O admin (na app) e o painel do PC; a confirmação de quem é está dentro.
REVOKE ALL ON FUNCTION winecatalog.listar_comentarios(text, text)                  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.contar_comentarios()                            FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.responder_comentario(bigint, text, text, text)  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.listar_comentarios(text, text)                 TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION winecatalog.contar_comentarios()                           TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION winecatalog.responder_comentario(bigint, text, text, text) TO authenticated, service_role;

-- Os meus: só as linhas da própria pessoa.
REVOKE ALL ON FUNCTION winecatalog.meus_comentarios(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.meus_comentarios(integer) TO authenticated;

-- A conversa. A tabela, como a dos comentários, só pela service_role e
-- pelas funções. Responder, marcar lidos e os avisos só mexem nas linhas
-- da própria pessoa; a `comentario_msgs` é chamada de dentro das outras.
REVOKE ALL ON winecatalog.comentarios_msgs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.comentarios_msgs TO service_role;
REVOKE ALL ON FUNCTION winecatalog.comentario_msgs(bigint, boolean)      FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.comentario_do_autor(bigint, text)     FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.comentarios_marcar_lidos()            FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.meus_avisos()                         FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.comentario_msgs(bigint, boolean)   TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.comentario_do_autor(bigint, text)  TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.comentarios_marcar_lidos()         TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.meus_avisos()                      TO authenticated;

-- Confirmar (a `comentar` só postgres e service_role; as outras sem anon):
-- SELECT p.proname,
--        has_function_privilege('authenticated', p.oid, 'EXECUTE') AS auth,
--        has_function_privilege('anon',          p.oid, 'EXECUTE') AS anon
--   FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--  WHERE n.nspname = 'winecatalog' AND p.proname LIKE '%comenta%';
