-- =====================================================================
-- WineCatalog — CURADORIA: corrigir, pesquisar, comparar, reportar
--
-- Correr DEPOIS de `catalogo.sql` (precisa da `winecatalog.juntar`, da
-- `achar` e da `forca` já com as origens novas) e ANTES de `policies.sql`.
--
-- O QUE ISTO ACRESCENTA, e porquê.
--
-- O catálogo tinha um ecrã que MOSTRAVA e não deixava MEXER. Isso estava
-- certo enquanto ele era só o depósito do que as outras duas apps
-- escreviam — mas um catálogo que se lê e não se corrige é um catálogo
-- onde um erro fica para sempre, e a ser lido pelas três apps todos os
-- dias. Daqui saem quatro coisas:
--
--   · EDITAR (`editar`) — o admin corrige um campo à mão. A força 4 do
--     `catalogo-admin` é o que faz isto valer alguma coisa: ver o
--     comentário da `winecatalog.forca` em `catalogo.sql`.
--   · PESQUISAR (`pesquisa_criar`/`pesquisa_ver` + a Edge Function
--     `catalogo-info`) — mandar uma pesquisa Google a sério para um vinho
--     do catálogo, sem ter de passar por uma garrafeira.
--   · COMPARAR (`comparar`) — a Garrafeira pergunta "o que é que o
--     catálogo sabe deste vinho que é diferente do que eu tenho?". É a
--     única função deste schema aberta a QUALQUER pessoa com login, e o
--     porquê está escrito ao lado dela.
--   · REPORTAR (`reportar` + `listar_reportes`/`resolver_reporte`) — quem
--     vê um número errado na sua garrafeira avisa o admin do catálogo em
--     vez de corrigir só para si e o erro ficar lá para os outros.
-- =====================================================================


-- =====================================================================
-- 1. AS TABELAS
-- =====================================================================

-- ---------------------------------------------------------------------
-- PESQUISAS — o trabalho assíncrono da `catalogo-info`
--
-- Mesma arquitetura da `sugerir-vinho` da WineSelection, e pela mesma
-- razão, que já foi paga lá: uma pesquisa com grounding pode passar de um
-- minuto, e um pedido HTTP à espera desse tempo todo morre assim que o
-- telemóvel bloqueia o ecrã. Por isso a função responde já com
-- `{estado:'pendente'}` e fecha a linha depois, e o browser sonda.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.pesquisas (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  vinho_id   bigint NOT NULL,
  quem       text NOT NULL,
  estado     text NOT NULL DEFAULT 'pendente',  -- pendente | concluido | erro
  resultado  jsonb,
  erro       text,
  criado_em  timestamptz NOT NULL DEFAULT now(),
  fechado_em timestamptz,
  CONSTRAINT pesquisas_pkey PRIMARY KEY (id),
  CONSTRAINT pesquisas_estado_chk CHECK (estado IN ('pendente','concluido','erro'))
);
CREATE INDEX IF NOT EXISTS pesquisas_vinho_idx ON winecatalog.pesquisas (vinho_id, criado_em DESC);

-- ---------------------------------------------------------------------
-- REPORTES — "isto aqui está errado"
--
-- Guarda-se o valor DOS DOIS LADOS no momento em que alguém reportou, e
-- não só um apontador para o campo: o catálogo muda, e um alerta que diga
-- apenas "o preço do Papa Figos está mal" é inútil daqui a três semanas.
-- Com os dois valores lá dentro, o admin vê exatamente o que a pessoa viu.
--
-- A `chave` vai ao lado do `vinho_id` de propósito: uma fusão muda o id a
-- que o vinho responde, e um reporte órfão é um reporte que ninguém trata.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.reportes (
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  vinho_id     bigint,
  chave        text,
  nome         text NOT NULL,
  produtor     text NOT NULL DEFAULT '',
  ano          integer,
  campo        text NOT NULL,
  valor_catalogo jsonb,      -- o que estava CÁ quando reportaram
  valor_deles    jsonb,      -- o que a pessoa tem do lado dela
  nota         text,
  app          text NOT NULL DEFAULT 'garrafeira',
  quem         text NOT NULL,
  quando       timestamptz NOT NULL DEFAULT now(),
  estado       text NOT NULL DEFAULT 'aberto',   -- aberto | resolvido | rejeitado
  resposta     text,
  fechado_em   timestamptz,
  fechado_por  text,
  CONSTRAINT reportes_pkey PRIMARY KEY (id),
  CONSTRAINT reportes_estado_chk CHECK (estado IN ('aberto','resolvido','rejeitado'))
);
-- Um alerta aberto por pessoa, vinho e campo. Sem isto, carregar duas
-- vezes no botão enche o ecrã do admin com a mesma queixa — e um ecrã
-- cheio de repetições é um ecrã que se deixa de abrir.
CREATE UNIQUE INDEX IF NOT EXISTS reportes_um_aberto_idx
  ON winecatalog.reportes (quem, COALESCE(chave,''), campo)
  WHERE estado = 'aberto';
CREATE INDEX IF NOT EXISTS reportes_abertos_idx ON winecatalog.reportes (quando DESC)
  WHERE estado = 'aberto';

ALTER TABLE winecatalog.pesquisas ENABLE ROW LEVEL SECURITY;
ALTER TABLE winecatalog.reportes  ENABLE ROW LEVEL SECURITY;


-- =====================================================================
-- 2. COMPARAR DOIS VALORES — sem inventar diferenças
--
-- "Tinto" e "tinto" não são uma divergência. "13.5" e "13.50" também não.
-- E as castas são um CONJUNTO: a mesma lista por outra ordem é a mesma
-- lista. Sem isto, a marca da Garrafeira aparecia em metade dos campos de
-- toda a gente no primeiro dia e ninguém voltava a olhar para ela — que é
-- exatamente o erro que a lista de duplicados já cometeu uma vez.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.texto_norm(p text)
  RETURNS text LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT btrim(regexp_replace(
           lower(regexp_replace(normalize(COALESCE(p, ''), NFD),
                                U&'[\0300-\036F]', '', 'g')),
           '\s+', ' ', 'g'));
$$;

CREATE OR REPLACE FUNCTION winecatalog.igual(a jsonb, b jsonb)
  RETURNS boolean LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE
    WHEN a IS NULL AND b IS NULL THEN true
    WHEN a IS NULL OR  b IS NULL THEN false
    WHEN jsonb_typeof(a) = 'null' AND jsonb_typeof(b) = 'null' THEN true
    WHEN jsonb_typeof(a) = 'null' OR  jsonb_typeof(b) = 'null' THEN false
    -- números: 13.5 = 13.50, e um número escrito como texto ("13.5") é o
    -- mesmo número — as apps não são todas igualmente cuidadosas com isso
    WHEN (a #>> '{}') ~ '^-?[0-9]+(\.[0-9]+)?$'
     AND (b #>> '{}') ~ '^-?[0-9]+(\.[0-9]+)?$'
      THEN (a #>> '{}')::numeric = (b #>> '{}')::numeric
    -- listas (castas): conjunto, não sequência
    WHEN jsonb_typeof(a) = 'array' AND jsonb_typeof(b) = 'array'
      THEN (SELECT COALESCE(array_agg(DISTINCT winecatalog.texto_norm(x #>> '{}')
                                      ORDER BY winecatalog.texto_norm(x #>> '{}')), '{}')
              FROM jsonb_array_elements(a) x)
         = (SELECT COALESCE(array_agg(DISTINCT winecatalog.texto_norm(y #>> '{}')
                                      ORDER BY winecatalog.texto_norm(y #>> '{}')), '{}')
              FROM jsonb_array_elements(b) y)
    WHEN jsonb_typeof(a) = 'array' OR jsonb_typeof(b) = 'array' THEN false
    ELSE winecatalog.texto_norm(a #>> '{}') = winecatalog.texto_norm(b #>> '{}')
  END;
$$;

-- Um valor "vazio" não é uma opinião diferente, é a ausência de uma. Tem
-- de ser a MESMA regra da `juntar` (que recusa '', [], {} e null), senão a
-- Garrafeira marcava como divergência um campo que o catálogo nem sequer
-- aceitaria escrever.
CREATE OR REPLACE FUNCTION winecatalog.vazio(v jsonb)
  RETURNS boolean LANGUAGE sql IMMUTABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT v IS NULL OR jsonb_typeof(v) = 'null'
      OR v = '""'::jsonb OR v = '[]'::jsonb OR v = '{}'::jsonb
      OR (jsonb_typeof(v) = 'string' AND btrim(v #>> '{}') = '');
$$;


-- =====================================================================
-- 3. EDITAR — o admin corrige o catálogo
--
-- `p_campos` é `{campo: valor}`. Um valor JSON `null` APAGA o campo (e a
-- proveniência dele), e isso é diferente de o deixar de fora: quem não
-- vem no objeto fica como estava.
--
-- APAGAR NÃO FIXA NADA, e é preciso dizê-lo no ecrã: um campo apagado
-- fica livre para a próxima escrita de qualquer origem o voltar a
-- preencher — inclusive com o mesmo valor errado, se ele vier de uma
-- garrafeira que o tem escrito. Para fixar, CORRIGE-SE (força 4), não se
-- apaga.
--
-- A identidade (nome/produtor/ano) também se pode corrigir, e é o pedaço
-- perigoso desta função: mexe na CHAVE, que é o que faz duas linhas serem
-- a mesma. Se a chave nova já for de outra linha, isto RECUSA e manda usar
-- o ecrã de duplicados — juntar duas linhas é a `fundir`, que é
-- reversível; um UPDATE à socapa não seria.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.editar(
  p_id bigint,
  p_campos jsonb DEFAULT '{}'::jsonb,
  p_nome text DEFAULT NULL,
  p_produtor text DEFAULT NULL,
  p_ano integer DEFAULT NULL,
  p_mexer_identidade boolean DEFAULT false
) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  r         winecatalog.vinhos%ROWTYPE;
  v_ficha   jsonb;
  v_origens jsonb;
  v_antes   jsonb := '{}'::jsonb;
  v_mudou   integer := 0;
  v_apagou  integer := 0;
  k         text;
  v         jsonb;
  v_f       integer;
  v_nome    text;
  v_prod    text;
  v_ano     integer;
  v_chave   text;
  v_outro   bigint;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode corrigir uma linha.';
  END IF;

  SELECT * INTO r FROM winecatalog.vinhos WHERE id = p_id FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'Linha não encontrada.'; END IF;
  IF EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = r.id) THEN
    RAISE EXCEPTION 'Essa linha foi fundida noutra — corrige a linha que ficou.';
  END IF;

  v_ficha   := r.ficha;
  v_origens := r.origens;

  IF p_campos IS NOT NULL AND jsonb_typeof(p_campos) = 'object' THEN
    FOR k, v IN SELECT key, value FROM jsonb_each(p_campos) LOOP
      -- Um nome de campo é uma chave de jsonb, não texto livre: sem isto,
      -- um engano na app enchia a ficha de lixo que ninguém sabia apagar.
      CONTINUE WHEN k !~ '^[a-z][a-z0-9_]{0,39}$';
      -- "DOURO"/"Península de Setúbal" não entram nem pela mão do admin —
      -- ver `winecatalog.normalizar_regiao`.
      IF k = 'regiao' AND jsonb_typeof(v) = 'string' THEN
        v := to_jsonb(winecatalog.normalizar_regiao(v #>> '{}'));
      END IF;
      -- Nada muda -> nada se escreve. Evita carimbar `catalogo-admin` (e a
      -- força 4) em cima de campos que o admin só olhou e não tocou:
      -- guardar o formulário inteiro não pode valer o mesmo que corrigir.
      CONTINUE WHEN winecatalog.igual(v_ficha -> k, v)
                    AND (v_ficha ? k) = NOT winecatalog.vazio(v);

      v_antes := v_antes || jsonb_build_object(k, jsonb_build_object(
        'valor',  v_ficha -> k, 'origem', v_origens -> k));

      IF winecatalog.vazio(v) THEN
        v_ficha   := v_ficha   - k;
        v_origens := v_origens - k;
        v_apagou  := v_apagou + 1;
      ELSE
        v_f := winecatalog.forca('catalogo-admin', k);
        v_ficha   := v_ficha   || jsonb_build_object(k, v);
        v_origens := v_origens || jsonb_build_object(
          k, jsonb_build_object('o', 'catalogo-admin', 'f', v_f, 'em', now()));
        v_mudou := v_mudou + 1;
      END IF;
    END LOOP;
  END IF;

  v_nome := COALESCE(NULLIF(btrim(COALESCE(p_nome, '')), ''), r.nome);
  v_prod := COALESCE(p_produtor, r.produtor);
  v_ano  := CASE WHEN p_mexer_identidade THEN p_ano ELSE COALESCE(p_ano, r.ano) END;

  IF p_mexer_identidade THEN
    v_chave := winecatalog.chave(v_nome, v_prod, v_ano);
    IF v_chave <> r.chave THEN
      SELECT id INTO v_outro FROM winecatalog.vinhos WHERE chave = v_chave AND id <> r.id;
      IF v_outro IS NOT NULL THEN
        RAISE EXCEPTION 'Com esse nome esta linha passa a ser a mesma que a #% — junta-as no ecrã de Duplicados em vez de a reescrever aqui.', v_outro;
      END IF;
      IF winecatalog.chave_base(v_nome, v_prod) = '' THEN
        RAISE EXCEPTION 'Esse nome não deixa identidade nenhuma — ficava a casar com tudo.';
      END IF;
    END IF;
    UPDATE winecatalog.vinhos SET
      nome = v_nome, produtor = COALESCE(v_prod,''), ano = v_ano,
      chave      = v_chave,
      chave_base = winecatalog.chave_base(v_nome, v_prod),
      chave_nome = winecatalog.chave_nome(v_nome, v_ano),
      base_nome  = winecatalog.base_nome(v_nome)
    WHERE id = r.id;
  END IF;

  UPDATE winecatalog.vinhos
     SET ficha = v_ficha, origens = v_origens,
         atualizado_em = CASE WHEN v_mudou + v_apagou > 0 THEN now() ELSE atualizado_em END
   WHERE id = r.id;

  -- O `origens` diz de onde veio cada campo, mas não guarda o valor
  -- ANTERIOR nem quem o mudou. Uma correção à mão é a única escrita que
  -- ninguém pode reconstituir a partir de mais lado nenhum — por isso
  -- fica aqui, com o antes e o depois.
  IF v_mudou + v_apagou > 0 OR p_mexer_identidade THEN
    INSERT INTO winecatalog.sync_log (origem, acao, estado, quem, detalhe)
    VALUES ('app', 'editar', 'ok', auth.email(), jsonb_build_object(
      'vinho_id', r.id, 'campos', v_mudou, 'apagados', v_apagou,
      'antes', v_antes, 'depois', p_campos,
      'identidade', CASE WHEN p_mexer_identidade
        THEN jsonb_build_object('nome', v_nome, 'produtor', v_prod, 'ano', v_ano) END));
  END IF;

  RETURN jsonb_build_object('ok', true, 'campos', v_mudou, 'apagados', v_apagou);
END;
$$;


-- =====================================================================
-- 3B. CRIAR — um vinho que ninguém tem, do zero
--
-- Metade do §4.4 do documento de arranque que ainda faltava (ver o
-- CLAUDE.md, "O que falta"): a `catalogo-info` já sabia pesquisar UMA
-- linha que já existe; esta função é o que falta para ela nascer. Sem
-- isto, um vinho que nenhuma garrafeira tem e nenhuma carta leu ainda não
-- tinha ONDE nascer no catálogo — o `juntar` cria linhas, mas só a
-- service_role lhe chega (é para as Edge Functions, a reboque de um
-- trabalho que a pessoa já pediu para si); aqui é uma PESSOA, do ecrã, a
-- pedir a linha diretamente, e por isso a mesma regra do resto: só o
-- admin do catálogo.
--
-- Os campos entram com a MESMA força de um `editar` (`catalogo-admin`):
-- 4 no que está no rótulo, 3 na nota/preço/imagem — ninguém os sabe por
-- ser admin, e uma pesquisa a sério fresca ainda os deve poder actualizar.
-- É o mesmo campo `p_campos` que a `editar` já usa, para o ecrã poder
-- reaproveitar o mesmo formulário (e ler uma fotografia do rótulo para o
-- pré-preencher, do lado da app — esta função nunca vê imagem nenhuma).
--
-- NÃO deixa nascer uma SEGUNDA linha do mesmo vinho: `achar` olha às
-- DUAS chaves (nome+produtor e só nome), dos dois lados, exatamente como
-- o `juntar` faz antes de escrever — se já existir, recusa e diz qual é,
-- para o ecrã abrir essa em vez de duplicar.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.criar(
  p_nome text,
  p_produtor text DEFAULT '',
  p_ano integer DEFAULT NULL,
  p_campos jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_nome    text := btrim(COALESCE(p_nome, ''));
  v_prod    text := COALESCE(p_produtor, '');
  v_base    text;
  v_chave   text;
  v_cnome   text;
  v_bnome   text;
  v_existe  bigint;
  v_id      bigint;
  v_ficha   jsonb := '{}'::jsonb;
  v_origens jsonb := '{}'::jsonb;
  k text; v jsonb; v_f integer;
BEGIN
  -- O batch do PC (service_role) também cria — pela `vivino_novo`, o
  -- "Vinho novo" do painel do vinhos.bat, que é o admin ao teclado.
  IF NOT (winecatalog.sou_admin() OR COALESCE(auth.role(), '') = 'service_role') THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode criar uma linha.';
  END IF;
  IF v_nome = '' THEN
    RAISE EXCEPTION 'Um vinho novo precisa de um nome.';
  END IF;

  v_base := winecatalog.chave_base(v_nome, v_prod);
  IF v_base = '' THEN
    RAISE EXCEPTION 'Esse nome não deixa identidade nenhuma — não distingue este vinho de mais nenhum.';
  END IF;

  -- A MESMA pergunta que o `juntar` faz antes de escrever: se este vinho
  -- (por qualquer uma das duas chaves) já tiver linha nesta colheita, não
  -- nasce uma segunda — abre-se a que já existe.
  v_existe := winecatalog.achar(v_nome, v_prod, p_ano, true);
  IF v_existe IS NOT NULL THEN
    RAISE EXCEPTION 'Já existe uma linha para este vinho e colheita — é a #%. Abre-a em vez de criar outra.', v_existe;
  END IF;

  v_chave := winecatalog.chave(v_nome, v_prod, p_ano);
  v_cnome := winecatalog.chave_nome(v_nome, p_ano);
  v_bnome := winecatalog.base_nome(v_nome);

  IF p_campos IS NOT NULL AND jsonb_typeof(p_campos) = 'object' THEN
    FOR k, v IN SELECT key, value FROM jsonb_each(p_campos) LOOP
      CONTINUE WHEN k !~ '^[a-z][a-z0-9_]{0,39}$';
      -- "DOURO"/"Península de Setúbal" não nascem assim nem num vinho novo
      -- — ver `winecatalog.normalizar_regiao`.
      IF k = 'regiao' AND jsonb_typeof(v) = 'string' THEN
        v := to_jsonb(winecatalog.normalizar_regiao(v #>> '{}'));
      END IF;
      CONTINUE WHEN winecatalog.vazio(v);
      v_f := winecatalog.forca('catalogo-admin', k);
      v_ficha   := v_ficha   || jsonb_build_object(k, v);
      v_origens := v_origens || jsonb_build_object(
        k, jsonb_build_object('o', 'catalogo-admin', 'f', v_f, 'em', now()));
    END LOOP;
  END IF;

  BEGIN
    INSERT INTO winecatalog.vinhos
      (chave, chave_base, chave_nome, base_nome, nome, produtor, ano, ficha, origens)
    VALUES
      (v_chave, v_base, v_cnome, v_bnome, v_nome, v_prod, p_ano, v_ficha, v_origens)
    RETURNING id INTO v_id;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'Já existe uma linha com essa identidade — outra escrita chegou primeiro.';
  END;

  INSERT INTO winecatalog.sync_log (origem, acao, estado, quem, detalhe)
  VALUES ('app', 'criar', 'ok', auth.email(), jsonb_build_object(
    'vinho_id', v_id, 'nome', v_nome, 'produtor', v_prod, 'ano', p_ano,
    'campos', (SELECT count(*) FROM jsonb_object_keys(v_ficha))));

  RETURN jsonb_build_object('ok', true, 'id', v_id);
END;
$$;


-- =====================================================================
-- 4. PESQUISAR — o pedido, e a espera
--
-- `pesquisa_criar` só CRIA a linha; quem faz o trabalho é a Edge Function
-- `catalogo-info`, que a fecha com a service role. A autorização fica toda
-- aqui, no SQL, onde se testa — e a função lá fora volta a confirmá-la
-- antes de gastar um cêntimo.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.pesquisa_criar(p_vinho_id bigint)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  r     winecatalog.vinhos%ROWTYPE;
  v_id  bigint;
  v_ja  bigint;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode mandar pesquisar.';
  END IF;
  SELECT * INTO r FROM winecatalog.vinhos WHERE id = p_vinho_id;
  IF r.id IS NULL THEN RAISE EXCEPTION 'Linha não encontrada.'; END IF;

  -- Duas pesquisas a correr ao mesmo tempo para o mesmo vinho são duas
  -- contas pelo mesmo trabalho. Devolve-se a que já está a andar.
  SELECT id INTO v_ja FROM winecatalog.pesquisas
   WHERE vinho_id = r.id AND estado = 'pendente'
     AND criado_em > now() - interval '5 minutes'
   ORDER BY criado_em DESC LIMIT 1;
  IF v_ja IS NOT NULL THEN
    RETURN jsonb_build_object('id', v_ja, 'estado', 'pendente', 'jaAndava', true);
  END IF;

  INSERT INTO winecatalog.pesquisas (vinho_id, quem)
  VALUES (r.id, COALESCE(auth.email(), ''))
  RETURNING id INTO v_id;

  RETURN jsonb_build_object('id', v_id, 'estado', 'pendente',
    'nome', r.nome, 'produtor', r.produtor, 'ano', r.ano);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.pesquisa_ver(p_id bigint)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE p winecatalog.pesquisas%ROWTYPE;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Sem acesso.';
  END IF;
  SELECT * INTO p FROM winecatalog.pesquisas WHERE id = p_id;
  IF p.id IS NULL THEN RETURN NULL; END IF;
  RETURN jsonb_build_object(
    'id', p.id, 'vinhoId', p.vinho_id, 'estado', p.estado,
    'resultado', p.resultado, 'erro', p.erro,
    'criadoEm', p.criado_em, 'fechadoEm', p.fechado_em);
END;
$$;


-- =====================================================================
-- 4B. REVER ANTES DE GRAVAR (26/09/2026) — o mesmo desenho da Garrafeira
--
-- Até aqui a pesquisa GRAVAVA sozinha (a `juntar`, pela força) e só depois
-- dizia o que tinha entrado. O dono das apps: "nunca percebo se fica
-- automaticamente guardado, se tenho que ir a algum lado, o que é que foi
-- atualizado, se posso aceitar ou não". Agora a `catalogo-info`, chamada
-- com `rever:true`, fecha a pesquisa com as PROPOSTAS (o valor encontrado
-- e o que estava no catálogo nesse momento) e não escreve nada; o admin vê
-- campo a campo e só o que ele marcar entra, por aqui.
--
-- O que entra, entra como `catalogo-pesquisa` (força 3), por cima do que lá
-- estava seja qual for a força: a força existe para decidir quando NINGUÉM
-- olha, e aqui o admin olhou — viu o valor de agora e a origem dele ao lado
-- e escolheu. A origem continua a dizer que veio de uma pesquisa, não de
-- uma correção à mão (invariante 9): quem abrir a ficha tem de saber isso.
--
-- Os VALORES vêm da linha da pesquisa, nunca do browser: a app só diz
-- QUAIS campos. É o que a Edge Function já validou e normalizou — um
-- atalho que aceitasse valores daqui era outra porta para dentro da ficha.
--
-- Um campo que MUDOU desde a pesquisa não se toca: o admin decidiu contra
-- o valor que viu, não contra o que lá está agora (uma corrida do script
-- entretanto, outra pesquisa). A mesma regra do "Repor" do histórico.
--
-- O PRODUTOR é identidade (mexe na `chave`): vai pela `editar` com o
-- interruptor de identidade, que recusa se passar a ser a mesma linha que
-- outra — nesse caso o resto grava na mesma e o erro volta para o ecrã.
--
-- `p_campos` vazio DESCARTA: a pesquisa deixa de ficar à espera na ficha.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.pesquisa_aplicar(p_id bigint, p_campos text[])
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  p          winecatalog.pesquisas%ROWTYPE;
  r          winecatalog.vinhos%ROWTYPE;
  v_ficha    jsonb;
  v_origens  jsonb;
  v_fontes   jsonb;
  v_entrou   jsonb := '[]'::jsonb;
  v_iguais   jsonb := '[]'::jsonb;
  v_mudaram  jsonb := '[]'::jsonb;
  v_prop     jsonb;
  k          text;
  v          jsonb;
  v_atual    jsonb;
  v_prod     text;
  v_prod_ok  boolean := false;
  v_prod_err text;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo pode guardar uma pesquisa.';
  END IF;
  SELECT * INTO p FROM winecatalog.pesquisas WHERE id = p_id FOR UPDATE;
  IF p.id IS NULL THEN RAISE EXCEPTION 'Pesquisa não encontrada.'; END IF;
  IF p.estado <> 'concluido' OR COALESCE(p.resultado ->> 'rever', '') <> 'true' THEN
    RAISE EXCEPTION 'Esta pesquisa não está à espera de revisão.';
  END IF;
  IF p.resultado ? 'aplicadoEm' THEN
    RAISE EXCEPTION 'Esta pesquisa já foi guardada (ou descartada). Pesquisa outra vez se quiseres mudar mais alguma coisa.';
  END IF;
  -- A proposta foi procurada pelo nome da linha que entretanto se fundiu:
  -- a mesma regra da `vivino_resolver` — pesquisa-se outra vez o que ficou.
  IF EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = p.vinho_id) THEN
    RAISE EXCEPTION 'Este vinho foi fundido noutro depois da pesquisa — pesquisa outra vez no que ficou.';
  END IF;

  SELECT * INTO r FROM winecatalog.vinhos WHERE id = p.vinho_id FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'A linha do catálogo desapareceu.'; END IF;
  v_ficha := r.ficha; v_origens := r.origens; v_fontes := r.fontes;

  FOR v_prop IN SELECT value FROM jsonb_array_elements(COALESCE(p.resultado -> 'propostas', '[]'::jsonb)) LOOP
    k := v_prop ->> 'campo';
    CONTINUE WHEN k IS NULL OR NOT (k = ANY (COALESCE(p_campos, '{}'::text[])));
    IF k = 'produtor' THEN
      v_prod := btrim(COALESCE(v_prop ->> 'valor', ''));
      CONTINUE;
    END IF;
    CONTINUE WHEN k !~ '^[a-z][a-z0-9_]{0,39}$';
    v := v_prop -> 'valor';
    CONTINUE WHEN winecatalog.vazio(v);
    -- Sem colheita não há janela (o trigger `vinhos_sem_colheita` também a
    -- tiraria, mas assim não aparece como "entrou").
    CONTINUE WHEN r.ano IS NULL AND k IN ('beber_de', 'beber_ate');
    IF k = 'regiao' AND jsonb_typeof(v) = 'string' THEN
      v := to_jsonb(winecatalog.normalizar_regiao(v #>> '{}'));
      CONTINUE WHEN v IS NULL;
    END IF;
    IF (v_ficha ? k) AND winecatalog.igual(v_ficha -> k, v) THEN
      v_iguais := v_iguais || to_jsonb(k);
      CONTINUE;
    END IF;
    v_atual := v_prop -> 'atual';
    IF winecatalog.vazio(v_atual) <> winecatalog.vazio(v_ficha -> k)
       OR (NOT winecatalog.vazio(v_atual) AND NOT winecatalog.igual(v_ficha -> k, v_atual)) THEN
      v_mudaram := v_mudaram || to_jsonb(k);
      CONTINUE;
    END IF;
    v_ficha   := v_ficha   || jsonb_build_object(k, v);
    v_origens := v_origens || jsonb_build_object(k, jsonb_build_object(
      'o', 'catalogo-pesquisa', 'f', winecatalog.forca('catalogo-pesquisa', k), 'em', now()));
    v_entrou  := v_entrou  || to_jsonb(k);
  END LOOP;

  IF jsonb_array_length(v_entrou) > 0 THEN
    -- As fontes da pesquisa acompanham o que dela se aceitou — a mesma
    -- acumulação da `juntar` (sem repetir URL, 8 no máximo).
    IF jsonb_typeof(p.resultado -> 'fontes') = 'array' THEN
      SELECT COALESCE(jsonb_agg(f), '[]'::jsonb) INTO v_fontes FROM (
        SELECT DISTINCT ON (f ->> 'url') f
          FROM jsonb_array_elements(COALESCE(v_fontes, '[]'::jsonb) || (p.resultado -> 'fontes')) f
         WHERE COALESCE(f ->> 'url', '') <> ''
         ORDER BY (f ->> 'url') LIMIT 8) x;
    END IF;
    UPDATE winecatalog.vinhos
       SET ficha = v_ficha, origens = v_origens, fontes = COALESCE(v_fontes, fontes),
           atualizado_em = now()
     WHERE id = r.id;
  END IF;

  IF COALESCE(v_prod, '') <> '' AND v_prod IS DISTINCT FROM r.produtor THEN
    BEGIN
      PERFORM winecatalog.editar(r.id, '{}'::jsonb, r.nome, v_prod, r.ano, true);
      v_prod_ok := true;
    EXCEPTION WHEN OTHERS THEN
      v_prod_err := SQLERRM;
    END;
  END IF;

  UPDATE winecatalog.pesquisas
     SET resultado = resultado || jsonb_build_object(
           'aplicadoEm', now(),
           'aplicados', v_entrou || CASE WHEN v_prod_ok THEN '["produtor"]'::jsonb ELSE '[]'::jsonb END,
           'descartada', COALESCE(array_length(p_campos, 1), 0) = 0)
   WHERE id = p.id;

  IF jsonb_array_length(v_entrou) > 0 OR v_prod_ok THEN
    INSERT INTO winecatalog.sync_log (origem, acao, estado, quem, detalhe)
    VALUES ('app', 'pesquisa_aplicar', 'ok', auth.email(), jsonb_build_object(
      'vinho_id', r.id, 'pesquisa_id', p.id, 'entrou', v_entrou,
      'produtor', v_prod_ok, 'mudaram', v_mudaram));
  END IF;

  RETURN jsonb_build_object('ok', true, 'entrou', v_entrou, 'iguais', v_iguais,
    'mudaram', v_mudaram, 'produtor', v_prod_ok, 'produtorErro', v_prod_err);
END;
$$;

-- A pesquisa que ficou por rever (ou ainda a correr) para um vinho — é o
-- que a ficha mostra ao abrir, para uma pesquisa fechada a meio não se
-- perder: "fica à espera de ti na ficha do vinho". Só a ÚLTIMA pesquisa do
-- vinho conta: uma pesquisa profunda pedida a partir da revisão de outra
-- substitui-a, e a de antes não pode voltar a aparecer depois de esta ser
-- tratada. Uma semana chega; mais velha, já não diz o que está no catálogo.
CREATE OR REPLACE FUNCTION winecatalog.pesquisa_por_rever(p_vinho_id bigint)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE p winecatalog.pesquisas%ROWTYPE;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Sem acesso.';
  END IF;
  SELECT * INTO p FROM winecatalog.pesquisas
   WHERE vinho_id = p_vinho_id
   ORDER BY criado_em DESC LIMIT 1;
  IF p.id IS NULL THEN RETURN NULL; END IF;
  IF NOT ((p.estado = 'pendente' AND p.criado_em > now() - interval '5 minutes')
       OR (p.estado = 'concluido' AND p.resultado ->> 'rever' = 'true'
           AND NOT p.resultado ? 'aplicadoEm'
           AND jsonb_array_length(COALESCE(p.resultado -> 'propostas', '[]'::jsonb)) > 0
           AND p.fechado_em > now() - interval '7 days')) THEN
    RETURN NULL;
  END IF;
  RETURN jsonb_build_object(
    'id', p.id, 'vinhoId', p.vinho_id, 'estado', p.estado,
    'resultado', p.resultado, 'erro', p.erro,
    'criadoEm', p.criado_em, 'fechadoEm', p.fechado_em);
END;
$$;


-- =====================================================================
-- 5. COMPARAR — "o que é que o catálogo tem de diferente do que eu tenho?"
--
-- ESTA É A ÚNICA FUNÇÃO DESTE SCHEMA ABERTA A QUALQUER PESSOA COM LOGIN,
-- e vale a pena ser explícito sobre a decisão.
--
-- Quem chama é a Garrafeira, em nome de uma pessoa que pode não estar (e
-- normalmente não está) em `winecatalog.allowed_users` — é dona da sua
-- garrafeira, não tem nada que ver com esta app. Exigir-lhe acesso ao
-- catálogo era exigir-lhe uma conta numa app que ela não usa, e a
-- funcionalidade morria aí.
--
-- O que se abre, e o que NÃO se abre:
--   · responde a UM vinho de cada vez, dado por nome — não enumera nada,
--     não há como varrer o catálogo com isto;
--   · devolve só a FICHA desse vinho (factos de um vinho, que é o que a
--     `vinho-info` já lhe dava na mesma), com a origem e a força de cada
--     campo, que é o que dá sentido à marca no ecrã;
--   · NÃO devolve as chaves, o `quem`, as fusões, nem o id de mais nada.
--
-- `p_ficha` é o que a pessoa tem do lado dela, na forma da ficha do
-- catálogo (a `garrafeira.ficha_catalogo` é que faz essa tradução, e é a
-- MESMA que alimenta o `juntar` — uma tradução só não pode divergir).
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.comparar(
  p_nome text, p_produtor text DEFAULT '', p_ano integer DEFAULT NULL,
  p_ficha jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb
  LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_id  bigint;
  r     winecatalog.vinhos%ROWTYPE;
  v_res jsonb;
BEGIN
  -- A service_role não tem email, e é ela que o batch do admin usa para
  -- comparar as garrafeiras com o catálogo (`garrafeira.fichas_catalogo_rever`).
  -- Já lê tudo de qualquer maneira; recusá-la aqui era só partir o batch.
  IF COALESCE(auth.email(), '') = '' AND COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Precisa de sessão iniciada.';
  END IF;
  IF COALESCE(btrim(COALESCE(p_nome,'')), '') = '' THEN RETURN NULL; END IF;

  -- `false` no `p_exigir_ano`: a garrafeira tem o ano e o catálogo pode só
  -- ter outra colheita do mesmo vinho. Isso é uma resposta útil para os
  -- factos estáveis — e a UI diz de que colheita é, como já faz na
  -- WineSelection.
  v_id := winecatalog.achar(p_nome, COALESCE(p_produtor,''), p_ano, false);
  IF v_id IS NULL THEN
    RETURN jsonb_build_object('encontrado', false);
  END IF;
  SELECT * INTO r FROM winecatalog.vinhos WHERE id = v_id;
  IF r.id IS NULL THEN RETURN jsonb_build_object('encontrado', false); END IF;

  SELECT COALESCE(jsonb_agg(x ORDER BY x ->> 'campo'), '[]'::jsonb) INTO v_res
    FROM (
      SELECT jsonb_build_object(
               'campo',    k,
               'catalogo', r.ficha -> k,
               'meu',      p_ficha -> k,
               'origem',   r.origens -> k ->> 'o',
               'forca',    COALESCE((r.origens -> k ->> 'f')::integer, 0),
               'em',       r.origens -> k ->> 'em',
               -- as três situações, e são mesmo três coisas diferentes:
               'difere',      NOT winecatalog.vazio(p_ficha -> k)
                              AND NOT winecatalog.vazio(r.ficha -> k)
                              AND NOT winecatalog.igual(p_ficha -> k, r.ficha -> k),
               'soCatalogo',  winecatalog.vazio(p_ficha -> k)
                              AND NOT winecatalog.vazio(r.ficha -> k),
               'soMeu',       NOT winecatalog.vazio(p_ficha -> k)
                              AND winecatalog.vazio(r.ficha -> k)
             ) AS x
        FROM (SELECT jsonb_object_keys(r.ficha) AS k
              UNION
              SELECT jsonb_object_keys(COALESCE(p_ficha,'{}'::jsonb))) ks
        -- A janela de consumo é escrita em anos de UMA colheita: só se
        -- compara (e só se oferece) entre a mesma colheita, conhecida dos
        -- dois lados. A de outro ano — ou a de nenhum — não é um desacordo
        -- nem informação que falte, é outra garrafa.
       WHERE NOT (k IN ('beber_de', 'beber_ate')
                  AND NOT COALESCE(r.ano = p_ano, false))
    ) y
   WHERE (x ->> 'difere')::boolean OR (x ->> 'soCatalogo')::boolean;

  RETURN jsonb_build_object(
    'encontrado', true,
    -- o ID vai porque o `reportar` precisa de saber de que linha se fala.
    -- Sozinho não abre nada: não há função nenhuma que leia o catálogo por
    -- id sem `pode_ler()`.
    'id', r.id,
    'nome', r.nome, 'produtor', r.produtor, 'ano', r.ano,
    -- A colheita do catálogo pode não ser a da garrafa que está em casa, e
    -- isso muda o que a nota quer dizer. Quem mostra tem de o poder dizer.
    'mesmaColheita', (r.ano IS NOT DISTINCT FROM p_ano),
    'campos', v_res);
END;
$$;


-- =====================================================================
-- 6. REPORTAR — avisar o admin do catálogo
--
-- O ponto desta função é uma frase: corrigir só na minha garrafeira deixa
-- o erro no catálogo, e portanto deixa-o a toda a gente. Um botão que
-- avisa custa menos do que descobrir o mesmo erro três vezes.
-- =====================================================================
CREATE OR REPLACE FUNCTION winecatalog.reportar(
  p_nome text, p_produtor text, p_ano integer,
  p_campo text, p_valor_deles jsonb, p_nota text DEFAULT NULL,
  p_app text DEFAULT 'garrafeira'
) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_quem text := lower(COALESCE(auth.email(), ''));
  v_id   bigint;
  r      winecatalog.vinhos%ROWTYPE;
  v_rid  bigint;
BEGIN
  IF v_quem = '' THEN RAISE EXCEPTION 'Precisa de sessão iniciada.'; END IF;
  IF COALESCE(btrim(COALESCE(p_campo,'')),'') = '' THEN
    RAISE EXCEPTION 'Falta dizer que campo é.';
  END IF;
  IF COALESCE(btrim(COALESCE(p_nome,'')),'') = '' THEN
    RAISE EXCEPTION 'Falta o vinho.';
  END IF;

  -- Trava de bom senso: 20 alertas abertos por pessoa chegam para
  -- qualquer garrafeira e não chegam para entupir o ecrã do admin.
  IF (SELECT count(*) FROM winecatalog.reportes
       WHERE quem = v_quem AND estado = 'aberto') >= 20 THEN
    RAISE EXCEPTION 'Já tens 20 alertas por tratar — espera que o admin os veja.';
  END IF;

  v_id := winecatalog.achar(p_nome, COALESCE(p_produtor,''), p_ano, false);
  IF v_id IS NOT NULL THEN
    SELECT * INTO r FROM winecatalog.vinhos WHERE id = v_id;
  END IF;

  INSERT INTO winecatalog.reportes
    (vinho_id, chave, nome, produtor, ano, campo,
     valor_catalogo, valor_deles, nota, app, quem)
  VALUES
    (r.id, r.chave, btrim(p_nome), COALESCE(btrim(COALESCE(p_produtor,'')),''), p_ano,
     left(btrim(p_campo), 40),
     r.ficha -> left(btrim(p_campo), 40), p_valor_deles,
     NULLIF(left(btrim(COALESCE(p_nota,'')), 500), ''),
     left(COALESCE(p_app,'garrafeira'), 20), v_quem)
  ON CONFLICT (quem, COALESCE(chave,''), campo) WHERE estado = 'aberto'
  DO UPDATE SET valor_deles = EXCLUDED.valor_deles,
                valor_catalogo = EXCLUDED.valor_catalogo,
                nota = COALESCE(EXCLUDED.nota, winecatalog.reportes.nota),
                quando = now()
  RETURNING id INTO v_rid;

  RETURN jsonb_build_object('ok', true, 'id', v_rid, 'noCatalogo', r.id IS NOT NULL);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.listar_reportes(p_estado text DEFAULT 'aberto')
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_res jsonb; v_e text := COALESCE(NULLIF(btrim(COALESCE(p_estado,'')),''), 'aberto');
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo vê os alertas.';
  END IF;
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'id', t.id, 'vinhoId', t.vinho_id,
           'nome', t.nome, 'produtor', t.produtor, 'ano', t.ano,
           'campo', t.campo,
           'valorCatalogo', t.valor_catalogo, 'valorDeles', t.valor_deles,
           -- o valor de AGORA ao lado do de então: se alguém já corrigiu
           -- entretanto, o admin vê-o sem ter de abrir a ficha
           'valorAgora', v.ficha -> t.campo,
           'origemAgora', v.origens -> t.campo ->> 'o',
           'forcaAgora', COALESCE((v.origens -> t.campo ->> 'f')::integer, 0),
           'nota', t.nota, 'app', t.app, 'quem', t.quem, 'quando', t.quando,
           'estado', t.estado, 'resposta', t.resposta
         ) ORDER BY t.quando DESC), '[]'::jsonb) INTO v_res
    FROM (SELECT * FROM winecatalog.reportes
           WHERE (v_e = 'todos' OR estado = v_e)
           ORDER BY quando DESC LIMIT 200) t
    LEFT JOIN winecatalog.vinhos v ON v.id = t.vinho_id;
  RETURN v_res;
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.contar_reportes()
  RETURNS integer LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE WHEN winecatalog.sou_admin()
              THEN (SELECT count(*)::integer FROM winecatalog.reportes WHERE estado = 'aberto')
              ELSE 0 END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.resolver_reporte(
  p_id bigint, p_estado text DEFAULT 'resolvido', p_resposta text DEFAULT NULL)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_e text := COALESCE(NULLIF(btrim(COALESCE(p_estado,'')),''), 'resolvido');
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo trata dos alertas.';
  END IF;
  IF v_e NOT IN ('aberto','resolvido','rejeitado') THEN
    RAISE EXCEPTION 'Estado inválido.';
  END IF;
  UPDATE winecatalog.reportes
     SET estado = v_e,
         resposta = NULLIF(left(btrim(COALESCE(p_resposta,'')), 500), ''),
         fechado_em  = CASE WHEN v_e = 'aberto' THEN NULL ELSE now() END,
         fechado_por = CASE WHEN v_e = 'aberto' THEN NULL ELSE auth.email() END
   WHERE id = p_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Alerta não encontrado.'; END IF;
  RETURN jsonb_build_object('ok', true, 'estado', v_e);
END;
$$;


-- =====================================================================
-- 7. GRANTS — a mesma postura do `catalogo.sql`
--
-- As duas tabelas novas não têm grant nenhum a quem tem login: chega-se
-- lá pelas funções SECURITY DEFINER, e mais nada. (A `sync_log` nasce no
-- `catalogo.sql`, ao pé da vista que a lê, e os grants dela estão lá.)
-- =====================================================================
REVOKE ALL ON winecatalog.pesquisas FROM PUBLIC, anon, authenticated;
REVOKE ALL ON winecatalog.reportes  FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.pesquisas TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.reportes  TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA winecatalog TO service_role;

-- As de apoio à comparação: puras sobre os argumentos, não lêem tabela
-- nenhuma. Ficam fechadas na mesma — não há razão para estarem abertas.
REVOKE ALL ON FUNCTION winecatalog.texto_norm(text)   FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.igual(jsonb,jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.vazio(jsonb)       FROM PUBLIC, anon;

-- As do admin, chamadas do browser com o JWT dele. A confirmação de quem
-- é está DENTRO de cada uma (`sou_admin()`), como nas outras.
REVOKE ALL ON FUNCTION winecatalog.editar(bigint, jsonb, text, text, integer, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.criar(text, text, integer, jsonb)   FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.pesquisa_criar(bigint)          FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.pesquisa_ver(bigint)            FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.pesquisa_aplicar(bigint, text[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.pesquisa_por_rever(bigint)      FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.listar_reportes(text)           FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.contar_reportes()               FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.resolver_reporte(bigint, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.editar(bigint, jsonb, text, text, integer, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.criar(text, text, integer, jsonb)   TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.pesquisa_criar(bigint)          TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.pesquisa_ver(bigint)            TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.pesquisa_aplicar(bigint, text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.pesquisa_por_rever(bigint)      TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.listar_reportes(text)           TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.contar_reportes()               TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.resolver_reporte(bigint, text, text) TO authenticated;

-- As DUAS que a outra app chama, em nome de gente que não tem conta nesta.
-- Ver o comentário grande da `comparar`: é uma decisão, não um descuido.
REVOKE ALL ON FUNCTION winecatalog.comparar(text, text, integer, jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.reportar(text, text, integer, text, jsonb, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.comparar(text, text, integer, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.reportar(text, text, integer, text, jsonb, text, text) TO authenticated;
