-- =====================================================================
-- WineCatalog — HISTÓRICO DE ALTERAÇÕES (campo a campo)
--
-- Correr DEPOIS de `curadoria.sql` (a `repor_alteracao` usa a `editar`).
-- Idempotente.
--
-- PORQUÊ. A 25/09/2026 o dono decidiu que o script do Vivino e das lojas
-- passa a ESCREVER no catálogo em vez de deixar propostas — e pediu, em
-- troca, uma forma fácil de ver o que mudou em cada atributo, quem mudou e
-- quando. O `origens` só guarda o ÚLTIMO valor de cada campo (de onde veio,
-- com que força, quando), e o `sync_log` só as correções à mão. Nenhum dos
-- dois responde a "o que estava aqui antes?".
--
-- COMO. Um trigger na própria `vinhos`, e não um registo em cada função
-- que escreve: são seis portas (juntar, editar, criar, fundir, separar,
-- aplicar_fontes) e uma que se esquecesse de registar era um buraco calado
-- no histórico. Na tabela, nenhuma escapa.
--
-- QUEM. Quem escreve diz quem é pela configuração `winecatalog.quem` (o
-- script põe "script Vivino/lojas (PC)"); sem ela, o email de quem tem a
-- sessão; sem sessão, o papel. MAS: uma escrita com origem numa GARRAFEIRA
-- fica "uma garrafeira", sem email — o email ligava uma pessoa a um vinho,
-- ou seja, dizia o que ela tem em casa, e isso é exatamente o que o
-- catálogo promete não abrir (invariante 2 do CLAUDE.md).
-- =====================================================================

CREATE TABLE IF NOT EXISTS winecatalog.alteracoes (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  vinho_id  bigint NOT NULL,
  campo     text   NOT NULL,   -- um campo da ficha, ou nome/produtor/ano, ou _criado
  antes     jsonb,
  depois    jsonb,
  origem    text,              -- a origem que ficou no `origens` para o campo
  quem      text,
  quando    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alteracoes_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS alteracoes_vinho_idx ON winecatalog.alteracoes (vinho_id, quando DESC);
CREATE INDEX IF NOT EXISTS alteracoes_quando_idx ON winecatalog.alteracoes (quando DESC);
ALTER TABLE winecatalog.alteracoes ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION winecatalog.quem_escreve(p_origem text)
  RETURNS text LANGUAGE sql STABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT CASE
    WHEN COALESCE(p_origem, '') IN ('garrafeira', 'garrafeira-bruto') THEN 'uma garrafeira'
    ELSE COALESCE(NULLIF(current_setting('winecatalog.quem', true), ''),
                  auth.email(),
                  CASE WHEN auth.role() = 'service_role' THEN 'Edge Function (service_role)' END,
                  current_user)
  END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.registar_alteracoes()
  RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  k   text;
  o   text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO winecatalog.alteracoes (vinho_id, campo, antes, depois, origem, quem)
    VALUES (NEW.id, '_criado', NULL, to_jsonb(NEW.nome), NULL, winecatalog.quem_escreve(NULL));
    RETURN NEW;
  END IF;

  FOR k IN SELECT DISTINCT key FROM (
             SELECT jsonb_object_keys(COALESCE(OLD.ficha, '{}')) AS key
             UNION SELECT jsonb_object_keys(COALESCE(NEW.ficha, '{}'))) t
  LOOP
    CONTINUE WHEN (OLD.ficha -> k) IS NOT DISTINCT FROM (NEW.ficha -> k);
    o := COALESCE(NEW.origens -> k ->> 'o', OLD.origens -> k ->> 'o');
    -- Um campo APAGADO não tem origem nova: quem apaga é quem tem a sessão.
    IF NOT (NEW.ficha ? k) THEN o := NULL; END IF;
    INSERT INTO winecatalog.alteracoes (vinho_id, campo, antes, depois, origem, quem)
    VALUES (NEW.id, k, OLD.ficha -> k, NEW.ficha -> k, o, winecatalog.quem_escreve(o));
  END LOOP;

  IF OLD.nome IS DISTINCT FROM NEW.nome THEN
    INSERT INTO winecatalog.alteracoes (vinho_id, campo, antes, depois, quem)
    VALUES (NEW.id, 'nome', to_jsonb(OLD.nome), to_jsonb(NEW.nome), winecatalog.quem_escreve(NULL));
  END IF;
  IF OLD.produtor IS DISTINCT FROM NEW.produtor THEN
    INSERT INTO winecatalog.alteracoes (vinho_id, campo, antes, depois, quem)
    VALUES (NEW.id, 'produtor', to_jsonb(OLD.produtor), to_jsonb(NEW.produtor), winecatalog.quem_escreve(NULL));
  END IF;
  IF OLD.ano IS DISTINCT FROM NEW.ano THEN
    INSERT INTO winecatalog.alteracoes (vinho_id, campo, antes, depois, quem)
    VALUES (NEW.id, 'ano', to_jsonb(OLD.ano), to_jsonb(NEW.ano), winecatalog.quem_escreve(NULL));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS vinhos_historico ON winecatalog.vinhos;
CREATE TRIGGER vinhos_historico
  AFTER INSERT OR UPDATE ON winecatalog.vinhos
  FOR EACH ROW EXECUTE FUNCTION winecatalog.registar_alteracoes();


-- ---------------------------------------------------------------------
-- LER — só o admin (o `quem` tem emails; e o conjunto diz o que passou
-- por aqui). Um vinho, ou os últimos de todo o catálogo.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.historico(p_vinho_id bigint DEFAULT NULL, p_limite integer DEFAULT 100)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo vê o histórico.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', a.id, 'vinhoId', a.vinho_id, 'campo', a.campo,
      'antes', a.antes, 'depois', a.depois, 'origem', a.origem,
      'quem', a.quem, 'quando', a.quando,
      'nome', v.nome, 'ano', v.ano,
      'agora', v.ficha -> a.campo)
      ORDER BY a.quando DESC, a.id DESC)
    FROM (
      SELECT * FROM winecatalog.alteracoes
       WHERE p_vinho_id IS NULL OR vinho_id = p_vinho_id
          -- As linhas fundidas nesta também contam a história dela.
          OR vinho_id IN (SELECT id_de FROM winecatalog.alias WHERE id_para = p_vinho_id)
       ORDER BY quando DESC, id DESC
       LIMIT GREATEST(1, LEAST(COALESCE(p_limite, 100), 500))
    ) a
    LEFT JOIN winecatalog.vinhos v ON v.id = a.vinho_id
  ), '[]'::jsonb);
END;
$$;

-- ---------------------------------------------------------------------
-- REPOR — o valor de antes volta, pela `editar` (a mesma porta de uma
-- correção à mão: força do admin, sync_log, e mais uma linha de histórico).
-- Só campos da ficha: repor um NOME mexe na chave, e isso é o Editar com o
-- interruptor de identidade, que verifica duplicados.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.repor_alteracao(p_id bigint)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  a      winecatalog.alteracoes%ROWTYPE;
  v_alvo bigint;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo repõe valores.';
  END IF;
  SELECT * INTO a FROM winecatalog.alteracoes WHERE id = p_id;
  IF a.id IS NULL THEN RAISE EXCEPTION 'Alteração não encontrada.'; END IF;
  IF a.campo IN ('nome', 'produtor', 'ano', '_criado') THEN
    RAISE EXCEPTION 'A identidade não se repõe daqui — usa o Editar (interruptor de identidade).';
  END IF;
  v_alvo := COALESCE((SELECT id_para FROM winecatalog.alias WHERE id_de = a.vinho_id), a.vinho_id);
  RETURN winecatalog.editar(v_alvo, jsonb_build_object(a.campo, COALESCE(a.antes, 'null'::jsonb)));
END;
$$;


REVOKE ALL ON winecatalog.alteracoes FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON winecatalog.alteracoes TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA winecatalog TO service_role;

REVOKE ALL ON FUNCTION winecatalog.quem_escreve(text)          FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.registar_alteracoes()       FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.historico(bigint, integer)  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.repor_alteracao(bigint)     FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.historico(bigint, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.repor_alteracao(bigint)    TO authenticated;
