-- ═══════════════════════════════════════════════════════════════════════
-- ia_uso — o registo central de acessos ao Gemini
-- ═══════════════════════════════════════════════════════════════════════
-- Schema À PARTE, no MESMO projeto Supabase, partilhado pelas CINCO apps
-- que chamam o Gemini. Uma linha por chamada: quem, que app, que função,
-- que modelo, quantos tokens, quanto custou (estimado), quanto demorou e
-- o que correu mal.
--
-- PORQUE É QUE ISTO EXISTE. Cada app já tinha o seu `sync_log` e nenhuma
-- sabia o que as outras gastavam — a pergunta "quanto é que isto me está
-- a custar ao todo?" não tinha onde ser respondida. Somar cinco tabelas à
-- mão, em cinco schemas, com colunas diferentes, não é resposta.
--
-- PORQUE É UM SCHEMA À PARTE, e não uma tabela na WineCatalog. Pelo mesmo
-- motivo que o catálogo saiu da Garrafeira: isto não é de nenhuma das
-- cinco apps. Pendurá-lo numa delas era dar a quem herdasse essa app o
-- poder sobre uma tabela que regista o gasto de todas. Tem dono próprio
-- (`ia_uso.config.admin_email`), que não tem de ser o admin de nenhuma.
--
-- O QUE ESTE FICHEIRO NÃO DECIDE: o que cada app escreve aqui. Isso vive
-- na `registarIaUso()` de cada uma das 8 Edge Functions — duplicada de
-- propósito, como tudo neste projeto (cada Edge Function é auto-contida).
-- Ver "O registo central de acessos ao Gemini" no CLAUDE.md da WineCatalog.
--
-- ESCRITA: só a `service_role`, de dentro das Edge Functions
-- (`Content-Profile: ia_uso`). LEITURA: as funções `listar()`/`resumo()`,
-- com o portão `sou_admin()` lá dentro, mais as policies de SELECT como
-- segundo cinto para quem chegue à tabela por REST.
--
-- É IDEMPOTENTE: corre as vezes que forem precisas.
--
-- As 6 apps / 9 functions que escrevem aqui:
--   winecatalog    catalogo-info, catalogo-foto
--   garrafeira     vinho-info, importar-vinhos
--   wineselection  sugerir-vinho, verificar-vinhos
--   splitbill      fatura-restaurante
--   festasbv       fatura-ocr
--   goals          calendario-sporting
--
-- A `calendario-sporting` é a única que serve DUAS apps — o SplitBill lê o
-- mesmo calendário — e por isso grava `app` = quem chamou (`goals` ou
-- `splitbill`), não um "goals" fixo. A pergunta a que esta tabela existe
-- para responder é quanto custa cada APP, não quanto custa cada ficheiro.
--
-- PASSO MANUAL NO PAINEL: `ia_uso` tem de estar em Project Settings → API
-- → Data API → Exposed schemas. Sem isso o PostgREST responde PGRST106 e
-- os INSERTs das Edge Functions são engolidos pelo `try/catch` delas — a
-- tabela fica a zero sem um único erro à vista. É o pitfall do costume
-- com schemas não-`public`.
-- ═══════════════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS ia_uso;

-- ── Quem manda aqui ────────────────────────────────────────────────────
-- Na BASE DE DADOS e não em código, como nas apps irmãs: a app nasce com
-- um dono e pode um dia passar para outro sem um deploy pelo meio.
CREATE TABLE IF NOT EXISTS ia_uso.config (
  chave text PRIMARY KEY,
  valor text NOT NULL
);

INSERT INTO ia_uso.config (chave, valor)
VALUES ('admin_email', 'diogo.andre.f.silva@gmail.com')
ON CONFLICT (chave) DO NOTHING;

-- ── Uma linha por chamada ao Gemini ────────────────────────────────────
-- Os TOKENS são facto — vêm do `usageMetadata` da API. O `custo_estimado_eur`
-- é uma ESTIMATIVA GROSSEIRA, calculada de constantes escritas à mão em
-- cada Edge Function, e a pesquisa Google é faturada à parte por pedido.
-- Não é um preço publicado, e não se deve ler como fatura.
--
-- `detalhe` guarda o payload inteiro do `sync_log` da app de origem: é o
-- que permite investigar um caso concreto sem ter de acrescentar uma
-- coluna por cada coisa nova que uma das cinco apps queira registar.
CREATE TABLE IF NOT EXISTS ia_uso.registos (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  criado_em          timestamptz NOT NULL DEFAULT now(),
  app                text NOT NULL,
  funcao             text NOT NULL,
  estado             text NOT NULL DEFAULT 'ok'
                       CHECK (estado IN ('pedido', 'ok', 'erro')),
  modelo             text,
  pesquisa_web       boolean,
  tokens_entrada     integer,
  tokens_saida       integer,
  tokens_pensamento  integer,
  tokens_total       integer,
  custo_estimado_eur numeric,
  duracao_ms         integer,
  quem               text,
  erro               text,
  detalhe            jsonb
);

-- Por data (o ecrã abre sempre pelo mais recente), por app+data (o filtro
-- que o painel usa) e por modelo (a pergunta "o flash-lite chega?").
CREATE INDEX IF NOT EXISTS registos_criado_idx
  ON ia_uso.registos USING btree (criado_em DESC);
CREATE INDEX IF NOT EXISTS registos_app_criado_idx
  ON ia_uso.registos USING btree (app, criado_em DESC);
CREATE INDEX IF NOT EXISTS registos_modelo_idx
  ON ia_uso.registos USING btree (modelo);

-- ═══════════════════════════════════════════════════════════════════════
-- Funções
-- ═══════════════════════════════════════════════════════════════════════
-- Todas com `search_path` FIXO. Nenhuma app deste projeto o dispensa — foi
-- o linter do Supabase que apanhou as que não o tinham na WineSelection, e
-- a lição foi que a regra existia num repo e não no outro.

CREATE OR REPLACE FUNCTION ia_uso.admin_email()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
  SELECT COALESCE(
    (SELECT lower(valor) FROM ia_uso.config WHERE chave = 'admin_email'),
    'diogo.andre.f.silva@gmail.com'
  );
$$;

CREATE OR REPLACE FUNCTION ia_uso.sou_admin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
  SELECT lower(COALESCE(auth.email(), '')) = ia_uso.admin_email();
$$;

-- Passar este painel a outra pessoa. Só o admin de agora o pode fazer.
CREATE OR REPLACE FUNCTION ia_uso.definir_admin(p_email text)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
DECLARE
  v_novo text := lower(trim(COALESCE(p_email, '')));
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin pode passar este painel a outra pessoa.';
  END IF;
  IF v_novo = '' OR v_novo NOT LIKE '%@%' THEN
    RAISE EXCEPTION 'Email inválido.';
  END IF;
  INSERT INTO ia_uso.config (chave, valor) VALUES ('admin_email', v_novo)
  ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor;
  RETURN 'ok';
END;
$$;

-- Os registos em bruto, do mais recente para o mais antigo. O limite é
-- capado a 1000 — é um painel, não um export.
CREATE OR REPLACE FUNCTION ia_uso.listar(
  p_limite integer DEFAULT 200,
  p_app text DEFAULT NULL,
  p_desde timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê os acessos à IA.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(to_jsonb(r) ORDER BY r.criado_em DESC)
    FROM (
      SELECT * FROM ia_uso.registos
       WHERE (p_app IS NULL OR app = p_app)
         AND (p_desde IS NULL OR criado_em >= p_desde)
       ORDER BY criado_em DESC
       LIMIT LEAST(GREATEST(COALESCE(p_limite, 200), 1), 1000)
    ) r
  ), '[]'::jsonb);
END;
$$;

-- Os totais: por app, por modelo, na janela pedida e desde sempre.
-- `porApp`/`porModelo` são do TOTAL acumulado (não da janela) de propósito
-- — a pergunta "quanto é que cada app já gastou" não se responde com 30
-- dias; a janela serve para ver o ritmo de agora, e vem à parte.
CREATE OR REPLACE FUNCTION ia_uso.resumo(p_dias integer DEFAULT 30)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
DECLARE
  v_desde timestamptz := now() - make_interval(days => GREATEST(COALESCE(p_dias, 30), 1));
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê os acessos à IA.';
  END IF;
  RETURN jsonb_build_object(
    'janelaDias', p_dias,
    'porApp', COALESCE((
      SELECT jsonb_agg(x ORDER BY (x ->> 'pedidos')::int DESC) FROM (
        SELECT jsonb_build_object(
          'app', app,
          'pedidos', count(*),
          'ok', count(*) FILTER (WHERE estado = 'ok'),
          'erro', count(*) FILTER (WHERE estado = 'erro'),
          'tokensEntrada', COALESCE(sum(tokens_entrada), 0),
          'tokensSaida', COALESCE(sum(tokens_saida), 0),
          'custoEur', COALESCE(sum(custo_estimado_eur), 0),
          'ultimaChamada', max(criado_em)
        ) AS x
        FROM ia_uso.registos GROUP BY app
      ) t
    ), '[]'::jsonb),
    'porModelo', COALESCE((
      SELECT jsonb_agg(x ORDER BY (x ->> 'pedidos')::int DESC) FROM (
        SELECT jsonb_build_object(
          'modelo', COALESCE(modelo, '(desconhecido)'),
          'pedidos', count(*),
          'tokensEntrada', COALESCE(sum(tokens_entrada), 0),
          'tokensSaida', COALESCE(sum(tokens_saida), 0),
          'custoEur', COALESCE(sum(custo_estimado_eur), 0)
        ) AS x
        FROM ia_uso.registos GROUP BY modelo
      ) t
    ), '[]'::jsonb),
    'janela', (
      SELECT jsonb_build_object(
        'pedidos', count(*),
        'tokensEntrada', COALESCE(sum(tokens_entrada), 0),
        'tokensSaida', COALESCE(sum(tokens_saida), 0),
        'custoEur', COALESCE(sum(custo_estimado_eur), 0)
      ) FROM ia_uso.registos WHERE criado_em >= v_desde
    ),
    'total', (
      SELECT jsonb_build_object(
        'pedidos', count(*),
        'tokensEntrada', COALESCE(sum(tokens_entrada), 0),
        'tokensSaida', COALESCE(sum(tokens_saida), 0),
        'custoEur', COALESCE(sum(custo_estimado_eur), 0)
      ) FROM ia_uso.registos
    )
  );
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════
-- RLS, GRANTS e policies
-- ═══════════════════════════════════════════════════════════════════════
-- ISTO É O BLOCO QUE FALTOU CORRER À PRIMEIRA (20/09/2026) e sem o qual
-- NADA funciona: não havia um único GRANT no schema, nem sequer `USAGE`
-- para a `service_role`. Os INSERTs das 8 functions levavam 403 (42501) e
-- eram engolidos pelo `try/catch` delas — a tabela ficava a zero linhas
-- sem um erro em lado nenhum, e as funções de leitura estavam
-- inalcançáveis. Se algum dia isto voltar a estar vazio, é o primeiro
-- sítio a conferir (a seguir aos Exposed schemas, lá em cima).

ALTER TABLE ia_uso.registos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_uso.config   ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA ia_uso TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ia_uso TO service_role;
GRANT SELECT ON ia_uso.registos, ia_uso.config TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ia_uso TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ia_uso TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA ia_uso
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA ia_uso
  GRANT SELECT ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA ia_uso
  GRANT USAGE, SELECT ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA ia_uso
  GRANT EXECUTE ON FUNCTIONS TO authenticated, service_role;

-- Segundo cinto: quem chegue às tabelas por REST (e não pelas funções) só
-- lê sendo admin. A `service_role` passa por cima do RLS, como é suposto —
-- é ela que escreve, de dentro das Edge Functions.
DROP POLICY IF EXISTS registos_admin_le ON ia_uso.registos;
CREATE POLICY registos_admin_le ON ia_uso.registos
  FOR SELECT TO authenticated USING (ia_uso.sou_admin());

DROP POLICY IF EXISTS config_admin_le ON ia_uso.config;
CREATE POLICY config_admin_le ON ia_uso.config
  FOR SELECT TO authenticated USING (ia_uso.sou_admin());

-- ── Conferir depois de correr ──────────────────────────────────────────
-- select has_schema_privilege('service_role','ia_uso','USAGE')      as srv_usage,
--        has_table_privilege('service_role','ia_uso.registos','INSERT') as srv_insert,
--        has_table_privilege('authenticated','ia_uso.registos','SELECT') as auth_select,
--        has_function_privilege('authenticated','ia_uso.resumo(integer)','EXECUTE') as auth_exec;
-- select count(*) from pg_policies where schemaname = 'ia_uso';  -- 2
