-- =====================================================================
-- WineCatalog — VERIFICAÇÃO DOS LINKS DO VIVINO (o batch da noite)
--
-- Correr DEPOIS de `curadoria.sql` (usa a `editar`). Idempotente.
--
-- PORQUÊ. A 25/09/2026 olhou-se para os 135 links do Vivino do catálogo:
-- 18 estavam errados quase de certeza (formatos que o Vivino não usa, o
-- mesmo número em dois vinhos diferentes, o link do tinto num branco) e
-- 21 eram `/wines/<nº>`, que é o número de UMA colheita e não o do vinho.
-- Não é o Vivino a mudar links (o número depois de `/w/` é estável): é o
-- que as pesquisas de memória escreveram, com ar de verdadeiro.
--
-- O QUE FAZ. Um script (`batch/vivino-verificar.mjs`), SEM IA, com dois
-- motores: `browser` abre a página de cada vinho num Chromium a sério e
-- confere o nome (corre no computador do admin — o Vivino recusa-o a partir
-- dos servidores do GitHub, 403 a 25/09/2026); `serper` não toca no Vivino
-- e lê o link, a nota e as avaliações de uma pesquisa Google
-- `site:vivino.com` (corre no GitHub Actions, à mão).
--
-- O QUE NÃO FAZ: escrever no catálogo. Cada vinho tratado deixa uma linha
-- em `vivino_verificacoes` com o que encontrou e o que PROPÕE; quem
-- decide é o admin, no separador Alertas, e o que ele aceita entra pela
-- `editar` (força do `catalogo-admin`, com o antes e o depois no
-- `sync_log`). Um nome mal lido nunca chega sozinho a uma ficha.
--
-- QUANTO E QUANDO. Definições › "Links do Vivino": quantos vinhos de cada
-- vez. Desde 25/09/2026 corre SÓ À MÃO (o workflow não tem horário, a
-- pedido do dono: o Serper tem limite). A frequência continua a existir
-- aqui e na `vivino_a_tratar` para o dia em que voltar a haver um cron.
--
-- Vinhos pedidos à mão (`vivino_pedir`, a "fila") correm na noite seguinte
-- mesmo que a frequência diga que não é dia: foram pedidos por alguém.
-- =====================================================================

-- ---------------------------------------------------------------------
-- A TABELA — uma linha por vinho tratado, por execução
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winecatalog.vivino_verificacoes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  vinho_id      bigint NOT NULL,
  verificado_em timestamptz NOT NULL DEFAULT now(),
  execucao      text,          -- o run do GitHub Actions, para se ir ao log
  url_antes     text,          -- o link que o catálogo tinha nesse momento
  -- certo       a página (ou o Google) confirma que o link é deste vinho
  -- errado      a página abriu e é de OUTRO vinho                 (browser)
  -- diferente   o Google aponta para outro link; o atual não foi aberto (serper)
  -- nao_existe  "página não encontrada", ou um link que não pode abrir
  -- nao_encontrado  a procura não achou o vinho                   (serper)
  -- sem_link    o catálogo não tinha link
  -- bloqueado   o Vivino recusou abrir a página ao script
  -- erro        outra coisa correu mal (ver `detalhe`)
  estado        text NOT NULL,
  nome_pagina   text,          -- o nome que a página do link ATUAL mostra
  -- O que se propõe gravar: {vivino_url, vivino_nota, vivino_avaliacoes,
  -- nome, confianca}. Um `vivino_url` a null quer dizer "apagar o link".
  proposta      jsonb,
  candidatos    jsonb,         -- o que a procura no Vivino devolveu
  detalhe       jsonb,         -- HTTP, URL final, título, o que se leu
  -- pendente    à espera do admin
  -- aceite      a proposta entrou no catálogo
  -- recusado    o admin deixou o catálogo como estava
  -- sem_acao    nada a decidir (link certo e números iguais)
  revisao       text NOT NULL DEFAULT 'pendente',
  revisto_em    timestamptz,
  revisto_por   text,
  CONSTRAINT vivino_verificacoes_pkey PRIMARY KEY (id),
  CONSTRAINT vivino_verificacoes_estado_chk
    CHECK (estado IN ('certo','errado','diferente','nao_existe','nao_encontrado','sem_link','bloqueado','erro')),
  CONSTRAINT vivino_verificacoes_revisao_chk
    CHECK (revisao IN ('pendente','aceite','recusado','sem_acao'))
);
CREATE INDEX IF NOT EXISTS vivino_verificacoes_vinho_idx
  ON winecatalog.vivino_verificacoes (vinho_id, verificado_em DESC);
CREATE INDEX IF NOT EXISTS vivino_verificacoes_revisao_idx
  ON winecatalog.vivino_verificacoes (revisao, verificado_em DESC);
ALTER TABLE winecatalog.vivino_verificacoes ENABLE ROW LEVEL SECURITY;
-- Os estados do motor Serper (25/09/2026) numa base onde a tabela já existia.
ALTER TABLE winecatalog.vivino_verificacoes DROP CONSTRAINT IF EXISTS vivino_verificacoes_estado_chk;
ALTER TABLE winecatalog.vivino_verificacoes ADD CONSTRAINT vivino_verificacoes_estado_chk
  CHECK (estado IN ('certo','errado','diferente','nao_existe','nao_encontrado','sem_link','bloqueado','erro'));

-- As definições vivem na `config` que já existe (chave → texto).
INSERT INTO winecatalog.config (chave, valor) VALUES
  ('vivino_frequencia', 'desligado'),
  ('vivino_lote',       '10'),
  ('vivino_fila',       '[]')
ON CONFLICT (chave) DO NOTHING;


-- =====================================================================
-- DO LADO DO ADMIN (browser, JWT dele — `sou_admin()` dentro de cada uma)
-- =====================================================================

CREATE OR REPLACE FUNCTION winecatalog.vivino_config()
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_fila jsonb;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo vê isto.';
  END IF;
  v_fila := COALESCE((SELECT valor::jsonb FROM winecatalog.config WHERE chave = 'vivino_fila'), '[]');
  RETURN jsonb_build_object(
    'frequencia', COALESCE((SELECT valor FROM winecatalog.config WHERE chave = 'vivino_frequencia'), 'desligado'),
    'lote',       COALESCE((SELECT valor FROM winecatalog.config WHERE chave = 'vivino_lote')::int, 10),
    'ultima',     (SELECT valor FROM winecatalog.config WHERE chave = 'vivino_ultima'),
    'fila',       jsonb_array_length(v_fila),
    'pendentes',  (SELECT count(*) FROM winecatalog.vivino_verificacoes x WHERE x.revisao = 'pendente'
                    AND NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = x.vinho_id)),
    'verificados',(SELECT count(DISTINCT vinho_id) FROM winecatalog.vivino_verificacoes),
    'total',      (SELECT count(*) FROM winecatalog.vinhos v
                    WHERE NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = v.id))
  );
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.vivino_definir(p_frequencia text, p_lote integer)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo mexe nisto.';
  END IF;
  IF p_frequencia NOT IN ('desligado','diario','dia_sim_dia_nao','semanal') THEN
    RAISE EXCEPTION 'Frequência desconhecida: %', p_frequencia;
  END IF;
  -- 30 é o teto: a 4–7 s por página (mais a procura quando o link está
  -- errado), um lote maior passa a ser tráfego que se nota.
  IF p_lote IS NULL OR p_lote < 1 OR p_lote > 30 THEN
    RAISE EXCEPTION 'O número de vinhos de cada vez vai de 1 a 30.';
  END IF;
  INSERT INTO winecatalog.config (chave, valor) VALUES
    ('vivino_frequencia', p_frequencia), ('vivino_lote', p_lote::text)
  ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor;
  RETURN winecatalog.vivino_config();
END;
$$;

-- Pôr vinhos na fila da próxima execução (a ficha de um vinho, ou uma
-- lista à mão). Os que já lá estão não se repetem.
CREATE OR REPLACE FUNCTION winecatalog.vivino_pedir(p_ids bigint[])
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_fila jsonb;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo mexe nisto.';
  END IF;
  v_fila := COALESCE((SELECT valor::jsonb FROM winecatalog.config WHERE chave = 'vivino_fila'), '[]');
  SELECT COALESCE(jsonb_agg(x ORDER BY ord), '[]') INTO v_fila FROM (
    SELECT x, min(ord) ord FROM (
      SELECT value::bigint x, ordinality ord FROM jsonb_array_elements_text(v_fila) WITH ORDINALITY
      UNION ALL
      SELECT i, 100000 + ordinality FROM unnest(p_ids) WITH ORDINALITY AS u(i, ordinality)
       WHERE EXISTS (SELECT 1 FROM winecatalog.vinhos v WHERE v.id = i)
    ) t GROUP BY x
  ) s;
  INSERT INTO winecatalog.config (chave, valor) VALUES ('vivino_fila', v_fila::text)
  ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor;
  RETURN jsonb_build_object('fila', jsonb_array_length(v_fila));
END;
$$;

-- A lista do separador Alertas: cada verificação com o vinho e o que está
-- no catálogo AGORA (pode já ter mudado desde a noite em que se verificou).
CREATE OR REPLACE FUNCTION winecatalog.vivino_listar(p_revisao text DEFAULT 'pendente')
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo vê isto.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', x.id, 'vinhoId', x.vinho_id, 'quando', x.verificado_em,
      'estado', x.estado, 'revisao', x.revisao, 'urlAntes', x.url_antes,
      'nomePagina', x.nome_pagina, 'proposta', x.proposta,
      'candidatos', x.candidatos, 'detalhe', x.detalhe,
      'revistoEm', x.revisto_em, 'revistoPor', x.revisto_por,
      'nome', v.nome, 'produtor', v.produtor, 'ano', v.ano,
      'tipo', v.ficha ->> 'tipo',
      'agora', jsonb_build_object(
        'vivino_url',        v.ficha -> 'vivino_url',
        'vivino_nota',       v.ficha -> 'vivino_nota',
        'vivino_avaliacoes', v.ficha -> 'vivino_avaliacoes'))
      ORDER BY x.verificado_em DESC, x.id DESC)
    FROM (
      -- Uma proposta por decidir de um vinho que entretanto foi FUNDIDO
      -- noutro já não é pergunta nenhuma: era para o nome antigo. Não
      -- aparece nos pendentes (a `vivino_resolver` também a recusa).
      SELECT * FROM winecatalog.vivino_verificacoes x0
       WHERE p_revisao = 'todos'
          OR (x0.revisao = p_revisao AND NOT (p_revisao = 'pendente' AND EXISTS (
                SELECT 1 FROM winecatalog.alias a WHERE a.id_de = x0.vinho_id)))
       ORDER BY verificado_em DESC, id DESC
       LIMIT 200
    ) x
    LEFT JOIN winecatalog.vinhos v ON v.id = x.vinho_id
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.vivino_contar()
  RETURNS integer LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN RETURN 0; END IF;
  RETURN (SELECT count(*) FROM winecatalog.vivino_verificacoes x WHERE x.revisao = 'pendente'
            AND NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = x.vinho_id));
END;
$$;

-- Decidir. `aceite` grava a proposta (ou `p_campos`, quando o admin escolhe
-- um dos candidatos em vez dela) pela `editar` — a mesma porta de qualquer
-- correção à mão, com a mesma força e o mesmo registo do antes e depois.
CREATE OR REPLACE FUNCTION winecatalog.vivino_resolver(
  p_id bigint, p_decisao text, p_campos jsonb DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  r       winecatalog.vivino_verificacoes%ROWTYPE;
  v_alvo  bigint;
  v_campos jsonb;
  v_res   jsonb := NULL;
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo decide isto.';
  END IF;
  IF p_decisao NOT IN ('aceite','recusado','pendente') THEN
    RAISE EXCEPTION 'Decisão desconhecida: %', p_decisao;
  END IF;
  SELECT * INTO r FROM winecatalog.vivino_verificacoes WHERE id = p_id FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'Verificação não encontrada.'; END IF;

  IF p_decisao = 'aceite' THEN
    -- Só os três campos do Vivino, venha o que vier: isto não é uma porta
    -- para escrever outra coisa na ficha.
    SELECT COALESCE(jsonb_object_agg(key, value), '{}') INTO v_campos
      FROM jsonb_each(COALESCE(p_campos, r.proposta, '{}'))
     WHERE key IN ('vivino_url','vivino_nota','vivino_avaliacoes');
    IF v_campos = '{}'::jsonb THEN
      RAISE EXCEPTION 'Não há nada para aplicar nesta verificação.';
    END IF;
    -- Um vinho fundido DEPOIS de verificado: a proposta foi procurada pelo
    -- nome antigo, e aplicá-la ao vinho que ficou era pôr-lhe o link de
    -- outro (25/09/2026: o "Post" fundido no "Post Scriptum" tinha à espera
    -- o link de um "Post Reserve Cabernet Sauvignon" americano). Verifica-se
    -- outra vez o que ficou.
    SELECT id_para INTO v_alvo FROM winecatalog.alias WHERE id_de = r.vinho_id;
    IF v_alvo IS NOT NULL THEN
      RAISE EXCEPTION 'Este vinho foi fundido noutro (#%) depois de verificado — a proposta era para o nome antigo. Põe o que ficou na fila ("Verificar no Vivino").', v_alvo;
    END IF;
    v_res := winecatalog.editar(r.vinho_id, v_campos);
  END IF;

  UPDATE winecatalog.vivino_verificacoes
     SET revisao = p_decisao,
         revisto_em  = CASE WHEN p_decisao = 'pendente' THEN NULL ELSE now() END,
         revisto_por = CASE WHEN p_decisao = 'pendente' THEN NULL ELSE auth.email() END
   WHERE id = r.id;
  RETURN jsonb_build_object('ok', true, 'editar', v_res);
END;
$$;


-- =====================================================================
-- DO LADO DO BATCH (service_role — o GitHub Actions)
-- =====================================================================

-- Um vinho como o script o recebe. A ficha vai inteira: o script só
-- preenche os campos VAZIOS dela (castas, região, harmonização…) e tem de
-- saber quais são. Uma função só, para a fila e para o "Vinho novo".
CREATE OR REPLACE FUNCTION winecatalog.vivino_linha(v winecatalog.vinhos)
  RETURNS jsonb LANGUAGE sql STABLE
  SET search_path TO 'winecatalog', 'public'
AS $$
  SELECT jsonb_build_object(
    'id', v.id, 'nome', v.nome, 'produtor', v.produtor, 'ano', v.ano,
    'tipo', v.ficha ->> 'tipo',
    'vivino_url', v.ficha ->> 'vivino_url',
    'vivino_nota', v.ficha -> 'vivino_nota',
    'vivino_avaliacoes', v.ficha -> 'vivino_avaliacoes',
    'preco_medio', v.ficha -> 'preco_medio',
    'precos', v.ficha -> 'precos',
    -- De onde veio o preço médio e a imagem: no modo "só o Vivino" um preço
    -- de loja não se toca, e só se troca uma imagem que também veio do Vivino.
    'origem_preco', v.origens -> 'preco_medio' ->> 'o',
    'origem_imagem', v.origens -> 'imagem_url' ->> 'o',
    'ficha', v.ficha);
$$;

-- Hoje é dia? E, se for, que vinhos? Primeiro os da fila (pedidos à mão),
-- depois os que nunca foram vistos, depois os vistos há mais tempo. Quem
-- ainda tem uma verificação por decidir fica de fora — voltar a verificá-lo
-- era só acumular propostas para o mesmo vinho.
CREATE OR REPLACE FUNCTION winecatalog.vivino_a_tratar(
  p_manual boolean DEFAULT false, p_limite integer DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_freq  text;
  v_lote  integer;
  v_fila  jsonb;
  v_ult   date;
  v_hoje  date := (now() AT TIME ZONE 'Europe/Lisbon')::date;
  v_dia   boolean;
  v_ids   bigint[];
  v_resto integer;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  v_freq := COALESCE((SELECT valor FROM winecatalog.config WHERE chave = 'vivino_frequencia'), 'desligado');
  v_lote := COALESCE(p_limite, (SELECT valor FROM winecatalog.config WHERE chave = 'vivino_lote')::int, 10);
  v_lote := GREATEST(1, LEAST(v_lote, 50));
  v_fila := COALESCE((SELECT valor::jsonb FROM winecatalog.config WHERE chave = 'vivino_fila'), '[]');
  v_ult  := ((SELECT valor FROM winecatalog.config WHERE chave = 'vivino_ultima')::timestamptz
              AT TIME ZONE 'Europe/Lisbon')::date;

  v_dia := CASE v_freq
    WHEN 'diario'          THEN v_ult IS NULL OR v_hoje - v_ult >= 1
    WHEN 'dia_sim_dia_nao' THEN v_ult IS NULL OR v_hoje - v_ult >= 2
    WHEN 'semanal'         THEN v_ult IS NULL OR v_hoje - v_ult >= 7
    ELSE false END;

  IF NOT p_manual AND NOT v_dia AND jsonb_array_length(v_fila) = 0 THEN
    RETURN jsonb_build_object('correr', false,
      'motivo', format('frequência "%s", última execução %s', v_freq, COALESCE(v_ult::text, 'nunca')));
  END IF;

  -- A fila primeiro, pela ordem em que foi pedida.
  SELECT COALESCE(array_agg(i ORDER BY ord), '{}') INTO v_ids FROM (
    SELECT value::bigint i, ordinality ord
      FROM jsonb_array_elements_text(v_fila) WITH ORDINALITY
     WHERE EXISTS (SELECT 1 FROM winecatalog.vinhos v WHERE v.id = value::bigint)
       AND NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = value::bigint)
     LIMIT v_lote
  ) f;

  -- Só a fila, quando hoje não é dia: foram pedidos, o resto não.
  v_resto := CASE WHEN p_manual OR v_dia THEN v_lote - COALESCE(array_length(v_ids, 1), 0) ELSE 0 END;
  IF v_resto > 0 THEN
    v_ids := v_ids || COALESCE((
      SELECT array_agg(id ORDER BY ult NULLS FIRST, id) FROM (
        SELECT v.id, (SELECT max(verificado_em) FROM winecatalog.vivino_verificacoes x
                       WHERE x.vinho_id = v.id) ult
          FROM winecatalog.vinhos v
         WHERE NOT (v.id = ANY(v_ids))
           AND NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = v.id)
           AND NOT EXISTS (SELECT 1 FROM winecatalog.vivino_verificacoes x
                            WHERE x.vinho_id = v.id AND x.revisao = 'pendente')
         ORDER BY ult NULLS FIRST, v.id
         LIMIT v_resto
      ) s), '{}');
  END IF;

  RETURN jsonb_build_object('correr', COALESCE(array_length(v_ids, 1), 0) > 0,
    'motivo', CASE WHEN p_manual THEN 'manual' WHEN v_dia THEN v_freq ELSE 'fila' END,
    'vinhos', COALESCE((
      SELECT jsonb_agg(winecatalog.vivino_linha(v) ORDER BY array_position(v_ids, v.id))
      FROM winecatalog.vinhos v WHERE v.id = ANY(v_ids)), '[]'));
END;
$$;

-- Uma linha por vinho tratado. Tira o vinho da fila e carimba a execução.
-- `sem_acao` quando não há nada a decidir: o link está certo e os números
-- que a página mostra são os que o catálogo já tem.
-- `p_revisao`: desde 25/09/2026 o script APLICA o que encontrou (pela
-- `aplicar_fontes`) e grava a verificação como 'aceite' (revista pelo
-- script); 'sem_acao' para o que não tem nada a decidir. Sem ele, o
-- comportamento de antes: pendente para o admin.
DROP FUNCTION IF EXISTS winecatalog.vivino_gravar(bigint, jsonb, text);
CREATE OR REPLACE FUNCTION winecatalog.vivino_gravar(
  p_vinho_id bigint, p_res jsonb, p_execucao text DEFAULT NULL, p_revisao text DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v       winecatalog.vinhos%ROWTYPE;
  v_prop  jsonb := p_res -> 'proposta';
  v_rev   text := 'pendente';
  v_id    bigint;
  v_fila  jsonb;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  SELECT * INTO v FROM winecatalog.vinhos WHERE id = p_vinho_id;
  IF v.id IS NULL THEN RAISE EXCEPTION 'Vinho % não existe.', p_vinho_id; END IF;

  IF p_res ->> 'estado' = 'certo'
     AND (v_prop IS NULL OR (
          winecatalog.igual(v.ficha -> 'vivino_url', v_prop -> 'vivino_url')
      AND (v_prop -> 'vivino_nota' IS NULL OR winecatalog.igual(v.ficha -> 'vivino_nota', v_prop -> 'vivino_nota'))
      AND (v_prop -> 'vivino_avaliacoes' IS NULL OR winecatalog.igual(v.ficha -> 'vivino_avaliacoes', v_prop -> 'vivino_avaliacoes'))))
  THEN
    v_rev := 'sem_acao';
  END IF;
  -- Bloqueado ou erro não é uma resposta sobre o vinho: não fica à espera
  -- de decisão, e o vinho volta a entrar numa próxima noite.
  IF p_res ->> 'estado' IN ('bloqueado','erro') THEN v_rev := 'sem_acao'; END IF;
  IF p_revisao IN ('aceite','sem_acao','pendente') AND p_res ->> 'estado' NOT IN ('bloqueado','erro') THEN
    v_rev := p_revisao;
  END IF;

  INSERT INTO winecatalog.vivino_verificacoes
    (vinho_id, execucao, url_antes, estado, nome_pagina, proposta, candidatos, detalhe, revisao,
     revisto_em, revisto_por)
  VALUES
    -- `url_antes` a null quer dizer "não havia link": o script grava o
    -- vinho ANTES de registar a verificação, e o COALESCE punha aqui o link
    -- novo como se fosse o de antes.
    (v.id, p_execucao, CASE WHEN p_res ? 'url_antes' THEN p_res ->> 'url_antes' ELSE v.ficha ->> 'vivino_url' END,
     p_res ->> 'estado',
     p_res ->> 'nome_pagina', v_prop, p_res -> 'candidatos', p_res -> 'detalhe', v_rev,
     CASE WHEN v_rev = 'aceite' THEN now() END,
     CASE WHEN v_rev = 'aceite' THEN 'script' END)
  RETURNING id INTO v_id;

  v_fila := COALESCE((SELECT valor::jsonb FROM winecatalog.config WHERE chave = 'vivino_fila'), '[]');
  IF p_res ->> 'estado' NOT IN ('bloqueado','erro') THEN
    SELECT COALESCE(jsonb_agg(value ORDER BY ord), '[]') INTO v_fila
      FROM jsonb_array_elements(v_fila) WITH ORDINALITY AS e(value, ord)
     WHERE value::text::bigint <> v.id;
  END IF;
  INSERT INTO winecatalog.config (chave, valor) VALUES
    ('vivino_fila', v_fila::text), ('vivino_ultima', now()::text)
  ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor;
  RETURN v_id;
END;
$$;


-- ---------------------------------------------------------------------
-- APLICAR — o script escreve no catálogo (desde 25/09/2026, a pedido do
-- dono: "prefiro que atualizes o catálogo", com o histórico campo a campo
-- em `historico.sql` para ver e repor).
--
-- A mesma regra da `juntar`, campo a campo: entra se o campo está vazio ou
-- se a força desta origem (`forca(origem, campo)`) é igual ou maior do que
-- a que lá está. Um valor escrito à mão no rótulo (4) nunca é tapado; uma
-- nota lida na página do Vivino (3) atualiza a que lá estava. Pelo ID e não
-- pela chave: o script já sabe de que linha se trata.
--
-- Diz o que entrou e o que ficou de fora (e porquê) — é o que o script
-- mostra no fim de cada vinho.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.aplicar_fontes(
  p_vinho_id bigint, p_campos jsonb, p_origem text, p_quem text,
  p_fontes jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE
  v_id      bigint;
  v_ficha   jsonb;
  v_origens jsonb;
  v_fontes  jsonb;
  v_entrou  jsonb := '[]'::jsonb;
  v_ficou   jsonb := '[]'::jsonb;
  k         text;
  v         jsonb;
  v_f       integer;
  v_ant     integer;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  IF winecatalog.forca(p_origem) <= 0 THEN
    RAISE EXCEPTION 'Origem sem força: %', p_origem;
  END IF;
  v_id := COALESCE((SELECT id_para FROM winecatalog.alias WHERE id_de = p_vinho_id), p_vinho_id);
  SELECT ficha, origens, fontes INTO v_ficha, v_origens, v_fontes
    FROM winecatalog.vinhos WHERE id = v_id FOR UPDATE;
  IF v_ficha IS NULL THEN RAISE EXCEPTION 'Vinho % não existe.', p_vinho_id; END IF;

  PERFORM set_config('winecatalog.quem', COALESCE(NULLIF(p_quem, ''), 'script'), true);

  FOR k, v IN SELECT key, value FROM jsonb_each(COALESCE(p_campos, '{}')) LOOP
    CONTINUE WHEN k !~ '^[a-z][a-z0-9_]{0,39}$' OR winecatalog.vazio(v);
    -- A mesma normalização da `juntar`/`criar`: "DOURO" não entra assim.
    IF k = 'regiao' AND jsonb_typeof(v) = 'string' THEN
      v := to_jsonb(winecatalog.normalizar_regiao(v #>> '{}'));
    END IF;
    v_f   := winecatalog.forca(p_origem, k);
    v_ant := COALESCE((v_origens -> k ->> 'f')::integer, 0);
    IF v_f >= v_ant THEN
      v_ficha   := v_ficha || jsonb_build_object(k, v);
      v_origens := v_origens || jsonb_build_object(k, jsonb_build_object('o', p_origem, 'f', v_f, 'em', now()));
      v_entrou  := v_entrou || to_jsonb(k);
    ELSE
      v_ficou := v_ficou || jsonb_build_object('campo', k, 'origem', v_origens -> k ->> 'o', 'forca', v_ant);
    END IF;
  END LOOP;

  IF p_fontes IS NOT NULL AND jsonb_typeof(p_fontes) = 'array' AND jsonb_array_length(p_fontes) > 0 THEN
    SELECT COALESCE(jsonb_agg(f), '[]'::jsonb) INTO v_fontes FROM (
      SELECT DISTINCT ON (f ->> 'url') f
        FROM jsonb_array_elements(COALESCE(v_fontes, '[]') || p_fontes) f
       WHERE COALESCE(f ->> 'url', '') <> ''
       ORDER BY (f ->> 'url') LIMIT 8) x;
  END IF;

  UPDATE winecatalog.vinhos
     SET ficha = v_ficha, origens = v_origens, fontes = COALESCE(v_fontes, fontes),
         atualizado_em = CASE WHEN jsonb_array_length(v_entrou) > 0 THEN now() ELSE atualizado_em END
   WHERE id = v_id;
  RETURN jsonb_build_object('vinho', v_id, 'entrou', v_entrou, 'ficou', v_ficou);
END;
$$;


-- ---------------------------------------------------------------------
-- VINHO NOVO pelo painel do vinhos.bat (25/09/2026). O admin escreve nome,
-- produtor, ano e cor; o script procura no Vivino e nas lojas e só DEPOIS de
-- o admin rever a simulação é que a linha nasce.
-- `vivino_achar`: já existe? (a MESMA `achar` do `juntar`/`criar`, às duas
-- chaves). `vivino_novo`: cria pela `criar` — que recusa um duplicado —, ou
-- devolve a que já existe se entretanto alguém a criou.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.vivino_achar(p_nome text, p_produtor text, p_ano integer)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_id bigint; v winecatalog.vinhos;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  v_id := winecatalog.achar(btrim(COALESCE(p_nome, '')), COALESCE(p_produtor, ''), p_ano, true);
  IF v_id IS NULL THEN RETURN NULL; END IF;
  v_id := COALESCE((SELECT id_para FROM winecatalog.alias WHERE id_de = v_id), v_id);
  SELECT * INTO v FROM winecatalog.vinhos WHERE id = v_id;
  RETURN winecatalog.vivino_linha(v);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.vivino_novo(
  p_nome text, p_produtor text, p_ano integer, p_tipo text, p_quem text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
DECLARE v_ja jsonb; v_r jsonb;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  v_ja := winecatalog.vivino_achar(p_nome, p_produtor, p_ano);
  IF v_ja IS NOT NULL THEN
    RETURN jsonb_build_object('id', v_ja -> 'id', 'existia', true);
  END IF;
  PERFORM set_config('winecatalog.quem', COALESCE(NULLIF(p_quem, ''), 'script'), true);
  -- A cor foi o admin que a escolheu no painel: entra como uma correção à
  -- mão (a `criar` dá-lhe a força de `catalogo-admin`).
  v_r := winecatalog.criar(p_nome, COALESCE(p_produtor, ''), p_ano,
           CASE WHEN COALESCE(p_tipo, '') <> '' THEN jsonb_build_object('tipo', p_tipo) ELSE '{}'::jsonb END);
  RETURN jsonb_build_object('id', v_r -> 'id', 'existia', false);
END;
$$;


-- ---------------------------------------------------------------------
-- ESCOLHER NO PAINEL (25/09/2026). O painel do vinhos.bat mostra o catálogo
-- e o admin marca os vinhos a tratar. `vivino_catalogo`: a lista, leve (o
-- que ajuda a escolher — tem fotografia? preço? quando foi visto?), sem os
-- fundidos. `vivino_estes`: esses vinhos, na forma que o script recebe, pela
-- ordem marcada; um id fundido responde pelo vinho que ficou.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION winecatalog.vivino_catalogo()
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', v.id, 'nome', v.nome, 'produtor', v.produtor, 'ano', v.ano,
      'tipo', v.ficha ->> 'tipo', 'regiao', v.ficha ->> 'regiao',
      'imagem', v.ficha ? 'imagem_url', 'preco', v.ficha ? 'preco_medio', 'vivino', v.ficha ? 'vivino_url',
      -- O formato do link: 'ok' (/<nome>/w/<nº>, limpo), 'por_limpar' (tem o
      -- número do vinho mas também país/língua/?year= — funciona, e o script
      -- arruma-o quando passa), 'invalido' (sem /w/<nº>: /wines/<nº> é UMA
      -- colheita, /Wines/<nome> não existe — o que as pesquisas de memória
      -- inventam). A mesma regra do `urlLimpo` do script.
      'link', CASE WHEN COALESCE(v.ficha ->> 'vivino_url', '') = '' THEN NULL
                   WHEN v.ficha ->> 'vivino_url' ~ '^https://www\.vivino\.com/[a-z0-9-]+/w/[0-9]+$' THEN 'ok'
                   WHEN v.ficha ->> 'vivino_url' ~ '^https?://([a-z]+\.)?vivino\.com/.*/w/[0-9]+' THEN 'por_limpar'
                   ELSE 'invalido' END,
      'campos', (SELECT count(*) FROM jsonb_object_keys(v.ficha)),
      'visto', (SELECT max(x.verificado_em) FROM winecatalog.vivino_verificacoes x WHERE x.vinho_id = v.id))
      ORDER BY lower(v.nome), v.ano NULLS FIRST)
    FROM winecatalog.vinhos v
    WHERE NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = v.id)), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.vivino_estes(p_ids bigint[])
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Só o batch (service_role) chama isto.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(winecatalog.vivino_linha(v) ORDER BY o.ord)
      FROM (SELECT DISTINCT ON (alvo) alvo, ord FROM (
              SELECT COALESCE((SELECT id_para FROM winecatalog.alias WHERE id_de = i), i) alvo, ord
                FROM unnest(p_ids[1:50]) WITH ORDINALITY AS u(i, ord)) z
            ORDER BY alvo, ord) o
      JOIN winecatalog.vinhos v ON v.id = o.alvo), '[]'::jsonb);
END;
$$;


-- =====================================================================
-- GRANTS — cada função nasce com EXECUTE para PUBLIC; tira-se sempre.
-- =====================================================================
REVOKE ALL ON winecatalog.vivino_verificacoes FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON winecatalog.vivino_verificacoes TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA winecatalog TO service_role;

REVOKE ALL ON FUNCTION winecatalog.vivino_config()                         FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.vivino_definir(text, integer)           FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.vivino_pedir(bigint[])                  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.vivino_listar(text)                     FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.vivino_contar()                         FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION winecatalog.vivino_resolver(bigint, text, jsonb)    FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_config()                      TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_definir(text, integer)        TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_pedir(bigint[])               TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_listar(text)                  TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_contar()                      TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_resolver(bigint, text, jsonb) TO authenticated;

REVOKE ALL ON FUNCTION winecatalog.vivino_a_tratar(boolean, integer)       FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.vivino_gravar(bigint, jsonb, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.aplicar_fontes(bigint, jsonb, text, text, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.aplicar_fontes(bigint, jsonb, text, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_a_tratar(boolean, integer)    TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_gravar(bigint, jsonb, text, text) TO service_role;
REVOKE ALL ON FUNCTION winecatalog.vivino_linha(winecatalog.vinhos)          FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.vivino_achar(text, text, integer)         FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.vivino_novo(text, text, integer, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_linha(winecatalog.vinhos)       TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_achar(text, text, integer)      TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_novo(text, text, integer, text, text) TO service_role;
REVOKE ALL ON FUNCTION winecatalog.vivino_catalogo()       FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION winecatalog.vivino_estes(bigint[])   FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_catalogo()     TO service_role;
GRANT EXECUTE ON FUNCTION winecatalog.vivino_estes(bigint[]) TO service_role;

-- Confirmar (deve dar ZERO linhas):
-- SELECT p.proname, r.rolname FROM pg_proc p
--   JOIN pg_namespace n ON n.oid = p.pronamespace
--   CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl, acldefault('f', p.proowner))) a
--   JOIN pg_roles r ON r.oid = a.grantee
--  WHERE n.nspname = 'winecatalog' AND p.proname LIKE 'vivino%'
--    AND r.rolname IN ('anon') ;
